MLIR: lib/AsmParser/AffineParser.cpp File Reference
AffineParser.cpp File Reference
#include "Parser.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/IntegerSet.h"
#include "llvm/Support/SourceMgr.h"
Functions
static bool isIdentifier (const Token &token)
Returns true if the given token can be represented as an identifier.
static void parseAffineMapOrIntegerSet (StringRef inputStr, MLIRContext *context, AffineMap &map, IntegerSet &set)
Function Documentation
isIdentifier()
static bool isIdentifier (const Token & token) static
Returns true if the given token can be represented as an identifier.
Definition at line 269 of file AffineParser.cpp.
References mlir::Token::isAny(), and mlir::Token::isKeyword().
parseAffineMapOrIntegerSet()
static void parseAffineMapOrIntegerSet (StringRef inputStr, MLIRContext * context, AffineMap & map, IntegerSet & set) static
Definition at line 737 of file AffineParser.cpp.
References mlir::detail::Parser::emitError(), mlir::Token::getLoc(), mlir::detail::Parser::getToken(), mlir::Token::isNot(), and mlir::detail::Parser::parseAffineMapOrIntegerSetReference().