MLIR: lib/Dialect/Arith/IR/ArithOps.cpp File Reference
ArithOps.cpp File Reference
#include <cassert>
#include <utility>
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/TypeSwitch.h"
#include "ArithCanonicalization.inc"
#include "mlir/Dialect/Arith/IR/ArithOps.cpp.inc"
#include "mlir/Dialect/Arith/IR/ArithOpsEnums.cpp.inc"
Classes
class CmpFIntToFPConst
struct SelectI1Simplify
struct SelectToExtUI
Macros
#define GET_OP_CLASSES
Typedefs
template<typename... Types>
using type_list = std::tuple< Types... > *
Functions
static IntegerAttr addIntegerAttrs (PatternRewriter &builder, Value res, Attribute lhs, Attribute rhs)
static IntegerAttr subIntegerAttrs (PatternRewriter &builder, Value res, Attribute lhs, Attribute rhs)
static arith::CmpIPredicateAttr invertPredicate (arith::CmpIPredicateAttr pred)
static APInt calculateCarry (const APInt &sum, const APInt &operand)
static APInt signedCeilNonnegInputs (const APInt &a, const APInt &b, bool &overflow)
static Value foldAndIofAndI (arith::AndIOp op)
Fold and(a, and(a, b)) to and(a, b)
template<typename... ShapedTypes, typename... ElementTypes>
static Type getUnderlyingType (Type type, type_list< ShapedTypes... >, type_list< ElementTypes... >)
Returns a non-null type only if the provided type is one of the allowed types or one of the allowed shaped types of the allowed types.
template<typename... ElementTypes>
static Type getTypeIfLike (Type type)
Get allowed underlying types for vectors and tensors.
template<typename... ElementTypes>
static Type getTypeIfLikeOrMemRef (Type type)
Get allowed underlying types for vectors, tensors, and memrefs.
static bool areValidCastInputsAndOutputs (TypeRange inputs, TypeRange outputs)
template<typename ValType , typename Op >
static LogicalResult verifyExtOp (Op op)
template<typename ValType , typename Op >
static LogicalResult verifyTruncateOp (Op op)
template<template< typename > class WidthComparator, typename... ElementTypes>
static bool checkWidthChangeCast (TypeRange inputs, TypeRange outputs)
Validate a cast that changes the width of a type.
template<typename From , typename To >
static bool checkIntFloatCast (TypeRange inputs, TypeRange outputs)
static bool areIndexCastCompatible (TypeRange inputs, TypeRange outputs)
static Type getI1SameShape (Type type)
Return the type of the same shape (scalar, vector or tensor) containing i1.
static bool applyCmpPredicateToEqualOperands (arith::CmpIPredicate predicate)
Returns true if the predicate is true for two equal operands.
static Attribute getBoolAttribute (Type type, MLIRContext *ctx, bool value)
static Optional< int64_t > getIntegerWidth (Type t)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2255 of file ArithOps.cpp.
Typedef Documentation
type_list
template<typename... Types> using type_list = std::tuple<Types...> *
Definition at line 953 of file ArithOps.cpp.
Function Documentation
addIntegerAttrs()
static IntegerAttr addIntegerAttrs (PatternRewriter & builder, Value res, Attribute lhs, Attribute rhs) static
Definition at line 31 of file ArithOps.cpp.
applyCmpPredicateToEqualOperands()
static bool applyCmpPredicateToEqualOperands (arith::CmpIPredicate predicate) static
Returns true if the predicate is true for two equal operands.
Definition at line 1479 of file ArithOps.cpp.
areIndexCastCompatible()
static bool areIndexCastCompatible (TypeRange inputs, TypeRange outputs) static
Definition at line 1322 of file ArithOps.cpp.
References areValidCastInputsAndOutputs().
areValidCastInputsAndOutputs()
static bool areValidCastInputsAndOutputs (TypeRange inputs, TypeRange outputs) static
Definition at line 986 of file ArithOps.cpp.
References mlir::succeeded(), and mlir::verifyCompatibleShapes().
Referenced by areIndexCastCompatible(), checkIntFloatCast(), and checkWidthChangeCast().
calculateCarry()
static APInt calculateCarry (const APInt & sum, const APInt & operand) static
Definition at line 233 of file ArithOps.cpp.
References getZero().
checkIntFloatCast()
template<typename From , typename To > static bool checkIntFloatCast (TypeRange inputs, TypeRange outputs) static
Definition at line 1205 of file ArithOps.cpp.
References areValidCastInputsAndOutputs().
checkWidthChangeCast()
template<template< typename > class WidthComparator, typename... ElementTypes> static bool checkWidthChangeCast (TypeRange inputs, TypeRange outputs) static
Validate a cast that changes the width of a type.
Definition at line 1023 of file ArithOps.cpp.
References areValidCastInputsAndOutputs(), and getTypeIfLike().
foldAndIofAndI()
static Value foldAndIofAndI (arith::AndIOp op) static
Fold and(a, and(a, b)) to and(a, b)
Definition at line 616 of file ArithOps.cpp.
getBoolAttribute()
static Attribute getBoolAttribute (Type type, MLIRContext * ctx, bool value) static
Definition at line 1497 of file ArithOps.cpp.
References mlir::Type::dyn_cast_or_null(), mlir::BoolAttr::get(), mlir::DenseElementsAttr::get(), and value.
getI1SameShape()
static Type getI1SameShape (Type type) static
Return the type of the same shape (scalar, vector or tensor) containing i1.
Definition at line 1433 of file ArithOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getContext(), and mlir::Type::isa().
getIntegerWidth()
static Optional<int64_t> getIntegerWidth (Type t) static
Definition at line 1505 of file ArithOps.cpp.
References mlir::Type::dyn_cast().
getTypeIfLike()
template<typename... ElementTypes> static Type getTypeIfLike (Type type) static
Get allowed underlying types for vectors and tensors.
Definition at line 973 of file ArithOps.cpp.
References getUnderlyingType().
Referenced by checkWidthChangeCast().
getTypeIfLikeOrMemRef()
template<typename... ElementTypes> static Type getTypeIfLikeOrMemRef (Type type) static
Get allowed underlying types for vectors, tensors, and memrefs.
Definition at line 980 of file ArithOps.cpp.
References getUnderlyingType().
getUnderlyingType()
template<typename... ShapedTypes, typename... ElementTypes> static Type getUnderlyingType (Type type, type_list< ShapedTypes... > , type_list< ElementTypes... >) static
Returns a non-null type only if the provided type is one of the allowed types or one of the allowed shaped types of the allowed types.
Returns the element type if a valid shaped type is provided.
Definition at line 959 of file ArithOps.cpp.
References mlir::getElementTypeOrSelf(), and mlir::Type::isa().
Referenced by getTypeIfLike(), and getTypeIfLikeOrMemRef().
invertPredicate()
static arith::CmpIPredicateAttr invertPredicate (arith::CmpIPredicateAttr pred) static
Definition at line 72 of file ArithOps.cpp.
References mlir::arith::invertPredicate().
signedCeilNonnegInputs()
static APInt signedCeilNonnegInputs (const APInt & a, const APInt & b, bool & overflow) static
Definition at line 415 of file ArithOps.cpp.
subIntegerAttrs()
static IntegerAttr subIntegerAttrs (PatternRewriter & builder, Value res, Attribute lhs, Attribute rhs) static
Definition at line 38 of file ArithOps.cpp.
verifyExtOp()
template<typename ValType , typename Op > static LogicalResult verifyExtOp (Op op) static
Definition at line 997 of file ArithOps.cpp.
References mlir::Type::cast(), mlir::OpState::emitError(), mlir::getElementTypeOrSelf(), and mlir::success().
verifyTruncateOp()
template<typename ValType , typename Op > static LogicalResult verifyTruncateOp (Op op) static
Definition at line 1010 of file ArithOps.cpp.
References mlir::Type::cast(), mlir::OpState::emitError(), mlir::getElementTypeOrSelf(), and mlir::success().