MLIR: lib/Dialect/Async/Transforms/AsyncRuntimeRefCounting.cpp File Reference
AsyncRuntimeRefCounting.cpp File Reference
#include "mlir/Dialect/Async/Passes.h"
#include "mlir/Analysis/Liveness.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/SmallSet.h"
#include "mlir/Dialect/Async/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_ASYNCRUNTIMEREFCOUNTING
#define GEN_PASS_DEF_ASYNCRUNTIMEPOLICYBASEDREFCOUNTING
#define DEBUG_TYPE "async-runtime-ref-counting"
Functions
static LogicalResult dropRefIfNoUses (Value value, unsigned count=1)
static LogicalResult walkReferenceCountedValues (Operation *op, llvm::function_ref< LogicalResult(Value)> addRefCounting)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "async-runtime-ref-counting"
Definition at line 31 of file AsyncRuntimeRefCounting.cpp.
GEN_PASS_DEF_ASYNCRUNTIMEPOLICYBASEDREFCOUNTING
#define GEN_PASS_DEF_ASYNCRUNTIMEPOLICYBASEDREFCOUNTING
Definition at line 27 of file AsyncRuntimeRefCounting.cpp.
GEN_PASS_DEF_ASYNCRUNTIMEREFCOUNTING
#define GEN_PASS_DEF_ASYNCRUNTIMEREFCOUNTING
Definition at line 26 of file AsyncRuntimeRefCounting.cpp.
Function Documentation
dropRefIfNoUses()
static LogicalResult dropRefIfNoUses (Value value, unsigned count = 1) static
Definition at line 41 of file AsyncRuntimeRefCounting.cpp.
References mlir::OpBuilder::create(), mlir::failure(), mlir::Builder::getI64IntegerAttr(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and value.
walkReferenceCountedValues()
static LogicalResult walkReferenceCountedValues (Operation * op, llvm::function_ref< LogicalResult(Value)> addRefCounting) static
Definition at line 60 of file AsyncRuntimeRefCounting.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Block::getArguments(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), mlir::WalkResult::interrupt(), mlir::async::isRefCounted(), mlir::success(), mlir::Operation::walk(), and mlir::WalkResult::wasInterrupted().