MLIR: lib/Dialect/Bufferization/Transforms/Bufferize.cpp File Reference
Bufferize.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotModuleBufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/Transforms.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::bufferization
Macros
#define GEN_PASS_DEF_FINALIZINGBUFFERIZE
#define GEN_PASS_DEF_BUFFERIZATIONBUFFERIZE
#define GEN_PASS_DEF_ONESHOTBUFFERIZE
#define DEBUG_TYPE "bufferize"
Functions
static Value materializeToTensor (OpBuilder &builder, TensorType type, ValueRange inputs, Location loc)
static bool isaTensor (Type t)
static bool hasTensorSemantics (Operation *op)
Return true if the given op has a tensor result or a tensor operand.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bufferize"
Definition at line 34 of file Bufferize.cpp.
GEN_PASS_DEF_BUFFERIZATIONBUFFERIZE
#define GEN_PASS_DEF_BUFFERIZATIONBUFFERIZE
Definition at line 28 of file Bufferize.cpp.
GEN_PASS_DEF_FINALIZINGBUFFERIZE
#define GEN_PASS_DEF_FINALIZINGBUFFERIZE
Definition at line 27 of file Bufferize.cpp.
GEN_PASS_DEF_ONESHOTBUFFERIZE
#define GEN_PASS_DEF_ONESHOTBUFFERIZE
Definition at line 29 of file Bufferize.cpp.
Function Documentation
hasTensorSemantics()
static bool hasTensorSemantics (Operation * op) static
Return true if the given op has a tensor result or a tensor operand.
Definition at line 320 of file Bufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), and isaTensor().
Referenced by mlir::bufferization::bufferizeOp().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 317 of file Bufferize.cpp.
References mlir::Type::isa().
Referenced by hasTensorSemantics().
materializeToTensor()
static Value materializeToTensor (OpBuilder & builder, TensorType type, ValueRange inputs, Location loc) static
Definition at line 43 of file Bufferize.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter().