MLIR: mlir::sparse_tensor::SparseTensorEnumeratorBase< V > Class Template Reference
mlir::sparse_tensor::SparseTensorEnumeratorBase< V > Class Template Reference abstract
A (higher-order) function object for enumerating the elements of some SparseTensorStorage under a permutation.
#include "mlir/ExecutionEngine/SparseTensor/Storage.h"
Public Member Functions
SparseTensorEnumeratorBase (const SparseTensorStorageBase &src, uint64_t trgRank, const uint64_t *trgSizes, uint64_t srcRank, const uint64_t *src2trg)
Constructs an enumerator which automatically applies the given mapping from the source tensor's dimensions to the desired target tensor dimensions.
virtual ~SparseTensorEnumeratorBase ()=default
SparseTensorEnumeratorBase (const SparseTensorEnumeratorBase &)=delete
SparseTensorEnumeratorBase & operator= (const SparseTensorEnumeratorBase &)=delete
uint64_t getSrcDimRank () const
Gets the source's dimension-rank.
uint64_t getTrgRank () const
Gets the target's dimension-/level-rank.
const std::vector< uint64_t > & getTrgSizes () const
Gets the target's dimension-/level-sizes.
virtual void forallElements (ElementConsumer< V > yield)=0
Enumerates all elements of the source tensor, permutes their indices, and passes the permuted element to the callback.
Protected Attributes
const SparseTensorStorageBase & src
std::vector< uint64_t > trgSizes
std::vector< uint64_t > lvl2trg
std::vector< uint64_t > trgCursor
Detailed Description
template<typename V>
class mlir::sparse_tensor::SparseTensorEnumeratorBase< V >
A (higher-order) function object for enumerating the elements of some SparseTensorStorage under a permutation.
That is, the forallElements method encapsulates the loop-nest for enumerating the elements of the source tensor (in whatever order is best for the source tensor), and applies a permutation to the coordinates/indices before handing each element to the callback. A single enumerator object can be freely reused for several calls to forallElements, just so long as each call is sequential with respect to one another.
N.B., this class stores a reference to the SparseTensorStorageBase passed to the constructor; thus, objects of this class must not outlive the sparse tensor they depend on.
Design Note: The reason we define this class instead of simply using SparseTensorEnumerator<P,I,V> is because we need to hide/generalize the <P,I> template parameters from MLIR client code (to simplify the type parameters used for direct sparse-to-sparse conversion). And the reason we define the SparseTensorEnumerator<P,I,V> subclasses rather than simply using this class, is to avoid the cost of virtual-method dispatch within the loop-nest.
Definition at line 720 of file Storage.h.
Constructor & Destructor Documentation
SparseTensorEnumeratorBase() [1/2]
template<typename V > mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::SparseTensorEnumeratorBase (const SparseTensorStorageBase & src, uint64_t trgRank, const uint64_t * trgSizes, uint64_t srcRank, const uint64_t * src2trg) inline
Constructs an enumerator which automatically applies the given mapping from the source tensor's dimensions to the desired target tensor dimensions.
Preconditions:
the src must have the same V value type.
trgSizes must be valid for trgRank.
src2trg must be valid for srcRank, and must map indices valid for src.getDimSizes() to indices valid for trgSizes.
Asserts:
trgSizes must be nonnull and must contain only nonzero sizes.
srcRank == src.getDimRank().
src2trg must be nonnull.
Definition at line 736 of file Storage.h.
References mlir::sparse_tensor::SparseTensorStorageBase::getDimRank(), mlir::sparse_tensor::SparseTensorStorageBase::getLvl2Dim(), and mlir::sparse_tensor::SparseTensorStorageBase::getLvlRank().
~SparseTensorEnumeratorBase()
template<typename V > virtual mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::~SparseTensorEnumeratorBase () virtual default
SparseTensorEnumeratorBase() [2/2]
template<typename V > mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::SparseTensorEnumeratorBase (const SparseTensorEnumeratorBase< V > &) delete
Member Function Documentation
forallElements()
template<typename V > virtual void mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::forallElements (ElementConsumer< V > yield) pure virtual
Enumerates all elements of the source tensor, permutes their indices, and passes the permuted element to the callback.
The callback must not store the cursor reference directly, since this function reuses the storage. Instead, the callback must copy it if they want to keep it.
Implemented in mlir::sparse_tensor::SparseTensorEnumerator< P, I, V >.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::initialize(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
getSrcDimRank()
template<typename V > uint64_t mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getSrcDimRank () const inline
Gets the source's dimension-rank.
Definition at line 760 of file Storage.h.
getTrgRank()
template<typename V > uint64_t mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getTrgRank () const inline
Gets the target's dimension-/level-rank.
(This is usually "dimension-rank", though that may coincide with "level-rank" depending on usage.)
Definition at line 765 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::initialize(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
getTrgSizes()
template<typename V > const std::vector<uint64_t>& mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getTrgSizes () const inline
Gets the target's dimension-/level-sizes.
(These are usually "dimensions", though that may coincide with "level-rank" depending on usage.)
Definition at line 770 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::initialize().
operator=()
template<typename V > SparseTensorEnumeratorBase& mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::operator= (const SparseTensorEnumeratorBase< V > &) delete
Member Data Documentation
lvl2trg
template<typename V > std::vector<uint64_t> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::lvl2trg protected
Definition at line 782 of file Storage.h.
src
template<typename V > const SparseTensorStorageBase& mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::src protected
Definition at line 780 of file Storage.h.
trgCursor
template<typename V > std::vector<uint64_t> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::trgCursor protected
Definition at line 783 of file Storage.h.
trgSizes
template<typename V > std::vector<uint64_t> mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::trgSizes protected
Definition at line 781 of file Storage.h.
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/SparseTensor/Storage.h