MLIR: mlir::FlatAffineRelation Class Reference
mlir::FlatAffineRelation Class Reference
A FlatAffineRelation represents a set of ordered pairs (domain -> range) where "domain" and "range" are tuples of variables.
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
Public Member Functions
FlatAffineRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDomainDims, unsigned numRangeDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs={})
FlatAffineRelation (unsigned numDomainDims=0, unsigned numRangeDims=0, unsigned numSymbols=0, unsigned numLocals=0)
FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, FlatAffineValueConstraints &fac)
FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, IntegerPolyhedron &fac)
FlatAffineValueConstraints getDomainSet () const
Returns a set corresponding to the domain/range of the affine relation.
FlatAffineValueConstraints getRangeSet () const
unsigned getNumDomainDims () const
Returns the number of variables corresponding to domain/range of relation.
unsigned getNumRangeDims () const
void compose (const FlatAffineRelation &other)
Given affine relation other: (domainOther -> rangeOther), this operation takes the composition of other on this: (domainThis -> rangeThis).
void inverse ()
Swap domain and range of the relation.
void insertDomainVar (unsigned pos, unsigned num=1)
Insert num variables of the specified kind after the pos variable of that kind.
void insertRangeVar (unsigned pos, unsigned num=1)
void appendDomainVar (unsigned num=1)
Append num variables of the specified kind after the last variable of that kind.
void appendRangeVar (unsigned num=1)
void removeVarRange (VarKind kind, unsigned varStart, unsigned varLimit) override
Removes variables in the column range [varStart, varLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Public Member Functions inherited from mlir::FlatAffineValueConstraints
FlatAffineValueConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs={})
Constructs a constraint system reserving memory for the specified number of constraints and variables.
FlatAffineValueConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0, ArrayRef< Optional< Value >> valArgs={})
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineValueConstraints (const IntegerPolyhedron &fac, ArrayRef< Optional< Value >> valArgs={})
FlatAffineValueConstraints (const AffineValueMap &avm)
Create a flat affine constraint system from an AffineValueMap or a list of these.
FlatAffineValueConstraints (ArrayRef< const AffineValueMap * > avmRef)
FlatAffineValueConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineValueConstraints (ArrayRef< const AffineValueMap * > avmRef, IntegerSet set)
Kind getKind () const override
Return the kind of this FlatAffineConstraints.
void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0)
Clears any existing data and reserves memory for the specified constraints.
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
void reset (unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
std::unique_ptr< FlatAffineValueConstraints > clone () const
Clones this object.
LogicalResult addAffineForOpDomain (AffineForOp forOp)
Adds constraints (lower and upper bounds) for the specified 'affine.for' operation's Value using IR information stored in its bound maps.
LogicalResult addDomainFromSliceMaps (ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds constraints (lower and upper bounds) for each loop in the loop nest described by the bound maps lbMaps and ubMaps of a computation slice.
void addAffineIfOpDomain (AffineIfOp ifOp)
Adds constraints imposed by the affine.if operation.
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap, bool isClosedBound)
Adds a bound for the variable at the specified position with constraints being drawn from the specified bound map.
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap)
Adds a bound for the variable at the specified position with constraints being drawn from the specified bound map.
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap, ValueRange operands)
Adds a bound for the variable at the specified position with constraints being drawn from the specified bound map and operands.
void addBound (BoundType type, Value val, int64_t value)
Adds a constant bound for the variable associated with the given Value.
IntegerSet getAsIntegerSet (MLIRContext *context) const
Returns the constraint system as an integer set.
void getSliceBounds (unsigned offset, unsigned num, MLIRContext *context, SmallVectorImpl< AffineMap > *lbMaps, SmallVectorImpl< AffineMap > *ubMaps, bool getClosedUB=false)
Computes the lower and upper bounds of the first num dimensional variables (starting at offset) as an affine map of the remaining variables (dimensional and symbolic).
LogicalResult composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatAffineConstraints.
std::pair< AffineMap, AffineMap > getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext *context) const
Gets the lower and upper bound of the offset + posth variable treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolVars) as symbols, and pos lies in [0, num).
void getIneqAsAffineValueMap (unsigned pos, unsigned ineqPos, AffineValueMap &vmap, MLIRContext *context) const
Returns the bound for the variable at pos from the inequality at ineqPos as a 1-d affine value map (affine map + operands).
LogicalResult addSliceBounds (ArrayRef< Value > values, ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds slice lower bounds represented by lower bounds in lbMaps and upper bounds in ubMaps to each variable in the constraint system which has a value in values.
bool findVar (Value val, unsigned *pos) const
Looks up the position of the variable with the specified Value.
bool containsVar (Value mayBeVar) const
Returns true if an variable with the specified Value exists, false otherwise.
void swapVar (unsigned posA, unsigned posB) override
Swap the posA^th variable with the posB^th variable.
unsigned insertDimVar (unsigned pos, unsigned num=1)
Insert variables of the specified kind at position pos.
unsigned insertSymbolVar (unsigned pos, unsigned num=1)
unsigned insertLocalVar (unsigned pos, unsigned num=1)
unsigned insertDimVar (unsigned pos, ValueRange vals)
unsigned insertSymbolVar (unsigned pos, ValueRange vals)
unsigned insertVar (presburger::VarKind kind, unsigned pos, unsigned num=1) override
Insert num variables of the specified kind at position pos.
unsigned insertVar (presburger::VarKind kind, unsigned pos, ValueRange vals)
unsigned appendDimVar (ValueRange vals)
Append variables of the specified kind after the last variable of that kind.
unsigned appendSymbolVar (ValueRange vals)
unsigned appendDimVar (unsigned num=1)
unsigned appendSymbolVar (unsigned num=1)
unsigned appendLocalVar (unsigned num=1)
void addInductionVarOrTerminalSymbol (Value val)
Add the specified values as a dim or symbol var depending on its nature, if it already doesn't exist in the system.
AffineMap computeAlignedMap (AffineMap map, ValueRange operands) const
Align map with this constraint system based on operands.
LogicalResult composeMap (const AffineValueMap *vMap)
Composes the affine value map with this FlatAffineValueConstrains, adding the results of the map as dimensions at the front [0, vMap->getNumResults()) and with the dimensions set to the equalities specified by the value map.
void projectOut (Value val)
Projects out the variable that is associate with Value.
void convertLoopIVSymbolsToDims ()
Changes all symbol variables which are loop IVs to dim variables.
LogicalResult unionBoundingBox (const FlatAffineValueConstraints &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
void mergeAndAlignVarsWithOther (unsigned offset, FlatAffineValueConstraints *other)
Merge and align the variables of this and other starting at offset, so that both constraint systems get the union of the contained variables that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all variables, with this's original variables appearing first followed by any of other's variables that didn't appear in this.
bool areVarsAlignedWithOther (const FlatAffineValueConstraints &other)
Returns true if this constraint system and other are in the same space, i.e., if they are associated with the same set of variables, appearing in the same order.
void clearAndCopyFrom (const IntegerRelation &other) override
Replaces the contents of this FlatAffineValueConstraints with other.
Value getValue (unsigned pos) const
Returns the Value associated with the pos^th variable.
bool hasValue (unsigned pos) const
Returns true if the pos^th variable has an associated Value.
bool hasValues () const
Returns true if at least one variable has an associated Value.
void getValues (unsigned start, unsigned end, SmallVectorImpl< Value > *values) const
Returns the Values associated with variables in range [start, end).
void getAllValues (SmallVectorImpl< Value > *values) const
ArrayRef< Optional< Value > > getMaybeValues () const
ArrayRef< Optional< Value > > getMaybeValues (presburger::VarKind kind) const
void setValue (unsigned pos, Value val)
Sets the Value associated with the pos^th variable.
void setValues (unsigned start, unsigned end, ArrayRef< Value > values)
Sets the Values associated with the variables in the range [start, end).
void mergeSymbolVars (FlatAffineValueConstraints &other)
Merge and align symbols of this and other such that both get union of of symbols that are unique.
Public Member Functions inherited from mlir::presburger::IntegerPolyhedron
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a set reserving memory for the specified number of constraints and variables.
IntegerPolyhedron (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
IntegerPolyhedron (const IntegerRelation &rel)
Construct a set from an IntegerRelation.
IntegerPolyhedron (IntegerRelation &&rel)
Construct a set from an IntegerRelation, but instead of creating a copy, use move constructor.
std::unique_ptr< IntegerPolyhedron > clone () const
IntegerPolyhedron intersect (const IntegerPolyhedron &other) const
Return the intersection of the two relations.
PresburgerSet subtract (const PresburgerSet &other) const
Return the set difference of this set and the given set, i.e., return this \ set.
Public Member Functions inherited from mlir::presburger::IntegerRelation
IntegerRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, const PresburgerSpace &space)
Constructs a relation reserving memory for the specified number of constraints and variables.
IntegerRelation (const PresburgerSpace &space)
Constructs a relation with the specified number of dimensions and symbols.
virtual ~IntegerRelation ()=default
std::unique_ptr< IntegerRelation > clone () const
const PresburgerSpace & getSpace () const
Returns a reference to the underlying space.
void setSpace (const PresburgerSpace &oSpace)
Set the space to oSpace, which should have the same number of ids as the current space.
void setSpaceExceptLocals (const PresburgerSpace &oSpace)
Set the space to oSpace, which should not have any local ids.
PresburgerSpace getSpaceWithoutLocals () const
Returns a copy of the space without locals.
void append (const IntegerRelation &other)
Appends constraints from other into this.
IntegerRelation intersect (IntegerRelation other) const
Return the intersection of the two relations.
bool isEqual (const IntegerRelation &other) const
Return whether this and other are equal.
bool isSubsetOf (const IntegerRelation &other) const
Return whether this is a subset of the given IntegerRelation.
MPInt atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t atEq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
MPInt & atEq (unsigned i, unsigned j)
MPInt atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t atIneq64 (unsigned i, unsigned j) const
The same, but casts to int64_t.
MPInt & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
unsigned getNumDomainVars () const
unsigned getNumRangeVars () const
unsigned getNumSymbolVars () const
unsigned getNumLocalVars () const
unsigned getNumDimVars () const
unsigned getNumDimAndSymbolVars () const
unsigned getNumVars () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< MPInt > getEquality (unsigned idx) const
ArrayRef< MPInt > getInequality (unsigned idx) const
SmallVector< int64_t, 8 > getEquality64 (unsigned idx) const
The same, but casts to int64_t.
SmallVector< int64_t, 8 > getInequality64 (unsigned idx) const
unsigned getNumVarKind (VarKind kind) const
Get the number of vars of the specified kind.
unsigned getVarKindOffset (VarKind kind) const
Return the index at which the specified kind of vars starts.
unsigned getVarKindEnd (VarKind kind) const
Return the index at Which the specified kind of vars ends.
unsigned getVarKindOverlap (VarKind kind, unsigned varStart, unsigned varLimit) const
Get the number of elements of the specified kind in the range [varStart, varLimit).
VarKind getVarKindAt (unsigned pos) const
Return the VarKind of the var at the specified position.
CountsSnapshot getCounts () const
void truncate (const CountsSnapshot &counts)
unsigned appendVar (VarKind kind, unsigned num=1)
Append num variables of the specified kind after the last variable of that kind.
void addInequality (ArrayRef< MPInt > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addInequality (ArrayRef< int64_t > inEq)
void addEquality (ArrayRef< MPInt > eq)
Adds an equality from the coefficients specified in eq.
void addEquality (ArrayRef< int64_t > eq)
virtual void eliminateRedundantLocalVar (unsigned posA, unsigned posB)
Eliminate the posB^th local variable, replacing every instance of it with the posA^th local variable.
void removeVar (VarKind kind, unsigned pos)
Removes variables of the specified kind with the specified pos (or within the specified range) from the system.
void removeVar (unsigned pos)
Removes the specified variable from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
MaybeOptimum< SmallVector< Fraction, 8 > > findRationalLexMin () const
Get the lexicographically minimum rational point satisfying the constraints.
MaybeOptimum< SmallVector< MPInt, 8 > > findIntegerLexMin () const
Same as above, but returns lexicographically minimal integer point.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< MPInt > values)
Sets the values.size() variables starting at pos to the specified values and removes them.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
virtual void clearAndCopyFrom (const IntegerRelation &other)
Replaces the contents of this IntegerRelation with other.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the variable at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all variables, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< MPInt, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
Optional< MPInt > computeVolume () const
Compute an overapproximation of the number of integer points in the relation.
bool containsPoint (ArrayRef< MPInt > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
bool containsPoint (ArrayRef< int64_t > point) const
Optional< SmallVector< MPInt, 8 > > containsPointNoLocal (ArrayRef< MPInt > point) const
Given the values of non-local vars, return a satisfying assignment to the local if one exists, or an empty optional otherwise.
Optional< SmallVector< MPInt, 8 > > containsPointNoLocal (ArrayRef< int64_t > point) const
DivisionRepr getLocalReprs (std::vector< MaybeLocalRepr > *repr=nullptr) const
Returns a DivisonRepr representing the division representation of local variables in the constraint system.
void addBound (BoundType type, unsigned pos, const MPInt &value)
Adds a constant bound for the specified variable.
void addBound (BoundType type, unsigned pos, int64_t value)
void addBound (BoundType type, ArrayRef< MPInt > expr, const MPInt &value)
Adds a constant bound for the specified expression.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
void addLocalFloorDiv (ArrayRef< MPInt > dividend, const MPInt &divisor)
Adds a new local variable as the floordiv of an affine function of other variables, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num variables starting at position pos.
void projectOut (unsigned pos)
LogicalResult constantFoldVar (unsigned pos)
Tries to fold the specified variable to a constant using a trivial equality detection; if successful, the constant is substituted for the variable everywhere in the constraint system and then removed from the system.
void constantFoldVarRange (unsigned pos, unsigned num)
This method calls constantFoldVar for the specified range of variables, num variables starting at position pos.
LogicalResult unionBoundingBox (const IntegerRelation &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
Optional< MPInt > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< MPInt > *lb=nullptr, MPInt *boundFloorDivisor=nullptr, SmallVectorImpl< MPInt > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified variable (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the variable.
Optional< int64_t > getConstantBoundOnDimSize64 (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
The same, but casts to int64_t.
Optional< MPInt > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th variable if there is one; None otherwise.
Optional< int64_t > getConstantBound64 (BoundType type, unsigned pos) const
The same, but casts to int64_t.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) variables in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of variables.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void removeDuplicateDivs ()
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind, unsigned pos)
Converts variables of kind srcKind in the range [varStart, varLimit) to variables of kind dstKind.
void convertVarKind (VarKind srcKind, unsigned varStart, unsigned varLimit, VarKind dstKind)
void convertToLocal (VarKind kind, unsigned varStart, unsigned varLimit)
unsigned mergeLocalVars (IntegerRelation &other)
Adds additional local vars to the sets such that they both have the union of the local vars in each set, without changing the set of points that lie in this and other.
bool hasOnlyDivLocals () const
Check whether all local ids have a division representation.
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
IntegerPolyhedron getDomainSet () const
Return a set corresponding to all points in the domain of the relation.
IntegerPolyhedron getRangeSet () const
Return a set corresponding to all points in the range of the relation.
void intersectDomain (const IntegerPolyhedron &poly)
Intersect the given poly with the domain in-place.
void intersectRange (const IntegerPolyhedron &poly)
Intersect the given poly with the range in-place.
void inverse ()
Invert the relation i.e., swap its domain and range.
void compose (const IntegerRelation &rel)
Let the relation this be R1, and the relation rel be R2.
void applyDomain (const IntegerRelation &rel)
Given a relation rel, apply the relation to the domain of this relation.
void applyRange (const IntegerRelation &rel)
Given a relation rel, apply the relation to the range of this relation.
PresburgerRelation computeReprWithOnlyDivLocals () const
Compute an equivalent representation of the same set, such that all local vars in all disjuncts have division representations.
SymbolicLexMin findSymbolicIntegerLexMin () const
Compute the symbolic integer lexmin of the relation.
PresburgerRelation subtract (const PresburgerRelation &set) const
Return the set difference of this set and the given set, i.e., return this \ set.
void print (raw_ostream &os) const
void dump () const
Protected Attributes
unsigned numDomainDims
unsigned numRangeDims
Protected Attributes inherited from mlir::FlatAffineValueConstraints
SmallVector< Optional< Value >, 8 > values
Values corresponding to the (column) non-local variables of this constraint system appearing in the order the variables correspond to columns.
Protected Attributes inherited from mlir::presburger::IntegerRelation
PresburgerSpace space
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Additional Inherited Members
Public Types inherited from mlir::presburger::IntegerRelation
enum class Kind { FlatAffineConstraints , FlatAffineValueConstraints , IntegerRelation , IntegerPolyhedron }
All derived classes of IntegerRelation.
enum BoundType { EQ , LB , UB }
The type of bound: equal, lower bound or upper bound.
Static Public Member Functions inherited from mlir::FlatAffineValueConstraints
static FlatAffineValueConstraints getHyperrectangular (ValueRange ivs, ValueRange lbs, ValueRange ubs)
static bool classof (const IntegerRelation *cst)
Static Public Member Functions inherited from mlir::presburger::IntegerPolyhedron
static IntegerPolyhedron getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerRelation *cst)
Static Public Member Functions inherited from mlir::presburger::IntegerRelation
static IntegerRelation getUniverse (const PresburgerSpace &space)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerRelation *cst)
Protected Types inherited from mlir::FlatAffineValueConstraints
using VarKind = presburger::VarKind
Protected Member Functions inherited from mlir::FlatAffineValueConstraints
bool hasConsistentState () const override
Returns false if the fields corresponding to various variable counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
LogicalResult flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
Given an affine map that is aligned with this constraint system:
void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr) override
Eliminates the variable at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that variable.
void printSpace (raw_ostream &os) const override
Prints the number of constraints, dimensions, symbols and locals in the FlatAffineConstraints.
Protected Member Functions inherited from mlir::presburger::IntegerRelation
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< MPInt > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound64 (unsigned pos)
The same, but casts to int64_t.
LogicalResult gaussianEliminateVar (unsigned position)
Eliminates a single variable at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateVars (unsigned posStart, unsigned posLimit)
Eliminates variables from equality and inequality constraints in column range [posStart, posLimit).
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned *rowIdx) const
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
void removeVarRange (unsigned varStart, unsigned varLimit)
Removes variables in the column range [varStart, varLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
void truncateVarKind (VarKind kind, unsigned num)
Truncate the vars of the specified kind to the specified number by dropping some vars at the end.
void truncateVarKind (VarKind kind, const CountsSnapshot &counts)
Truncate the vars to the number in the space of the specified CountsSnapshot.
Static Protected Attributes inherited from mlir::presburger::IntegerRelation
constexpr static unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
A FlatAffineRelation represents a set of ordered pairs (domain -> range) where "domain" and "range" are tuples of variables.
The relation is represented as a FlatAffineValueConstraints with separation of dimension variables into domain and range. The variables are stored as: [domainVars, rangeVars, symbolVars, localVars, constant].
Definition at line 517 of file AffineStructures.h.
Constructor & Destructor Documentation
FlatAffineRelation() [1/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDomainDims, unsigned numRangeDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs = {}) inline
Definition at line 519 of file AffineStructures.h.
FlatAffineRelation() [2/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numDomainDims = 0, unsigned numRangeDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline
Definition at line 529 of file AffineStructures.h.
FlatAffineRelation() [3/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, FlatAffineValueConstraints & fac) inline
Definition at line 535 of file AffineStructures.h.
FlatAffineRelation() [4/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, IntegerPolyhedron & fac) inline
Definition at line 540 of file AffineStructures.h.
Member Function Documentation
appendDomainVar()
void FlatAffineRelation::appendDomainVar (unsigned num = 1)
Append num variables of the specified kind after the last variable of that kind.
The coefficient columns corresponding to the added variables are initialized to zero.
Definition at line 1717 of file AffineStructures.cpp.
References getNumDomainDims(), mlir::FlatAffineValueConstraints::insertDimVar(), and numDomainDims.
appendRangeVar()
void FlatAffineRelation::appendRangeVar (unsigned num = 1)
Definition at line 1722 of file AffineStructures.cpp.
References mlir::presburger::IntegerRelation::getNumDimVars(), mlir::FlatAffineValueConstraints::insertDimVar(), and numRangeDims.
Referenced by compose(), mlir::MemRefAccess::getAccessRelation(), and inverse().
compose()
void FlatAffineRelation::compose (const FlatAffineRelation & other)
Given affine relation other: (domainOther -> rangeOther), this operation takes the composition of other on this: (domainThis -> rangeThis).
The resulting relation represents tuples of the form: domainOther -> rangeThis.
Definition at line 1631 of file AffineStructures.cpp.
References mlir::presburger::IntegerRelation::append(), appendRangeVar(), mlir::presburger::IntegerRelation::convertToLocal(), mlir::FlatAffineValueConstraints::getMaybeValues(), getNumDomainDims(), getNumRangeDims(), insertDomainVar(), mlir::presburger::IntegerRelation::mergeLocalVars(), mlir::FlatAffineValueConstraints::mergeSymbolVars(), mlir::presburger::IntegerRelation::removeRedundantLocalVars(), mlir::FlatAffineValueConstraints::setValue(), value, and mlir::FlatAffineValueConstraints::values.
Referenced by mlir::checkMemrefAccessDependence().
getDomainSet()
FlatAffineValueConstraints FlatAffineRelation::getDomainSet () const
Returns a set corresponding to the domain/range of the affine relation.
Definition at line 1616 of file AffineStructures.cpp.
References mlir::presburger::IntegerRelation::convertToLocal(), getNumDomainDims(), and getNumRangeDims().
Referenced by mlir::checkMemrefAccessDependence().
getNumDomainDims()
unsigned mlir::FlatAffineRelation::getNumDomainDims () const inline
Returns the number of variables corresponding to domain/range of relation.
Definition at line 551 of file AffineStructures.h.
References numDomainDims.
Referenced by appendDomainVar(), compose(), mlir::MemRefAccess::getAccessRelation(), getDomainSet(), getRangeSet(), mlir::getRelationFromMap(), insertDomainVar(), insertRangeVar(), and inverse().
getNumRangeDims()
unsigned mlir::FlatAffineRelation::getNumRangeDims () const inline
Definition at line 552 of file AffineStructures.h.
References numRangeDims.
Referenced by compose(), mlir::MemRefAccess::getAccessRelation(), getDomainSet(), mlir::getRelationFromMap(), insertRangeVar(), and inverse().
getRangeSet()
FlatAffineValueConstraints FlatAffineRelation::getRangeSet () const
Definition at line 1624 of file AffineStructures.cpp.
References mlir::presburger::IntegerRelation::convertToLocal(), and getNumDomainDims().
insertDomainVar()
void FlatAffineRelation::insertDomainVar (unsigned pos, unsigned num = 1)
Insert num variables of the specified kind after the pos variable of that kind.
The coefficient columns corresponding to the added variables are initialized to zero.
Definition at line 1703 of file AffineStructures.cpp.
References getNumDomainDims(), mlir::FlatAffineValueConstraints::insertDimVar(), and numDomainDims.
Referenced by compose(), and mlir::MemRefAccess::getAccessRelation().
insertRangeVar()
void FlatAffineRelation::insertRangeVar (unsigned pos, unsigned num = 1)
Definition at line 1710 of file AffineStructures.cpp.
References getNumDomainDims(), getNumRangeDims(), mlir::FlatAffineValueConstraints::insertDimVar(), and numRangeDims.
inverse()
void FlatAffineRelation::inverse ()
Swap domain and range of the relation.
(domain -> range) is converted to (range -> domain).
Definition at line 1688 of file AffineStructures.cpp.
References appendRangeVar(), getNumDomainDims(), getNumRangeDims(), numDomainDims, numRangeDims, removeVarRange(), and mlir::FlatAffineValueConstraints::swapVar().
Referenced by mlir::checkMemrefAccessDependence().
removeVarRange()
void FlatAffineRelation::removeVarRange (VarKind kind, unsigned varStart, unsigned varLimit) override virtual
Removes variables in the column range [varStart, varLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Reimplemented from mlir::FlatAffineValueConstraints.
Definition at line 1727 of file AffineStructures.cpp.
Referenced by inverse().
Member Data Documentation
numDomainDims
unsigned mlir::FlatAffineRelation::numDomainDims protected
Definition at line 585 of file AffineStructures.h.
Referenced by appendDomainVar(), getNumDomainDims(), insertDomainVar(), and inverse().
numRangeDims
unsigned mlir::FlatAffineRelation::numRangeDims protected
Definition at line 588 of file AffineStructures.h.
Referenced by appendRangeVar(), getNumRangeDims(), insertRangeVar(), and inverse().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Affine/Analysis/AffineStructures.h
lib/Dialect/Affine/Analysis/AffineStructures.cpp