MLIR: mlir::presburger::MultiAffineFunction Class Reference
mlir::presburger::MultiAffineFunction Class Reference
This class represents a multi-affine function with the domain as Z^d, where d is the number of domain variables of the function.
#include "mlir/Analysis/Presburger/PWMAFunction.h"
Public Member Functions
MultiAffineFunction (const PresburgerSpace &space, const Matrix &output)
MultiAffineFunction (const PresburgerSpace &space, const Matrix &output, const DivisionRepr &divs)
unsigned getNumDomainVars () const
unsigned getNumSymbolVars () const
unsigned getNumOutputs () const
unsigned getNumDivs () const
const PresburgerSpace & getSpace () const
Get the space of this function.
PresburgerSpace getDomainSpace () const
Get the domain/output space of the function.
PresburgerSpace getOutputSpace () const
const Matrix & getOutputMatrix () const
Get a matrix with each row representing row^th output expression.
ArrayRef< MPInt > getOutputExpr (unsigned i) const
Get the i^th output expression.
void removeOutputs (unsigned start, unsigned end)
void mergeDivs (MultiAffineFunction &other)
Given a MAF other, merges division variables such that both functions have the union of the division vars that exist in the functions.
SmallVector< MPInt, 8 > valueAt (ArrayRef< MPInt > point) const
SmallVector< MPInt, 8 > valueAt (ArrayRef< int64_t > point) const
bool isEqual (const MultiAffineFunction &other) const
Return whether the this and other are equal when the domain is restricted to domain.
bool isEqual (const MultiAffineFunction &other, const IntegerPolyhedron &domain) const
bool isEqual (const MultiAffineFunction &other, const PresburgerSet &domain) const
void subtract (const MultiAffineFunction &other)
IntegerRelation getAsRelation () const
Get this function as a relation.
void print (raw_ostream &os) const
void dump () const
Detailed Description
This class represents a multi-affine function with the domain as Z^d, where d is the number of domain variables of the function.
For example:
(x, y) -> (x + 2, 2*x - 3y + 5, 2*x + y).
The output expressions are represented as a matrix with one row for every output, one column for each var including division variables, and an extra column at the end for the constant term.
Checking equality of two such functions is supported, as well as finding the value of the function at a specified point.
Definition at line 36 of file PWMAFunction.h.
Constructor & Destructor Documentation
MultiAffineFunction() [1/2]
mlir::presburger::MultiAffineFunction::MultiAffineFunction (const PresburgerSpace & space, const Matrix & output) inline
Definition at line 38 of file PWMAFunction.h.
MultiAffineFunction() [2/2]
mlir::presburger::MultiAffineFunction::MultiAffineFunction (const PresburgerSpace & space, const Matrix & output, const DivisionRepr & divs) inline
Definition at line 44 of file PWMAFunction.h.
Member Function Documentation
dump()
void mlir::presburger::MultiAffineFunction::dump () const
getAsRelation()
IntegerRelation MultiAffineFunction::getAsRelation () const
Get this function as a relation.
Definition at line 379 of file PWMAFunction.cpp.
References addDivisionConstraints(), mlir::presburger::IntegerRelation::addEquality(), copy(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::PresburgerSpace::getNumDomainVars(), getNumDomainVars(), mlir::presburger::PresburgerSpace::getNumLocalVars(), getNumOutputs(), mlir::presburger::PresburgerSpace::getNumSymbolVars(), getOutputExpr(), mlir::presburger::PresburgerSpace::getRelationSpace(), mlir::presburger::IntegerRelation::getVarKindEnd(), mlir::presburger::IntegerRelation::getVarKindOffset(), mlir::presburger::IntegerRelation::insertVar(), and mlir::presburger::Range.
Referenced by isEqual().
getDomainSpace()
PresburgerSpace mlir::presburger::MultiAffineFunction::getDomainSpace () const inline
Get the domain/output space of the function.
The returned space is a set space.
Definition at line 59 of file PWMAFunction.h.
References mlir::presburger::PresburgerSpace::getDomainSpace().
Referenced by mlir::presburger::PWMAFunction::Piece::isConsistent().
getNumDivs()
unsigned mlir::presburger::MultiAffineFunction::getNumDivs () const inline
Definition at line 53 of file PWMAFunction.h.
References mlir::presburger::PresburgerSpace::getNumLocalVars().
Referenced by mergeDivs().
getNumDomainVars()
unsigned mlir::presburger::MultiAffineFunction::getNumDomainVars () const inline
Definition at line 50 of file PWMAFunction.h.
References mlir::presburger::PresburgerSpace::getNumDomainVars().
Referenced by getAsRelation(), and valueAt().
getNumOutputs()
unsigned mlir::presburger::MultiAffineFunction::getNumOutputs () const inline
Definition at line 52 of file PWMAFunction.h.
References mlir::presburger::PresburgerSpace::getNumRangeVars().
Referenced by getAsRelation(), removeOutputs(), subtract(), tiebreakLex(), and valueAt().
getNumSymbolVars()
unsigned mlir::presburger::MultiAffineFunction::getNumSymbolVars () const inline
Definition at line 51 of file PWMAFunction.h.
References mlir::presburger::PresburgerSpace::getNumSymbolVars().
Referenced by valueAt().
getOutputExpr()
ArrayRef<MPInt> mlir::presburger::MultiAffineFunction::getOutputExpr (unsigned i) const inline
Get the i^th output expression.
Definition at line 65 of file PWMAFunction.h.
References mlir::presburger::Matrix::getRow().
Referenced by getAsRelation(), subtract(), and tiebreakLex().
getOutputMatrix()
const Matrix& mlir::presburger::MultiAffineFunction::getOutputMatrix () const inline
Get a matrix with each row representing row^th output expression.
Definition at line 63 of file PWMAFunction.h.
getOutputSpace()
PresburgerSpace mlir::presburger::MultiAffineFunction::getOutputSpace () const inline
Definition at line 60 of file PWMAFunction.h.
References mlir::presburger::PresburgerSpace::getRangeSpace().
getSpace()
const PresburgerSpace& mlir::presburger::MultiAffineFunction::getSpace () const inline
Get the space of this function.
Definition at line 56 of file PWMAFunction.h.
Referenced by tiebreakLex().
isEqual() [1/3]
bool MultiAffineFunction::isEqual (const MultiAffineFunction & other) const
Return whether the this and other are equal when the domain is restricted to domain.
This is the case if they lie in the same space, and their outputs are equal for every point in domain.
Definition at line 82 of file PWMAFunction.cpp.
References getAsRelation(), mlir::presburger::PresburgerSpace::isCompatible(), and mlir::presburger::IntegerRelation::isEqual().
isEqual() [2/3]
bool MultiAffineFunction::isEqual (const MultiAffineFunction & other, const IntegerPolyhedron & domain) const
Definition at line 88 of file PWMAFunction.cpp.
References getAsRelation(), mlir::presburger::IntegerRelation::intersectDomain(), mlir::presburger::PresburgerSpace::isCompatible(), and mlir::presburger::IntegerRelation::isEqual().
isEqual() [3/3]
bool MultiAffineFunction::isEqual (const MultiAffineFunction & other, const PresburgerSet & domain) const
Definition at line 101 of file PWMAFunction.cpp.
References mlir::presburger::PresburgerRelation::getAllDisjuncts(), and mlir::presburger::PresburgerSpace::isCompatible().
mergeDivs()
void MultiAffineFunction::mergeDivs (MultiAffineFunction & other)
Given a MAF other, merges division variables such that both functions have the union of the division vars that exist in the functions.
Definition at line 121 of file PWMAFunction.cpp.
References mlir::presburger::Matrix::addToColumn(), copy(), mlir::presburger::DivisionRepr::getDenom(), mlir::presburger::DivisionRepr::getDividend(), mlir::presburger::DivisionRepr::getDivOffset(), getNumDivs(), mlir::presburger::DivisionRepr::getNumDivs(), mlir::presburger::DivisionRepr::getNumVars(), mlir::presburger::Matrix::insertColumns(), mlir::presburger::DivisionRepr::insertDiv(), mlir::presburger::PresburgerSpace::insertVar(), mlir::presburger::PresburgerSpace::isCompatible(), mlir::presburger::Local, mlir::presburger::Matrix::removeColumn(), mlir::presburger::DivisionRepr::removeDuplicateDivs(), mlir::presburger::PresburgerSpace::removeVarRange(), and mlir::presburger::DivisionRepr::setDiv().
Referenced by subtract().
print()
void MultiAffineFunction::print (raw_ostream & os) const
Definition at line 50 of file PWMAFunction.cpp.
References mlir::presburger::PresburgerSpace::print(), mlir::presburger::Matrix::print(), and mlir::presburger::DivisionRepr::print().
removeOutputs()
void MultiAffineFunction::removeOutputs (unsigned start, unsigned end)
Definition at line 111 of file PWMAFunction.cpp.
References getNumOutputs(), mlir::presburger::Range, mlir::presburger::Matrix::removeRows(), and mlir::presburger::PresburgerSpace::removeVarRange().
subtract()
void MultiAffineFunction::subtract (const MultiAffineFunction & other)
Definition at line 346 of file PWMAFunction.cpp.
References mlir::presburger::Matrix::addToRow(), getNumOutputs(), getOutputExpr(), mlir::presburger::PresburgerSpace::isCompatible(), and mergeDivs().
valueAt() [1/2]
SmallVector<MPInt, 8> mlir::presburger::MultiAffineFunction::valueAt (ArrayRef< int64_t > point) const inline
Definition at line 76 of file PWMAFunction.h.
References mlir::presburger::getMPIntVec(), and valueAt().
valueAt() [2/2]
SmallVector< MPInt, 8 > MultiAffineFunction::valueAt (ArrayRef< MPInt > point) const
Definition at line 59 of file PWMAFunction.cpp.
References mlir::presburger::DivisionRepr::divValuesAt(), getNumDomainVars(), getNumOutputs(), getNumSymbolVars(), and mlir::presburger::Matrix::postMultiplyWithColumn().
Referenced by valueAt().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/PWMAFunction.h
lib/Analysis/Presburger/PWMAFunction.cpp