MLIR: mlir::sparse_tensor::detail::PermutationRef Class Reference
mlir::sparse_tensor::detail::PermutationRef Class Reference final
A non-owning class for capturing the knowledge that isPermutation is true, to avoid needing to assert it repeatedly.
#include "mlir/ExecutionEngine/SparseTensor/PermutationRef.h"
Public Member Functions
PermutationRef (uint64_t size, const uint64_t *perm)
Asserts isPermutation and returns the witness to that being true.
uint64_t size () const
const uint64_t * data () const
const uint64_t & operator[] (uint64_t i) const
template<typename T >
std::vector< T > pushforward (const std::vector< T > &values) const
Constructs a pushforward array of values.
template<typename T >
std::vector< T > pushforward (uint64_t size, const T *values) const
template<typename T >
void pushforward (uint64_t size, const T *values, T *out) const
std::vector< uint64_t > inverse () const
Constructs the inverse permutation.
template<typename T >
std::vector< T > permute (const std::vector< T > &values) const
Constructs a permuted array of values.
template<typename T >
std::vector< T > permute (uint64_t size, const T *values) const
template<typename T >
void permute (uint64_t size, const T *values, T *out) const
Detailed Description
A non-owning class for capturing the knowledge that isPermutation is true, to avoid needing to assert it repeatedly.
Definition at line 54 of file PermutationRef.h.
Constructor & Destructor Documentation
PermutationRef()
mlir::sparse_tensor::detail::PermutationRef::PermutationRef (uint64_t size, const uint64_t * perm) inline explicit
Asserts isPermutation and returns the witness to that being true.
Definition at line 61 of file PermutationRef.h.
References mlir::sparse_tensor::detail::assertIsPermutation().
Member Function Documentation
data()
const uint64_t* mlir::sparse_tensor::detail::PermutationRef::data () const inline
Definition at line 68 of file PermutationRef.h.
inverse()
std::vector< uint64_t > mlir::sparse_tensor::detail::PermutationRef::inverse () const
Constructs the inverse permutation.
This is equivalent to calling pushforward with std::iota for the values.
Definition at line 33 of file PermutationRef.cpp.
operator[]()
const uint64_t& mlir::sparse_tensor::detail::PermutationRef::operator[] (uint64_t i) const inline
Definition at line 70 of file PermutationRef.h.
permute() [1/3]
template<typename T > std::vector<T> mlir::sparse_tensor::detail::PermutationRef::permute (const std::vector< T > & values) const inline
Constructs a permuted array of values.
This method is the inverse of pushforward in the sense that for all p and xs we have:
p.permute(p.pushforward(xs)) == xs
p.pushforward(p.permute(xs)) == xs
Definition at line 114 of file PermutationRef.h.
References permute().
permute() [2/3]
template<typename T > std::vector<T> mlir::sparse_tensor::detail::PermutationRef::permute (uint64_t size, const T * values) const inline
Definition at line 119 of file PermutationRef.h.
References permute().
permute() [3/3]
template<typename T > void mlir::sparse_tensor::detail::PermutationRef::permute (uint64_t size, const T * values, T * out) const inline
Definition at line 126 of file PermutationRef.h.
pushforward() [1/3]
template<typename T > std::vector<T> mlir::sparse_tensor::detail::PermutationRef::pushforward (const std::vector< T > & values) const inline
Constructs a pushforward array of values.
This method is the inverse of permute in the sense that for all p and xs we have:
p.permute(p.pushforward(xs)) == xs
p.pushforward(p.permute(xs)) == xs
Definition at line 80 of file PermutationRef.h.
Referenced by mlir::sparse_tensor::openSparseTensor().
pushforward() [2/3]
template<typename T > std::vector<T> mlir::sparse_tensor::detail::PermutationRef::pushforward (uint64_t size, const T * values) const inline
Definition at line 85 of file PermutationRef.h.
pushforward() [3/3]
template<typename T > void mlir::sparse_tensor::detail::PermutationRef::pushforward (uint64_t size, const T * values, T * out) const inline
Definition at line 94 of file PermutationRef.h.
size()
uint64_t mlir::sparse_tensor::detail::PermutationRef::size () const inline
Definition at line 66 of file PermutationRef.h.
The documentation for this class was generated from the following files:
include/mlir/ExecutionEngine/SparseTensor/PermutationRef.h
lib/ExecutionEngine/SparseTensor/PermutationRef.cpp