MLIR: mlir::sparse_tensor::SparseTensorCOO< V > Class Template Reference
mlir::sparse_tensor::SparseTensorCOO< V > Class Template Reference final
A memory-resident sparse tensor in coordinate-scheme representation (a collection of Elements).
#include "mlir/ExecutionEngine/SparseTensor/COO.h"
Public Types
using value_type = const Element< V >
using reference = value_type &
using const_reference = reference
using vector_type = std::vector< Element< V > >
using iterator = typename vector_type::const_iterator
using const_iterator = iterator
using difference_type = typename vector_type::difference_type
using size_type = typename vector_type::size_type
Public Member Functions
SparseTensorCOO (const std::vector< uint64_t > &dimSizes, uint64_t capacity=0)
Constructs a new coordinate-scheme sparse tensor with the given sizes and initial storage capacity.
SparseTensorCOO (uint64_t dimRank, const uint64_t *dimSizes, uint64_t capacity=0)
Constructs a new coordinate-scheme sparse tensor with the given sizes and initial storage capacity.
uint64_t getRank () const
Gets the rank of the tensor.
const std::vector< uint64_t > & getDimSizes () const
Gets the dimension-sizes array.
const std::vector< Element< V > > & getElements () const
Gets the elements array.
ElementLT< V > getElementLT () const
Returns the operator< closure object for the COO's element type.
void add (const std::vector< uint64_t > &ind, V val)
Adds an element to the tensor.
const_iterator begin () const
const_iterator end () const
void sort ()
Sorts elements lexicographically by index.
Detailed Description
template<typename V>
class mlir::sparse_tensor::SparseTensorCOO< V >
A memory-resident sparse tensor in coordinate-scheme representation (a collection of Elements).
This data structure is used as an intermediate representation; e.g., for reading sparse tensors from external formats into memory, or for certain conversions between different SparseTensorStorage formats.
This class provides all the typedefs required by the "Container" concept (https://en.cppreference.com/w/cpp/named_req/Container); however, beware that it cannot fully implement that concept since it cannot have a default ctor (because the dimSizes field is const). Thus these typedefs are provided for familiarity reasons, rather than as a proper implementation of the concept.
Definition at line 91 of file COO.h.
Member Typedef Documentation
const_iterator
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::const_iterator = iterator
Definition at line 101 of file COO.h.
const_reference
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::const_reference = reference
Definition at line 95 of file COO.h.
difference_type
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::difference_type = typename vector_type::difference_type
Definition at line 102 of file COO.h.
iterator
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::iterator = typename vector_type::const_iterator
Definition at line 100 of file COO.h.
reference
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::reference = value_type &
Definition at line 94 of file COO.h.
size_type
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::size_type = typename vector_type::size_type
Definition at line 103 of file COO.h.
value_type
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::value_type = const Element<V>
Definition at line 93 of file COO.h.
vector_type
template<typename V > using mlir::sparse_tensor::SparseTensorCOO< V >::vector_type = std::vector<Element<V> >
Definition at line 99 of file COO.h.
Constructor & Destructor Documentation
SparseTensorCOO() [1/2]
template<typename V > mlir::sparse_tensor::SparseTensorCOO< V >::SparseTensorCOO (const std::vector< uint64_t > & dimSizes, uint64_t capacity = 0) inline explicit
Constructs a new coordinate-scheme sparse tensor with the given sizes and initial storage capacity.
Asserts:
dimSizes has nonzero size.
the elements of dimSizes are nonzero.
Definition at line 111 of file COO.h.
SparseTensorCOO() [2/2]
template<typename V > mlir::sparse_tensor::SparseTensorCOO< V >::SparseTensorCOO (uint64_t dimRank, const uint64_t * dimSizes, uint64_t capacity = 0) inline explicit
Constructs a new coordinate-scheme sparse tensor with the given sizes and initial storage capacity.
Precondition: dimSizes must be valid for dimRank.
Asserts:
dimRank is nonzero.
the elements of dimSizes are nonzero.
Definition at line 127 of file COO.h.
Member Function Documentation
add()
template<typename V > void mlir::sparse_tensor::SparseTensorCOO< V >::add (const std::vector< uint64_t > & ind, V val) inline
Adds an element to the tensor.
This method does not check whether ind is already associated with a value, it adds it regardless. Resolving such conflicts is left up to clients of the iterator interface.
This method invalidates all iterators.
Asserts:
the ind is valid for rank
the elements of ind are valid for dimSizes.
Definition at line 161 of file COO.h.
References mlir::sparse_tensor::SparseTensorCOO< V >::getElementLT(), and mlir::sparse_tensor::SparseTensorCOO< V >::getRank().
begin()
template<typename V > const_iterator mlir::sparse_tensor::SparseTensorCOO< V >::begin () const inline
Definition at line 188 of file COO.h.
end()
template<typename V > const_iterator mlir::sparse_tensor::SparseTensorCOO< V >::end () const inline
Definition at line 189 of file COO.h.
getDimSizes()
template<typename V > const std::vector<uint64_t>& mlir::sparse_tensor::SparseTensorCOO< V >::getDimSizes () const inline
Gets the dimension-sizes array.
Definition at line 143 of file COO.h.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::newFromCOO(), mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), and mlir::sparse_tensor::writeExtFROSTT().
getElementLT()
template<typename V > ElementLT<V> mlir::sparse_tensor::SparseTensorCOO< V >::getElementLT () const inline
Returns the operator< closure object for the COO's element type.
Definition at line 149 of file COO.h.
References mlir::sparse_tensor::SparseTensorCOO< V >::getRank().
Referenced by mlir::sparse_tensor::SparseTensorCOO< V >::add(), and mlir::sparse_tensor::SparseTensorCOO< V >::sort().
getElements()
template<typename V > const std::vector<Element<V> >& mlir::sparse_tensor::SparseTensorCOO< V >::getElements () const inline
Gets the elements array.
Definition at line 146 of file COO.h.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage(), and mlir::sparse_tensor::writeExtFROSTT().
getRank()
template<typename V > uint64_t mlir::sparse_tensor::SparseTensorCOO< V >::getRank () const inline
Gets the rank of the tensor.
Definition at line 140 of file COO.h.
Referenced by mlir::sparse_tensor::SparseTensorCOO< V >::add(), mlir::sparse_tensor::SparseTensorCOO< V >::getElementLT(), and mlir::sparse_tensor::writeExtFROSTT().
sort()
template<typename V > void mlir::sparse_tensor::SparseTensorCOO< V >::sort () inline
Sorts elements lexicographically by index.
If an index is mapped to multiple values, then the relative order of those values is unspecified.
This method invalidates all iterators.
Definition at line 195 of file COO.h.
References mlir::sparse_tensor::SparseTensorCOO< V >::getElementLT().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/SparseTensor/COO.h