MLIR: mlir::dataflow::AbstractSparseDataFlowAnalysis Class Reference
mlir::dataflow::AbstractSparseDataFlowAnalysis Class Reference abstract
Base class for sparse (forward) data-flow analyses.
#include "mlir/Analysis/DataFlow/SparseAnalysis.h"
Public Member Functions
LogicalResult initialize (Operation *top) override
Initialize the analysis by visiting every owner of an SSA value: all operations and blocks.
LogicalResult visit (ProgramPoint point) override
Visit a program point.
Public Member Functions inherited from mlir::DataFlowAnalysis
virtual ~DataFlowAnalysis ()
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
Protected Member Functions
AbstractSparseDataFlowAnalysis (DataFlowSolver &solver)
virtual void visitOperationImpl (Operation *op, ArrayRef< const AbstractSparseLattice * > operandLattices, ArrayRef< AbstractSparseLattice * > resultLattices)=0
The operation transfer function.
virtual void visitNonControlFlowArgumentsImpl (Operation *op, const RegionSuccessor &successor, ArrayRef< AbstractSparseLattice * > argLattices, unsigned firstIndex)=0
Given an operation with region control-flow, the lattices of the operands, and a region successor, compute the lattice values for block arguments that are not accounted for by the branching control flow (ex.
virtual AbstractSparseLattice * getLatticeElement (Value value)=0
Get the lattice element of a value.
const AbstractSparseLattice * getLatticeElementFor (ProgramPoint point, Value value)
Get a read-only lattice element for a value and add it as a dependency to a program point.
virtual void setToEntryState (AbstractSparseLattice *lattice)=0
Set the given lattice element(s) at control flow entry point(s).
void setAllToEntryStates (ArrayRef< AbstractSparseLattice * > lattices)
void join (AbstractSparseLattice *lhs, const AbstractSparseLattice &rhs)
Join the lattice element and propagate and update if it changed.
Protected Member Functions inherited from mlir::DataFlowAnalysis
void addDependency (AnalysisState *state, ProgramPoint point)
Create a dependency between the given analysis state and program point on this analysis.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to a state if it changed.
template<typename PointT >
void registerPointKind ()
Register a custom program point class.
template<typename PointT , typename... Args>
PointT * getProgramPoint (Args &&...args)
Get or create a custom program point.
template<typename StateT , typename PointT >
StateT * getOrCreate (PointT point)
Get the analysis state assiocated with the program point.
template<typename StateT , typename PointT >
const StateT * getOrCreateFor (ProgramPoint dependent, PointT point)
Get a read-only analysis state for the given point and create a dependency on dependent.
Detailed Description
Base class for sparse (forward) data-flow analyses.
A sparse analysis implements a transfer function on operations from the lattices of the operands to the lattices of the results. This analysis will propagate lattices across control-flow edges and the callgraph using liveness information.
Definition at line 134 of file SparseAnalysis.h.
Constructor & Destructor Documentation
AbstractSparseDataFlowAnalysis()
AbstractSparseDataFlowAnalysis::AbstractSparseDataFlowAnalysis (DataFlowSolver & solver) explicit protected
Definition at line 31 of file SparseAnalysis.cpp.
Member Function Documentation
getLatticeElement()
virtual AbstractSparseLattice* mlir::dataflow::AbstractSparseDataFlowAnalysis::getLatticeElement (Value value) protected pure virtual
Get the lattice element of a value.
Implemented in mlir::dataflow::SparseDataFlowAnalysis< StateT >, mlir::dataflow::SparseDataFlowAnalysis< IntegerValueRangeLattice >, and mlir::dataflow::SparseDataFlowAnalysis< Lattice< ConstantValue > >.
Referenced by getLatticeElementFor(), and initialize().
getLatticeElementFor()
const AbstractSparseLattice * AbstractSparseDataFlowAnalysis::getLatticeElementFor (ProgramPoint point, Value value) protected
Get a read-only lattice element for a value and add it as a dependency to a program point.
Definition at line 266 of file SparseAnalysis.cpp.
References mlir::DataFlowAnalysis::addDependency(), getLatticeElement(), and value.
Referenced by mlir::dataflow::SparseDataFlowAnalysis< StateT >::getLatticeElementFor().
initialize()
LogicalResult AbstractSparseDataFlowAnalysis::initialize (Operation * top) override virtual
Initialize the analysis by visiting every owner of an SSA value: all operations and blocks.
Implements mlir::DataFlowAnalysis.
Definition at line 37 of file SparseAnalysis.cpp.
References getLatticeElement(), mlir::Operation::getRegions(), and setAllToEntryStates().
join()
void AbstractSparseDataFlowAnalysis::join (AbstractSparseLattice * lhs, const AbstractSparseLattice & rhs) protected
Join the lattice element and propagate and update if it changed.
Definition at line 279 of file SparseAnalysis.cpp.
Referenced by mlir::dataflow::SparseConstantPropagation::visitOperation().
setAllToEntryStates()
void AbstractSparseDataFlowAnalysis::setAllToEntryStates (ArrayRef< AbstractSparseLattice * > lattices) protected
Definition at line 273 of file SparseAnalysis.cpp.
References setToEntryState().
Referenced by initialize(), and mlir::dataflow::SparseDataFlowAnalysis< StateT >::setAllToEntryStates().
setToEntryState()
virtual void mlir::dataflow::AbstractSparseDataFlowAnalysis::setToEntryState (AbstractSparseLattice * lattice) protected pure virtual
Set the given lattice element(s) at control flow entry point(s).
Referenced by setAllToEntryStates().
visit()
LogicalResult AbstractSparseDataFlowAnalysis::visit (ProgramPoint point) override virtual
Visit a program point.
If this is a block and all control-flow predecessors or callsites are known, then the arguments lattices are propagated from them. If this is a call operation or an operation with region control-flow, then its result lattices are set accordingly. Otherwise, the operation transfer function is invoked.
Implements mlir::DataFlowAnalysis.
Definition at line 68 of file SparseAnalysis.cpp.
References mlir::failure(), and mlir::success().
visitNonControlFlowArgumentsImpl()
virtual void mlir::dataflow::AbstractSparseDataFlowAnalysis::visitNonControlFlowArgumentsImpl (Operation * op, const RegionSuccessor & successor, ArrayRef< AbstractSparseLattice * > argLattices, unsigned firstIndex) protected pure virtual
Given an operation with region control-flow, the lattices of the operands, and a region successor, compute the lattice values for block arguments that are not accounted for by the branching control flow (ex.
the bounds of loops).
visitOperationImpl()
virtual void mlir::dataflow::AbstractSparseDataFlowAnalysis::visitOperationImpl (Operation * op, ArrayRef< const AbstractSparseLattice * > operandLattices, ArrayRef< AbstractSparseLattice * > resultLattices) protected pure virtual
The operation transfer function.
Given the operand lattices, this function is expected to set the result lattices.
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/SparseAnalysis.h
lib/Analysis/DataFlow/SparseAnalysis.cpp