MLIR: mlir::arith::WideIntEmulationConverter Class Reference
mlir::arith::WideIntEmulationConverter Class Reference
Converts integer types that are too wide for the target by splitting them in two halves and thus turning into supported ones, i.e., i2*N --> iN, where N is the widest integer bitwidth supported by the target.
#include "mlir/Dialect/Arith/Transforms/WideIntEmulationConverter.h"
Public Member Functions
WideIntEmulationConverter (unsigned widestIntSupportedByTarget)
unsigned getMaxTargetIntBitWidth () const
Public Member Functions inherited from mlir::TypeConverter
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<0>>
void addConversion (FnT &&callback)
Register a conversion function.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addArgumentMaterialization (FnT &&callback)
Register a materialization function, which must be convertible to the following form: Optional<Value>(OpBuilder &, T, ValueRange, Location), where T is any subclass of Type.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addSourceMaterialization (FnT &&callback)
This method registers a materialization that will be called when converting a legal type to an illegal source type.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addTargetMaterialization (FnT &&callback)
This method registers a materialization that will be called when converting type from an illegal, or source, type to a legal type.
LogicalResult convertType (Type t, SmallVectorImpl< Type > &results)
Convert the given type.
Type convertType (Type t)
This hook simplifies defining 1-1 type conversions.
LogicalResult convertTypes (TypeRange types, SmallVectorImpl< Type > &results)
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
template<typename RangeT >
std::enable_if_t<!std::is_convertible< RangeT, Type >::value &&!std::is_convertible< RangeT, Operation * >::value, bool > isLegal (RangeT &&range)
Return true if all of the given types are legal for this type converter.
bool isLegal (Operation *op)
Return true if the given operation has legal operand and result types.
bool isLegal (Region *region)
Return true if the types of block arguments within the region are legal.
bool isSignatureLegal (FunctionType ty)
Return true if the inputs and outputs of the given function type are legal.
LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result)
This method allows for converting a specific argument of a signature.
LogicalResult convertSignatureArgs (TypeRange types, SignatureConversion &result, unsigned origInputOffset=0)
Optional< SignatureConversion > convertBlockSignature (Block *block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
Value materializeArgumentConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs)
Materialize a conversion from a set of types into one result type by generating a cast sequence of some kind.
Value materializeSourceConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs)
Value materializeTargetConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs)
Detailed Description
Converts integer types that are too wide for the target by splitting them in two halves and thus turning into supported ones, i.e., i2*N --> iN, where N is the widest integer bitwidth supported by the target.
Currently, we only handle power-of-two integer types and support conversions of integers twice as wide as the maxium supported by the target. Wide integers are represented as vectors, e.g., i64 --> vector<2xi32>, where the first element is the low half of the original integer, and the second element the high half.
Definition at line 23 of file WideIntEmulationConverter.h.
Constructor & Destructor Documentation
WideIntEmulationConverter()
arith::WideIntEmulationConverter::WideIntEmulationConverter (unsigned widestIntSupportedByTarget) explicit
Definition at line 1047 of file EmulateWideInt.cpp.
References mlir::TypeConverter::addConversion(), mlir::TypeConverter::convertTypes(), mlir::failed(), mlir::Type::getContext(), and None.
Member Function Documentation
getMaxTargetIntBitWidth()
unsigned mlir::arith::WideIntEmulationConverter::getMaxTargetIntBitWidth () const inline
Definition at line 27 of file WideIntEmulationConverter.h.
Referenced by mlir::memref::populateMemRefWideIntEmulationConversions().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Arith/Transforms/WideIntEmulationConverter.h
lib/Dialect/Arith/Transforms/EmulateWideInt.cpp