MLIR: mlir::dataflow::AbstractDenseDataFlowAnalysis Class Reference
mlir::dataflow::AbstractDenseDataFlowAnalysis Class Reference abstract
Base class for dense data-flow analyses.
#include "mlir/Analysis/DataFlow/DenseAnalysis.h"
Public Member Functions
LogicalResult initialize (Operation *top) override
Initialize the analysis by visiting every program point whose execution may modify the program state; that is, every operation and block.
LogicalResult visit (ProgramPoint point) override
Visit a program point that modifies the state of the program.
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
Public Member Functions inherited from mlir::DataFlowAnalysis
virtual ~DataFlowAnalysis ()
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
Protected Member Functions
virtual void visitOperationImpl (Operation *op, const AbstractDenseLattice &before, AbstractDenseLattice *after)=0
Propagate the dense lattice before the execution of an operation to the lattice after its execution.
virtual AbstractDenseLattice * getLattice (ProgramPoint point)=0
Get the dense lattice after the execution of the given program point.
const AbstractDenseLattice * getLatticeFor (ProgramPoint dependent, ProgramPoint point)
Get the dense lattice after the execution of the given program point and add it as a dependency to a program point.
virtual void setToEntryState (AbstractDenseLattice *lattice)=0
Set the dense lattice at control flow entry point and propagate an update if it changed.
void join (AbstractDenseLattice *lhs, const AbstractDenseLattice &rhs)
Join a lattice with another and propagate an update if it changed.
Protected Member Functions inherited from mlir::DataFlowAnalysis
void addDependency (AnalysisState *state, ProgramPoint point)
Create a dependency between the given analysis state and program point on this analysis.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to a state if it changed.
template<typename PointT >
void registerPointKind ()
Register a custom program point class.
template<typename PointT , typename... Args>
PointT * getProgramPoint (Args &&...args)
Get or create a custom program point.
template<typename StateT , typename PointT >
StateT * getOrCreate (PointT point)
Get the analysis state assiocated with the program point.
template<typename StateT , typename PointT >
const StateT * getOrCreateFor (ProgramPoint dependent, PointT point)
Get a read-only analysis state for the given point and create a dependency on dependent.
Detailed Description
Base class for dense data-flow analyses.
Dense data-flow analysis attaches a lattice between the execution of operations and implements a transfer function from the lattice before each operation to the lattice after. The lattice contains information about the state of the program at that point.
In this implementation, a lattice attached to an operation represents the state of the program after its execution, and a lattice attached to block represents the state of the program right before it starts executing its body.
Definition at line 56 of file DenseAnalysis.h.
Member Function Documentation
DataFlowAnalysis()
DataFlowAnalysis::DataFlowAnalysis explicit
Create an analysis with a reference to the parent solver.
Definition at line 352 of file DataFlowFramework.cpp.
getLattice()
virtual AbstractDenseLattice* mlir::dataflow::AbstractDenseDataFlowAnalysis::getLattice (ProgramPoint point) protected pure virtual
Get the dense lattice after the execution of the given program point.
Implemented in mlir::dataflow::DenseDataFlowAnalysis< LatticeT >.
Referenced by getLatticeFor().
getLatticeFor()
const AbstractDenseLattice * AbstractDenseDataFlowAnalysis::getLatticeFor (ProgramPoint dependent, ProgramPoint point) protected
Get the dense lattice after the execution of the given program point and add it as a dependency to a program point.
Definition at line 160 of file DenseAnalysis.cpp.
References mlir::DataFlowAnalysis::addDependency(), and getLattice().
initialize()
LogicalResult AbstractDenseDataFlowAnalysis::initialize (Operation * top) override virtual
Initialize the analysis by visiting every program point whose execution may modify the program state; that is, every operation and block.
Implements mlir::DataFlowAnalysis.
Definition at line 21 of file DenseAnalysis.cpp.
References mlir::failed(), mlir::failure(), mlir::Operation::getRegions(), and mlir::success().
join()
void mlir::dataflow::AbstractDenseDataFlowAnalysis::join (AbstractDenseLattice * lhs, const AbstractDenseLattice & rhs) inline protected
Join a lattice with another and propagate an update if it changed.
Definition at line 92 of file DenseAnalysis.h.
setToEntryState()
virtual void mlir::dataflow::AbstractDenseDataFlowAnalysis::setToEntryState (AbstractDenseLattice * lattice) protected pure virtual
Set the dense lattice at control flow entry point and propagate an update if it changed.
Implemented in mlir::dataflow::DenseDataFlowAnalysis< LatticeT >.
visit()
LogicalResult AbstractDenseDataFlowAnalysis::visit (ProgramPoint point) override virtual
Visit a program point that modifies the state of the program.
If this is a block, then the state is propagated from control-flow predecessors or callsites. If this is a call operation or region control-flow operation, then the state after the execution of the operation is set by control-flow or the callgraph. Otherwise, this function invokes the operation transfer function.
Implements mlir::DataFlowAnalysis.
Definition at line 35 of file DenseAnalysis.cpp.
References mlir::failure(), and mlir::success().
visitOperationImpl()
virtual void mlir::dataflow::AbstractDenseDataFlowAnalysis::visitOperationImpl (Operation * op, const AbstractDenseLattice & before, AbstractDenseLattice * after) protected pure virtual
Propagate the dense lattice before the execution of an operation to the lattice after its execution.
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/DenseAnalysis.h
lib/Analysis/DataFlow/DenseAnalysis.cpp