MLIR: mlir::dataflow::SparseDataFlowAnalysis< StateT > Class Template Reference
mlir::dataflow::SparseDataFlowAnalysis< StateT > Class Template Reference abstract
A sparse (forward) data-flow analysis for propagating SSA value lattices across the IR by implementing transfer functions for operations.
#include "mlir/Analysis/DataFlow/SparseAnalysis.h"
Public Member Functions
SparseDataFlowAnalysis (DataFlowSolver &solver)
virtual void visitOperation (Operation *op, ArrayRef< const StateT * > operands, ArrayRef< StateT * > results)=0
Visit an operation with the lattices of its operands.
virtual void visitNonControlFlowArguments (Operation *op, const RegionSuccessor &successor, ArrayRef< StateT * > argLattices, unsigned firstIndex)
Given an operation with possible region control-flow, the lattices of the operands, and a region successor, compute the lattice values for block arguments that are not accounted for by the branching control flow (ex.
Public Member Functions inherited from mlir::dataflow::AbstractSparseDataFlowAnalysis
LogicalResult initialize (Operation *top) override
Initialize the analysis by visiting every owner of an SSA value: all operations and blocks.
LogicalResult visit (ProgramPoint point) override
Visit a program point.
Public Member Functions inherited from mlir::DataFlowAnalysis
virtual ~DataFlowAnalysis ()
DataFlowAnalysis (DataFlowSolver &solver)
Create an analysis with a reference to the parent solver.
Protected Member Functions
StateT * getLatticeElement (Value value) override
Get the lattice element for a value.
const StateT * getLatticeElementFor (ProgramPoint point, Value value)
Get the lattice element for a value and create a dependency on the provided program point.
virtual void setToEntryState (StateT *lattice)=0
Set the given lattice element(s) at control flow entry point(s).
void setAllToEntryStates (ArrayRef< StateT * > lattices)
Protected Member Functions inherited from mlir::dataflow::AbstractSparseDataFlowAnalysis
AbstractSparseDataFlowAnalysis (DataFlowSolver &solver)
const AbstractSparseLattice * getLatticeElementFor (ProgramPoint point, Value value)
Get a read-only lattice element for a value and add it as a dependency to a program point.
void setAllToEntryStates (ArrayRef< AbstractSparseLattice * > lattices)
void join (AbstractSparseLattice *lhs, const AbstractSparseLattice &rhs)
Join the lattice element and propagate and update if it changed.
Protected Member Functions inherited from mlir::DataFlowAnalysis
void addDependency (AnalysisState *state, ProgramPoint point)
Create a dependency between the given analysis state and program point on this analysis.
void propagateIfChanged (AnalysisState *state, ChangeResult changed)
Propagate an update to a state if it changed.
template<typename PointT >
void registerPointKind ()
Register a custom program point class.
template<typename PointT , typename... Args>
PointT * getProgramPoint (Args &&...args)
Get or create a custom program point.
template<typename StateT , typename PointT >
StateT * getOrCreate (PointT point)
Get the analysis state assiocated with the program point.
template<typename StateT , typename PointT >
const StateT * getOrCreateFor (ProgramPoint dependent, PointT point)
Get a read-only analysis state for the given point and create a dependency on dependent.
Detailed Description
template<typename StateT>
class mlir::dataflow::SparseDataFlowAnalysis< StateT >
A sparse (forward) data-flow analysis for propagating SSA value lattices across the IR by implementing transfer functions for operations.
StateT is expected to be a subclass of AbstractSparseLattice.
Definition at line 214 of file SparseAnalysis.h.
Constructor & Destructor Documentation
SparseDataFlowAnalysis()
template<typename StateT > mlir::dataflow::SparseDataFlowAnalysis< StateT >::SparseDataFlowAnalysis (DataFlowSolver & solver) inline explicit
Definition at line 220 of file SparseAnalysis.h.
Member Function Documentation
getLatticeElement()
template<typename StateT > StateT* mlir::dataflow::SparseDataFlowAnalysis< StateT >::getLatticeElement (Value value) inline override protected virtual
Get the lattice element for a value.
Implements mlir::dataflow::AbstractSparseDataFlowAnalysis.
Definition at line 245 of file SparseAnalysis.h.
References value.
getLatticeElementFor()
template<typename StateT > const StateT* mlir::dataflow::SparseDataFlowAnalysis< StateT >::getLatticeElementFor (ProgramPoint point, Value value) inline protected
Get the lattice element for a value and create a dependency on the provided program point.
Definition at line 251 of file SparseAnalysis.h.
References mlir::dataflow::AbstractSparseDataFlowAnalysis::getLatticeElementFor(), and value.
setAllToEntryStates()
template<typename StateT > void mlir::dataflow::SparseDataFlowAnalysis< StateT >::setAllToEntryStates (ArrayRef< StateT * > lattices) inline protected
Definition at line 258 of file SparseAnalysis.h.
References mlir::dataflow::AbstractSparseDataFlowAnalysis::setAllToEntryStates().
Referenced by mlir::dataflow::SparseDataFlowAnalysis< StateT >::visitNonControlFlowArguments().
setToEntryState()
template<typename StateT > virtual void mlir::dataflow::SparseDataFlowAnalysis< StateT >::setToEntryState (StateT * lattice) protected pure virtual
Set the given lattice element(s) at control flow entry point(s).
Implemented in mlir::dataflow::SparseConstantPropagation, and mlir::dataflow::IntegerRangeAnalysis.
visitNonControlFlowArguments()
template<typename StateT > virtual void mlir::dataflow::SparseDataFlowAnalysis< StateT >::visitNonControlFlowArguments (Operation * op, const RegionSuccessor & successor, ArrayRef< StateT * > argLattices, unsigned firstIndex) inline virtual
Given an operation with possible region control-flow, the lattices of the operands, and a region successor, compute the lattice values for block arguments that are not accounted for by the branching control flow (ex.
the bounds of loops). By default, this method marks all such lattice elements as having reached a pessimistic fixpoint. firstIndex is the index of the first element of argLattices that is set by control-flow.
Reimplemented in mlir::dataflow::IntegerRangeAnalysis.
Definition at line 234 of file SparseAnalysis.h.
References mlir::RegionSuccessor::getSuccessorInputs(), and mlir::dataflow::SparseDataFlowAnalysis< StateT >::setAllToEntryStates().
Referenced by mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments().
visitOperation()
template<typename StateT > virtual void mlir::dataflow::SparseDataFlowAnalysis< StateT >::visitOperation (Operation * op, ArrayRef< const StateT * > operands, ArrayRef< StateT * > results) pure virtual
Visit an operation with the lattices of its operands.
This function is expected to set the lattices of the operation's results.
Implemented in mlir::dataflow::SparseConstantPropagation, and mlir::dataflow::IntegerRangeAnalysis.
The documentation for this class was generated from the following file:
include/mlir/Analysis/DataFlow/SparseAnalysis.h