MLIR: mlir::dataflow::IntegerValueRangeLattice Class Reference
mlir::dataflow::IntegerValueRangeLattice Class Reference
This lattice element represents the integer value range of an SSA value.
#include "mlir/Analysis/DataFlow/IntegerRangeAnalysis.h"
Public Member Functions
void onUpdate (DataFlowSolver *solver) const override
If the range can be narrowed to an integer constant, update the constant value of the SSA value.
Public Member Functions inherited from mlir::dataflow::Lattice< IntegerValueRange >
Value getPoint () const
Return the program point this lattice is located at.
IntegerValueRange & getValue ()
Return the value held by this lattice.
const IntegerValueRange & getValue () const
ChangeResult join (const AbstractSparseLattice &rhs) override
Join the information contained in the 'rhs' lattice into this lattice.
ChangeResult join (const IntegerValueRange &rhs)
Join the information contained in the 'rhs' value into this lattice.
void print (raw_ostream &os) const override
Print the lattice element.
AbstractSparseLattice (Value value)
Lattices can only be created for values.
Public Member Functions inherited from mlir::dataflow::AbstractSparseLattice
AbstractSparseLattice (Value value)
Lattices can only be created for values.
Value getPoint () const
Return the program point this lattice is located at.
void onUpdate (DataFlowSolver *solver) const override
When the lattice gets updated, propagate an update to users of the value using its use-def chain to subscribed analyses.
void useDefSubscribe (DataFlowAnalysis *analysis)
Subscribe an analysis to updates of the lattice.
Public Member Functions inherited from mlir::AnalysisState
virtual ~AnalysisState ()
AnalysisState (ProgramPoint point)
Create the analysis state at the given program point.
ProgramPoint getPoint () const
Returns the program point this static is located at.
Additional Inherited Members
Protected Attributes inherited from mlir::AnalysisState
SetVector< DataFlowSolver::WorkItem > dependents
The dependency relations originating from this analysis state.
ProgramPoint point
The program point to which the state belongs.
Detailed Description
This lattice element represents the integer value range of an SSA value.
When this lattice is updated, it automatically updates the constant value of the SSA value (if the range can be narrowed to one).
Definition at line 72 of file IntegerRangeAnalysis.h.
Member Function Documentation
onUpdate()
void IntegerValueRangeLattice::onUpdate (DataFlowSolver * solver) const override virtual
If the range can be narrowed to an integer constant, update the constant value of the SSA value.
Reimplemented from mlir::AnalysisState.
Definition at line 35 of file IntegerRangeAnalysis.cpp.
References mlir::ConstantIntRanges::getConstantValue(), mlir::DataFlowSolver::getOrCreateState(), mlir::dataflow::ConstantValue::getUnknownConstant(), mlir::dataflow::Lattice< IntegerValueRange >::getValue(), mlir::dataflow::IntegerValueRange::getValue(), mlir::dataflow::AbstractSparseLattice::onUpdate(), mlir::AnalysisState::point, and mlir::DataFlowSolver::propagateIfChanged().
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/IntegerRangeAnalysis.h
lib/Analysis/DataFlow/IntegerRangeAnalysis.cpp