MLIR: mlir::OpBuilder Class Reference
mlir::OpBuilder Class Reference
This class helps build Operations.
#include "mlir/IR/Builders.h"
Classes
class InsertionGuard
RAII guard to reset the insertion point of the builder when destroyed.
class InsertPoint
This class represents a saved insertion point.
struct Listener
This class represents a listener that may be used to hook into various actions within an OpBuilder.
Public Member Functions
OpBuilder (MLIRContext *ctx, Listener *listener=nullptr)
Create a builder with the given context.
OpBuilder (Region *region, Listener *listener=nullptr)
Create a builder and set the insertion point to the start of the region.
OpBuilder (Region &region, Listener *listener=nullptr)
OpBuilder (Operation *op, Listener *listener=nullptr)
Create a builder and set insertion point to the given operation, which will cause subsequent insertions to go right before it.
OpBuilder (Block *block, Block::iterator insertPoint, Listener *listener=nullptr)
void setListener (Listener *newListener)
Sets the listener of this builder to the one provided.
Listener * getListener () const
Returns the current listener of this builder, or nullptr if this builder doesn't have a listener.
void clearInsertionPoint ()
Reset the insertion point to no location.
InsertPoint saveInsertionPoint () const
Return a saved insertion point.
void restoreInsertionPoint (InsertPoint ip)
Restore the insert point to a previously saved point.
void setInsertionPoint (Block *block, Block::iterator insertPoint)
Set the insertion point to the specified location.
void setInsertionPoint (Operation *op)
Sets the insertion point to the specified operation, which will cause subsequent insertions to go right before it.
void setInsertionPointAfter (Operation *op)
Sets the insertion point to the node after the specified operation, which will cause subsequent insertions to go right after it.
void setInsertionPointAfterValue (Value val)
Sets the insertion point to the node after the specified value.
void setInsertionPointToStart (Block *block)
Sets the insertion point to the start of the specified block.
void setInsertionPointToEnd (Block *block)
Sets the insertion point to the end of the specified block.
Block * getInsertionBlock () const
Return the block the current insertion point belongs to.
Block::iterator getInsertionPoint () const
Returns the current insertion point of the builder.
Block * getBlock () const
Returns the current block of the builder.
Block * createBlock (Region *parent, Region::iterator insertPt={}, TypeRange argTypes=llvm::None, ArrayRef< Location > locs=llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Block * createBlock (Block *insertBefore, TypeRange argTypes=llvm::None, ArrayRef< Location > locs=llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
Operation * insert (Operation *op)
Insert the given operation at the current insertion point and return it.
Operation * create (const OperationState &state)
Creates an operation given the fields represented as an OperationState.
Operation * create (Location loc, StringAttr opName, ValueRange operands, TypeRange types={}, ArrayRef< NamedAttribute > attributes={}, BlockRange successors={}, MutableArrayRef< std::unique_ptr< Region >> regions={})
Creates an operation with the given fields.
template<typename OpTy , typename... Args>
OpTy create (Location location, Args &&...args)
Create an operation of specific op type at the current insertion point.
template<typename OpTy , typename... Args>
void createOrFold (SmallVectorImpl< Value > &results, Location location, Args &&...args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< OpTrait::OneResult >), Value > createOrFold (Location location, Args &&...args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if_t< OpTy::template hasTrait< OpTrait::ZeroResults >), OpTy > createOrFold (Location location, Args &&...args)
Overload to create or fold a zero result operation.
LogicalResult tryFold (Operation *op, SmallVectorImpl< Value > &results)
Attempts to fold the given operation and places new results within 'results'.
Operation * clone (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of the specified operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Operation * clone (Operation &op)
Operation * cloneWithoutRegions (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of this operation but keep the operation regions empty.
Operation * cloneWithoutRegions (Operation &op)
template<typename OpT >
OpT cloneWithoutRegions (OpT op)
Public Member Functions inherited from mlir::Builder
Builder (MLIRContext *context)
Builder (Operation *op)
MLIRContext * getContext () const
Location getUnknownLoc ()
Location getFusedLoc (ArrayRef< Location > locs, Attribute metadata=Attribute())
FloatType getFloat8E5M2Type ()
FloatType getFloat8E4M3FNType ()
FloatType getBF16Type ()
FloatType getF16Type ()
FloatType getF32Type ()
FloatType getF64Type ()
FloatType getF80Type ()
FloatType getF128Type ()
IndexType getIndexType ()
IntegerType getI1Type ()
IntegerType getI2Type ()
IntegerType getI4Type ()
IntegerType getI8Type ()
IntegerType getI16Type ()
IntegerType getI32Type ()
IntegerType getI64Type ()
IntegerType getIntegerType (unsigned width)
IntegerType getIntegerType (unsigned width, bool isSigned)
FunctionType getFunctionType (TypeRange inputs, TypeRange results)
TupleType getTupleType (TypeRange elementTypes)
NoneType getNoneType ()
template<typename Ty , typename... Args>
Ty getType (Args &&...args)
Get or construct an instance of the type Ty with provided arguments.
template<typename Attr , typename... Args>
Attr getAttr (Args &&...args)
Get or construct an instance of the attribute Attr with provided arguments.
NamedAttribute getNamedAttr (StringRef name, Attribute val)
UnitAttr getUnitAttr ()
BoolAttr getBoolAttr (bool value)
DictionaryAttr getDictionaryAttr (ArrayRef< NamedAttribute > value)
IntegerAttr getIntegerAttr (Type type, int64_t value)
IntegerAttr getIntegerAttr (Type type, const APInt &value)
FloatAttr getFloatAttr (Type type, double value)
FloatAttr getFloatAttr (Type type, const APFloat &value)
StringAttr getStringAttr (const Twine &bytes)
ArrayAttr getArrayAttr (ArrayRef< Attribute > value)
Attribute getZeroAttr (Type type)
FloatAttr getF16FloatAttr (float value)
FloatAttr getF32FloatAttr (float value)
FloatAttr getF64FloatAttr (double value)
IntegerAttr getI8IntegerAttr (int8_t value)
IntegerAttr getI16IntegerAttr (int16_t value)
IntegerAttr getI32IntegerAttr (int32_t value)
IntegerAttr getI64IntegerAttr (int64_t value)
IntegerAttr getIndexAttr (int64_t value)
IntegerAttr getSI32IntegerAttr (int32_t value)
Signed and unsigned integer attribute getters.
IntegerAttr getUI32IntegerAttr (uint32_t value)
DenseIntElementsAttr getBoolVectorAttr (ArrayRef< bool > values)
Vector-typed DenseIntElementsAttr getters. values must not be empty.
DenseIntElementsAttr getI32VectorAttr (ArrayRef< int32_t > values)
DenseIntElementsAttr getI64VectorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getIndexVectorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getI32TensorAttr (ArrayRef< int32_t > values)
Tensor-typed DenseIntElementsAttr getters.
DenseIntElementsAttr getI64TensorAttr (ArrayRef< int64_t > values)
DenseIntElementsAttr getIndexTensorAttr (ArrayRef< int64_t > values)
DenseBoolArrayAttr getDenseBoolArrayAttr (ArrayRef< bool > values)
Tensor-typed DenseArrayAttr getters.
DenseI8ArrayAttr getDenseI8ArrayAttr (ArrayRef< int8_t > values)
DenseI16ArrayAttr getDenseI16ArrayAttr (ArrayRef< int16_t > values)
DenseI32ArrayAttr getDenseI32ArrayAttr (ArrayRef< int32_t > values)
DenseI64ArrayAttr getDenseI64ArrayAttr (ArrayRef< int64_t > values)
DenseF32ArrayAttr getDenseF32ArrayAttr (ArrayRef< float > values)
DenseF64ArrayAttr getDenseF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getAffineMapArrayAttr (ArrayRef< AffineMap > values)
ArrayAttr getBoolArrayAttr (ArrayRef< bool > values)
ArrayAttr getI32ArrayAttr (ArrayRef< int32_t > values)
ArrayAttr getI64ArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getIndexArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getF32ArrayAttr (ArrayRef< float > values)
ArrayAttr getF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getStrArrayAttr (ArrayRef< StringRef > values)
ArrayAttr getTypeArrayAttr (TypeRange values)
AffineExpr getAffineDimExpr (unsigned position)
AffineExpr getAffineSymbolExpr (unsigned position)
AffineExpr getAffineConstantExpr (int64_t constant)
AffineMap getEmptyAffineMap ()
Returns a zero result affine map with no dimensions or symbols: () -> ().
AffineMap getConstantAffineMap (int64_t val)
Returns a single constant result affine map with 0 dimensions and 0 symbols.
AffineMap getDimIdentityMap ()
AffineMap getMultiDimIdentityMap (unsigned rank)
AffineMap getSymbolIdentityMap ()
AffineMap getSingleDimShiftAffineMap (int64_t shift)
Returns a map that shifts its (single) input dimension by 'shift'.
AffineMap getShiftedAffineMap (AffineMap map, int64_t shift)
Returns an affine map that is a translation (shift) of all result expressions in 'map' by 'shift'.
Static Public Member Functions
static OpBuilder atBlockBegin (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
static OpBuilder atBlockEnd (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
static OpBuilder atBlockTerminator (Block *block, Listener *listener=nullptr)
Create a builder and set the insertion point to before the block terminator.
Additional Inherited Members
Protected Attributes inherited from mlir::Builder
MLIRContext * context
Detailed Description
This class helps build Operations.
Operations that are created are automatically inserted at an insertion point. The builder is copyable.
Definition at line 198 of file Builders.h.
Constructor & Destructor Documentation
OpBuilder() [1/5]
mlir::OpBuilder::OpBuilder (MLIRContext * ctx, Listener * listener = nullptr) inline explicit
Create a builder with the given context.
Definition at line 203 of file Builders.h.
Referenced by atBlockBegin(), atBlockEnd(), and atBlockTerminator().
OpBuilder() [2/5]
mlir::OpBuilder::OpBuilder (Region * region, Listener * listener = nullptr) inline explicit
Create a builder and set the insertion point to the start of the region.
Definition at line 207 of file Builders.h.
References mlir::Block::begin(), mlir::Region::empty(), mlir::Region::front(), and setInsertionPoint().
OpBuilder() [3/5]
mlir::OpBuilder::OpBuilder (Region & region, Listener * listener = nullptr) inline explicit
Definition at line 212 of file Builders.h.
OpBuilder() [4/5]
mlir::OpBuilder::OpBuilder (Operation * op, Listener * listener = nullptr) inline explicit
Create a builder and set insertion point to the given operation, which will cause subsequent insertions to go right before it.
Definition at line 217 of file Builders.h.
References setInsertionPoint().
OpBuilder() [5/5]
mlir::OpBuilder::OpBuilder (Block * block, Block::iterator insertPoint, Listener * listener = nullptr) inline
Definition at line 222 of file Builders.h.
References setInsertionPoint().
Member Function Documentation
atBlockBegin()
static OpBuilder mlir::OpBuilder::atBlockBegin (Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to before the first operation in the block but still inside the block.
Definition at line 230 of file Builders.h.
References mlir::Block::begin(), and OpBuilder().
Referenced by mlir::collapseParallelLoops(), getOrInsertPushConstantVariable(), mlir::normalizeAffineParallel(), and normalizeLoop().
atBlockEnd()
static OpBuilder mlir::OpBuilder::atBlockEnd (Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to after the last operation in the block but still inside the block.
Definition at line 236 of file Builders.h.
References mlir::Block::end(), and OpBuilder().
atBlockTerminator()
static OpBuilder mlir::OpBuilder::atBlockTerminator (Block * block, Listener * listener = nullptr) inline static
Create a builder and set the insertion point to before the block terminator.
Definition at line 242 of file Builders.h.
References mlir::Block::getTerminator(), and OpBuilder().
Referenced by createFullTiles(), generatePointWiseCopy(), generateShiftedLoop(), generateUnrolledLoop(), and stripmineSink().
clearInsertionPoint()
void mlir::OpBuilder::clearInsertionPoint () inline
Reset the insertion point to no location.
Creating an operation without a set insertion point is an error, but this can still be useful when the current insertion point a builder refers to is being removed.
Definition at line 331 of file Builders.h.
Referenced by restoreInsertionPoint().
clone() [1/2]
Operation * OpBuilder::clone (Operation & op)
Definition at line 525 of file Builders.cpp.
References clone().
clone() [2/2]
Operation * OpBuilder::clone (Operation & op, BlockAndValueMapping & mapper)
Creates a deep copy of the specified operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Replaces references to cloned sub-operations to the corresponding operation that is copied, and adds those mappings to the map.
Definition at line 510 of file Builders.cpp.
References mlir::Operation::clone(), mlir::Operation::getRegions(), insert(), and mlir::OpBuilder::Listener::notifyOperationInserted().
Referenced by clone(), cloneAndFuseFirstUse(), mlir::async::cloneConstantsIntoTheRegion(), createFullPartialVectorTransferWrite(), createFullTiles(), createParallelComputeFunction(), fuseIfLegal(), mlir::fuseLoops(), generateCleanupLoopForUnroll(), generateFusedElementwiseOpRegion(), genForeachOnSparseConstant(), hoistAffineIfOp(), mlir::linalg::hoistPaddingOnTensors(), inlinePayload(), inlineRegionAndEmitStore(), mlir::insertBackwardComputationSlice(), mlir::loopUnrollByFactor(), mlir::loopUnrollJamByFactor(), CanonicalizeContractAdd< AddOpType >::matchAndRewrite(), AllocaScopeHoister::matchAndRewrite(), mlir::outlineSingleBlockRegion(), peelForLoop(), mlir::sinkOperationsIntoLaunchOp(), mlir::vector::splitFullAndPartialTransfer(), mlir::linalg::splitReduction(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), tileLinalgOpImpl(), tilePadOp(), mlir::linalg::tileReductionUsingForeachThread(), tileToForeachThreadOpImpl(), and vectorizeOneOp().
cloneWithoutRegions() [1/3]
Operation* mlir::OpBuilder::cloneWithoutRegions (Operation & op) inline
Definition at line 529 of file Builders.h.
References mlir::Operation::cloneWithoutRegions(), and insert().
cloneWithoutRegions() [2/3]
Operation* mlir::OpBuilder::cloneWithoutRegions (Operation & op, BlockAndValueMapping & mapper) inline
Creates a deep copy of this operation but keep the operation regions empty.
Operands are remapped using mapper (if present), and mapper is updated to contain the results.
Definition at line 526 of file Builders.h.
References mlir::Operation::cloneWithoutRegions(), and insert().
Referenced by cloneWithoutRegions(), and wrapInExecuteRegion().
cloneWithoutRegions() [3/3]
template<typename OpT > OpT mlir::OpBuilder::cloneWithoutRegions (OpT op) inline
Definition at line 533 of file Builders.h.
References cloneWithoutRegions().
create() [1/3]
Operation * OpBuilder::create (const OperationState & state)
Creates an operation given the fields represented as an OperationState.
Create an operation given the fields represented as an OperationState.
Definition at line 422 of file Builders.cpp.
References mlir::Operation::create(), and insert().
Referenced by addAtomicRMW(), adjustAccessChainForBitwidth(), mlir::affineParallelize(), mlir::UnrankedMemRefDescriptor::alignedPtr(), mlir::AllocationOpLLVMLowering::allocateBufferAutoAlign(), mlir::AllocationOpLLVMLowering::allocateBufferManuallyAlign(), mlir::UnrankedMemRefDescriptor::allocatedPtr(), mlir::bufferization::allocateTensorForShapedValue(), mlir::sparse_tensor::allocDenseTensor(), appendX1Dim(), applyPad(), broadcast(), mlir::tensor::bubbleUpPadSlice(), mlir::bufferization::func_ext::CallOpInterface::bufferize(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter(), buildAffineLoopFromConstants(), buildAffineLoopFromValues(), buildAffineLoopNestImpl(), buildIdentityRegion(), mlir::scf::buildLoopNest(), buildMinMaxReductionSeq(), buildMultiDimReduce(), mlir::scf::buildTerminatedBody(), mlir::vector::buildTerminatedBody(), buildVectorComparison(), buildVectorWrite(), calculateExpandedAccessIndices(), canonicalizeMinMaxOp(), castBoolToIntN(), castDataPtr(), castIntNToBool(), mlir::bufferization::castOrReallocMemRefValue(), ceilDivPositive(), checkAndNestUnderRewriteOp(), mlir::tosa::checkHasDynamicBatchDims(), mlir::tosa::clampFloatHelper(), mlir::tosa::clampIntHelper(), cloneOpWithOperandsAndTypes(), mlir::coalesceLoops(), collapseGenericOpIterationDims(), mlir::collapseParallelLoops(), mlir::spirv::combine(), mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::sparse_tensor::constantI1(), mlir::sparse_tensor::constantI16(), mlir::sparse_tensor::constantI32(), mlir::sparse_tensor::constantI8(), mlir::sparse_tensor::constantIndex(), mlir::sparse_tensor::constantOne(), mlir::sparse_tensor::constantZero(), mlir::detail::constructContainerOpForParserIfNecessary(), constructTiledLoopNest(), convertBroadcastOp(), convertConstantOp(), convertConstantOpMmaSync(), convertContractOp(), convertContractOpToMmaSync(), convertCtlzOp(), convertElementwiseOp(), convertExtractStridedSlice(), convertIntrinsicResult(), mlir::convertScalarToDtype(), convertTanhOp(), convertToLaunchFuncOp(), convertTransferReadOp(), convertTransferWriteOp(), convertTransferWriteToStores(), convertYieldOp(), copy(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), create(), mlir::OperationFolder::create(), createAdd(), mlir::createAffineComputationSlice(), mlir::AllocationOpLLVMLowering::createAligned(), mlir::bufferization::BufferizationOptions::createAlloc(), createAsyncDispatchFunction(), createBinarySearchFunc(), mlir::createCanonicalizedAffineForOp(), createCompareFuncImplementation(), createConst(), createConstantAllBitsSet(), createConstFromIntAttribute(), mlir::bufferization::BufferizationOptions::createDealloc(), createDecl(), mlir::tensor::createDynamicDimValues(), createEqCompare(), mlir::linalg::GeneralizePadOpPattern::createFillOrGenerateOp(), createFoldedSLE(), createForAllDimensions(), createFPConstant(), createFullPartialLinalgCopy(), createFullPartialVectorTransferRead(), createFullPartialVectorTransferWrite(), mlir::sparse_tensor::createFuncCall(), mlir::LLVM::createGlobalString(), createGlobalVarForEntryPointArgument(), createGpuLaunch(), createI32ConstantOf(), createInBoundsCond(), mlir::ConvertToLLVMPattern::createIndexAttrConstant(), createIndexAttrConstant(), mlir::AllocationOpLLVMLowering::createIndexConstant(), createLessThanCompare(), createLinalgBodyCalculationForElementwiseOp(), createLinalgBodyCalculationForReduceOp(), mlir::bufferization::BufferizationOptions::createMemCpy(), createMul(), createNewDynamicSizes(), createNonLdMatrixLoads(), createOrFold(), mlir::tensor::createPadHighOp(), createPartitionFunc(), createPrivateMemRef(), createScalarOrSplatConstant(), createScanLoop(), createSeparationCondition(), createSortNonstableFunc(), createSortStableFunc(), createSplitPart(), createSubViewIntersection(), createSwap(), createSwitchOp(), creatLdMatrixCompatibleLoads(), mlir::sparse_tensor::deallocDenseTensor(), defaultDeallocBufferCallBack(), deriveStaticUpperBound(), doSequentialDispatch(), doubleBuffer(), mlir::bufferization::dropEquivalentBufferResults(), dropRefIfNoUses(), dropTrailingX1Dim(), elementwiseMatchAndRewriteHelper(), mlir::tensor::ExtractSliceFromCollapseHelper::emitLoopNestBody(), emitScalarImplementation(), endIf(), ensureDistinctSuccessors(), mlir::sparse_tensor::SparseTensorLoopEmitter::enterCoIterationOverTensorsAtDims(), mlir::sparse_tensor::SparseTensorLoopEmitter::enterLoopOverTensorAtDim(), mlir::extractFixedOuterLoops(), extractLastDimSlice(), extractOne(), mlir::StructBuilder::extractPtr(), finalizeWhileOp(), forEachIJPairInXs(), mlir::sparse_tensor::foreachInSparseConstant(), mlir::linalg::fuseElementwiseOps(), mlir::linalg::TileLoopNest::fuseProducer(), mlir::linalg::fuseProducerOfTensor(), fuseWithReshapeByExpansion(), genAffine(), mlir::sparse_tensor::genAlloca(), mlir::sparse_tensor::genAllocaScalar(), mlir::linalg::generalizeNamedOp(), generateCollapsedIndexingRegion(), generateCopy(), generateFusedElementwiseOpRegion(), generateGpuBlockIds(), mlir::linalg::generateParallelLoopNest(), generatePointWiseCopy(), generateShiftedLoop(), generateTileLoopNest(), genIf(), genIndexAndValueForSparse(), genIndexLoad(), genInsertionLoad(), genInsertionLoadReduce(), mlir::sparse_tensor::genIsNonzero(), mlir::sparse_tensor::genReshapeDstShape(), genSplitSparseConstant(), genTensorLoad(), mlir::sparse_tensor::genValueForDense(), getAsValue(), mlir::bufferization::getBuffer(), getCleanupLoopLowerBound(), getCollapsedOpOperand(), getConvOutputDim(), getExpandedOutputDimFromInputShape(), mlir::sparse_tensor::getFunc(), mlir::bufferization::getGlobalFor(), mlir::arith::getIdentityValue(), getIndexedPtrs(), getIndicesForAccess(), getLibraryCallSymbolRef(), getLocalInvocationDimSize(), getLocationToWriteFullVec(), getMangledSortHelperFunc(), mlir::ConvertToLLVMPattern::getMemRefDescriptorSizes(), mlir::tensor::getMixedSizes(), mlir::ConvertToLLVMPattern::getNumElements(), getOffsetForBitwidth(), mlir::spirv::getOpenCLElementPtr(), mlir::tensor::getOrCreateDestination(), getOrCreateStep(), getOrDefineFunction(), getOrInsertBuiltinVariable(), getOrInsertPushConstantVariable(), mlir::spirv::getPushConstantValue(), getScalarOrVectorI32Constant(), getShapeDimSize(), mlir::ConvertToLLVMPattern::getSizeInBytes(), mlir::getValueOrCreateCastToIndexLike(), mlir::getValueOrCreateConstantIndexOp(), mlir::vector::getVectorReductionOp(), mlir::spirv::getVulkanElementPtr(), getZero(), mlir::LLVM::detail::handleMultidimensionalVectors(), hoistAffineIfOp(), inferDynamicDimsForConv(), mlir::sparse_tensor::SparseTensorLoopEmitter::initializeLoopEmit(), inlineIfCase(), inlinePayload(), inlineRegionAndEmitStore(), inlineWhileCase(), insertCasts(), insertLastDimSlice(), insertOne(), mlir::bufferization::insertSliceAnchoredEmptyTensorEliminationStep(), insertSliceIntoTensor(), mlir::linalg::insertSlicesBack(), mlir::sparse_tensor::insertYieldOp(), invertCollapseShapeIndexing(), mlir::spirv::linearizeIndex(), mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::LLVM::lookupOrCreateFn(), mlir::loopUnrollByFactor(), mlir::loopUnrollJamByFactor(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), mlir::scf::lowerToLoopsUsingSCFForOp(), mlir::makeComposedAffineApply(), mlir::linalg::makeMemRefCopyOp(), mlir::linalg::makeTransposeOp(), mlir::transform::gpu::mapForeachToBlocksImpl(), matchAndReplaceDepthwiseConv(), SelectI1Simplify::matchAndRewrite(), SelectToExtUI::matchAndRewrite(), YieldOpLowering::matchAndRewrite(), AssertOpLowering::matchAndRewrite(), CollapseShapeOpMemRefCastFolder::matchAndRewrite(), MaterializeTransferMask< ConcreteOp >::matchAndRewrite(), MultiBlockExecuteInliner::matchAndRewrite(), Convert1DExtractStridedSliceIntoExtractInsertChain::matchAndRewrite(), DecomposeNDExtractStridedSlice::matchAndRewrite(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::GPUPrintfOpToLLVMCallLowering::matchAndRewrite(), DecomposeDifferentRankInsertStridedSlice::matchAndRewrite(), FoldLaunchArguments::matchAndRewrite(), mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::OpWithOffsetSizesAndStridesConstantArgumentFolder< OpType, ResultTypeFunc, CastOpFunc >::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), ConvertAccessChain::matchAndRewrite(), ConvertLoad::matchAndRewrite(), ConvertStore::matchAndRewrite(), SwapExtractSliceOfFill::matchAndRewrite(), mlir::linalg::PadOpTransformationPattern::matchAndRewrite(), mlir::linalg::GeneralizePadOpPattern::matchAndRewrite(), MaterializePadValue::matchAndRewrite(), BubbleUpBitCastForStridedSliceInsert::matchAndRewrite(), BubbleDownVectorBitCastForExtract::matchAndRewrite(), BubbleDownBitCastForStridedSliceExtract::matchAndRewrite(), VectorLoadToMemrefLoadLowering::matchAndRewrite(), InnerOuterDimReductionConversion::matchAndRewrite(), ReduceMultiDimReductionRank::matchAndRewrite(), TwoDimMultiReductionToElementWise::matchAndRewrite(), TwoDimMultiReductionToReduction::matchAndRewrite(), OneDimMultiReductionToTwoDim::matchAndRewrite(), VectorStoreToMemrefStoreLowering::matchAndRewrite(), TransferReadPermutationLowering::matchAndRewrite(), TransferOpReduceRank::matchAndRewrite(), TransferReadToVectorLoadLowering::matchAndRewrite(), TransferWritePermutationLowering::matchAndRewrite(), mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite(), matchAndRewriteSortOp(), mlir::linalg::materializeTiledShape(), materializeToTensor(), mfmaConcatIfNeeded(), moveRegionToNewWarpOpAndReplaceReturns(), mlir::memref::multiBuffer(), mlir::normalizeAffineFor(), normalizeLoop(), mlir::normalizeMemRef(), mlir::MemRefDescriptor::offset(), mlir::UnrankedMemRefDescriptor::offset(), ofrToIndexValues(), mlir::LLVM::detail::oneToOneRewrite(), SliceCanonicalizer::operator()(), optionallyTruncateOrExtend(), outlineKernelFuncImpl(), mlir::outlineSingleBlockRegion(), padOperandToSmallestStaticBoundingBox(), permuteVectorOffset(), mlir::bufferization::populateDynamicDimSizes(), processParallelLoop(), mlir::promoteIfSingleIteration(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), mlir::linalg::promoteSubviewAsNewBuffer(), reduceMatchAndRewriteHelper(), mlir::replaceAllMemRefUsesWith(), replaceConstantUsesOf(), replaceForOpWithNewSignature(), mlir::replaceForOpWithNewYields(), mlir::replaceLoopWithNewYields(), mlir::bufferization::replaceOpWithBufferizedValues(), mlir::bufferization::replaceOpWithNewBufferizedOp(), replaceSCFOutputValue(), replaceUsesAndPropagateType(), reshapeLoad(), reshapeLowerToHigher(), reshapeStore(), resolveSourceIndicesCollapseShape(), resolveSourceIndicesExpandShape(), resolveSourceIndicesSubView(), resolveUsesInRepetitiveRegions(), mlir::linalg::DownscaleSizeOneWindowed2DConvolution< Conv2DOp, Conv1DOp >::returningMatchAndRewrite(), mlir::linalg::DownscaleDepthwiseConv2DNhwcHwcOp::returningMatchAndRewrite(), mlir::linalg::rewriteAsPaddedOp(), rewriteOneForeachThreadToGpuThreads(), PadOpVectorizationWithInsertSlicePattern::rewriteUser(), mlir::impl::scalarizeVectorOp(), mlir::UnrankedMemRefDescriptor::setAlignedPtr(), mlir::UnrankedMemRefDescriptor::setAllocatedPtr(), mlir::UnrankedMemRefDescriptor::setOffset(), mlir::MemRefDescriptor::setOffset(), mlir::StructBuilder::setPtr(), mlir::UnrankedMemRefDescriptor::setSize(), mlir::MemRefDescriptor::setSize(), mlir::UnrankedMemRefDescriptor::setStride(), mlir::MemRefDescriptor::setStride(), mlir::linalg::LinalgTilingOptions::setTileSizes(), mlir::scf::SCFTilingOptions::setTileSizes(), shiftValue(), mlir::tensor::simplifyCollapseShapeWithRankReducingExtractSlice(), mlir::UnrankedMemRefDescriptor::size(), mlir::MemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), sizesForTensor(), sliceTransferIndices(), sourceMaterializationCallback(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::vector::splitFullAndPartialTransfer(), mlir::linalg::splitReduction(), mlir::linalg::splitReductionByScaling(), mlir::UnrankedMemRefDescriptor::stride(), mlir::MemRefDescriptor::stride(), mlir::UnrankedMemRefDescriptor::strideBasePtr(), stripmineSink(), mlir::scf::tileParallelLoop(), mlir::linalg::tileReductionUsingForeachThread(), mlir::scf::tileReductionUsingScf(), tileToForeachThreadOpImpl(), mlir::scf::tileUsingSCFForOp(), mlir::sparse_tensor::translateIndicesArray(), GenericPadOpVectorizationPattern::tryVectorizeCopy(), mlir::DataDescriptor::undef(), mlir::MemRefDescriptor::undef(), mlir::UnrankedMemRefDescriptor::undef(), mlir::ComplexStructBuilder::undef(), unpackOperandVector(), updateCalls(), updateExpandedGenericOpRegion(), updateReturnOps(), vectorizeAsLinalgGeneric(), mlir::linalg::vectorizeCopy(), vectorizeLinalgIndex(), vectorizeOneOp(), vectorizeTensorExtract(), mlir::LLVM::detail::vectorOneToOneRewrite(), wrapExternalFunction(), wrapForExternalCallers(), wrapInExecuteRegion(), and yieldTiledValues().
create() [2/3]
Operation * OpBuilder::create (Location loc, StringAttr opName, ValueRange operands, TypeRange types = {}, ArrayRef< NamedAttribute > attributes = {}, BlockRange successors = {}, MutableArrayRef< std::unique_ptr< Region >> regions = {})
Creates an operation with the given fields.
Definition at line 427 of file Builders.cpp.
create() [3/3]
template<typename OpTy , typename... Args> OpTy mlir::OpBuilder::create (Location location, Args &&... args) inline
Create an operation of specific op type at the current insertion point.
Definition at line 458 of file Builders.h.
References create(), and mlir::Location::getContext().
createBlock() [1/2]
Block * OpBuilder::createBlock (Block * insertBefore, TypeRange argTypes = llvm::None, ArrayRef< Location > locs = llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
The block is placed before 'insertBefore'. locs contains the locations of the inserted arguments, and should match the size of argTypes.
The block is placed before 'insertBefore'.
Definition at line 414 of file Builders.cpp.
References createBlock(), and mlir::Block::getParent().
createBlock() [2/2]
Block * OpBuilder::createBlock (Region * parent, Region::iterator insertPt = {}, TypeRange argTypes = llvm::None, ArrayRef< Location > locs = llvm::None)
Add new block with 'argTypes' arguments and set the insertion point to the end of it.
The block is inserted at the provided insertion point of 'parent'. locs contains the locations of the inserted arguments, and should match the size of argTypes.
Definition at line 395 of file Builders.cpp.
References mlir::Block::addArguments(), mlir::Region::end(), mlir::Region::getBlocks(), mlir::OpBuilder::Listener::notifyBlockCreated(), and setInsertionPointToEnd().
Referenced by addAtomicRMW(), buildGenericRegion(), checkAndNestUnderRewriteOp(), createAsyncDispatchFunction(), createBinarySearchFunc(), createBlock(), createDecl(), createElementIPowIFunc(), createParallelComputeFunction(), createPartitionFunc(), createScanLoop(), ensureDistinctSuccessors(), mlir::impl::ensureRegionTerminator(), mlir::sparse_tensor::SparseTensorLoopEmitter::enterCoIterationOverTensorsAtDims(), fillStructuredOpRegion(), mlirLinalgFillBuiltinNamedOpRegion(), and mlir::outlineSingleBlockRegion().
createOrFold() [1/3]
template<typename OpTy , typename... Args> std::enable_if_t<OpTy::template hasTrait<OpTrait::OneResult>), Value> mlir::OpBuilder::createOrFold (Location location, Args &&... args) inline
Overload to create or fold a single result operation.
Definition at line 491 of file Builders.h.
createOrFold() [2/3]
template<typename OpTy , typename... Args> std::enable_if_t<OpTy::template hasTrait<OpTrait::ZeroResults>), OpTy> mlir::OpBuilder::createOrFold (Location location, Args &&... args) inline
Overload to create or fold a zero result operation.
Definition at line 500 of file Builders.h.
References tryFold().
createOrFold() [3/3]
template<typename OpTy , typename... Args> void mlir::OpBuilder::createOrFold (SmallVectorImpl< Value > & results, Location location, Args &&... args) inline
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
This functions populates 'results' with the results after folding the operation.
Definition at line 472 of file Builders.h.
References mlir::Operation::create(), mlir::Operation::destroy(), mlir::Location::getContext(), insert(), mlir::succeeded(), and tryFold().
Referenced by broadcastIfNeeded(), mlir::tensor::bubbleUpPadSlice(), buildLoopIterationCount(), mlir::bufferization::castOrReallocMemRefValue(), convertIntrinsicResult(), mlir::tensor::createCanonicalRankReducingExtractSliceOp(), mlir::tensor::createCanonicalRankReducingInsertSliceOp(), mlir::tensor::createDimValues(), createFoldedComposedAffineApply(), createI32Constant(), mlir::vector::createOrFoldDimOp(), createOrFoldDimOp(), mlir::linalg::createOrFoldDimOp(), mlir::tensor::createPadHighOp(), doubleBuffer(), getCollapsedOutputDimFromInputShape(), getShapeDimSize(), mlir::makeComposedAffineMin(), mlir::linalg::GeneralizePadOpPattern::matchAndRewrite(), mfmaConcatIfNeeded(), peelForLoop(), permuteVectorOffset(), mlir::linalg::promoteSubviewAsNewBuffer(), and mlir::scf::tileReductionUsingScf().
getBlock()
Block* mlir::OpBuilder::getBlock () const inline
Returns the current block of the builder.
Definition at line 400 of file Builders.h.
Referenced by mlir::sparse_tensor::createFuncCall().
getInsertionBlock()
Block* mlir::OpBuilder::getInsertionBlock () const inline
Return the block the current insertion point belongs to.
Note that the the insertion point is not necessarily the end of the block.
Definition at line 394 of file Builders.h.
Referenced by mlir::affineParallelize(), buildUnresolvedArgumentMaterialization(), checkAndNestUnderRewriteOp(), mlir::LLVM::createGlobalString(), finalizeWhileOp(), mlir::OperationFolder::getOrCreateConstant(), and saveInsertionPoint().
getInsertionPoint()
Block::iterator mlir::OpBuilder::getInsertionPoint () const inline
Returns the current insertion point of the builder.
Definition at line 397 of file Builders.h.
Referenced by mlir::affineParallelize(), broadcastIfNeeded(), buildUnresolvedArgumentMaterialization(), mlir::ConvertToLLVMPattern::copyUnrankedDescriptors(), materializeConstant(), and saveInsertionPoint().
getListener()
Listener* mlir::OpBuilder::getListener () const inline
Returns the current listener of this builder, or nullptr if this builder doesn't have a listener.
Definition at line 272 of file Builders.h.
Referenced by createAsyncDispatchFunction(), mlir::LLVM::createGlobalString(), createOrFold(), createParallelComputeFunction(), getOrInsertPushConstantVariable(), and materializeConstants().
insert()
Operation * OpBuilder::insert (Operation * op)
Insert the given operation at the current insertion point and return it.
Definition at line 386 of file Builders.cpp.
References mlir::Block::getOperations(), and mlir::OpBuilder::Listener::notifyOperationInserted().
Referenced by clone(), cloneWithoutRegions(), mlir::spirv::combine(), create(), mlir::OperationFolder::create(), createOrFold(), mlir::impl::ensureRegionTerminator(), and tryFold().
restoreInsertionPoint()
void mlir::OpBuilder::restoreInsertionPoint (InsertPoint ip) inline
Restore the insert point to a previously saved point.
Definition at line 342 of file Builders.h.
References clearInsertionPoint(), mlir::OpBuilder::InsertPoint::getBlock(), mlir::OpBuilder::InsertPoint::getPoint(), mlir::OpBuilder::InsertPoint::isSet(), and setInsertionPoint().
Referenced by mlir::OpBuilder::InsertionGuard::~InsertionGuard().
saveInsertionPoint()
InsertPoint mlir::OpBuilder::saveInsertionPoint () const inline
Return a saved insertion point.
Definition at line 337 of file Builders.h.
References getInsertionBlock(), and getInsertionPoint().
Referenced by mlir::linalg::tileReductionUsingForeachThread(), and tileToForeachThreadOpImpl().
setInsertionPoint() [1/2]
void mlir::OpBuilder::setInsertionPoint (Block * block, Block::iterator insertPoint) inline
Set the insertion point to the specified location.
Definition at line 350 of file Builders.h.
Referenced by mlir::bufferization::func_ext::FuncOpInterface::bufferize(), canonicalizeMinMaxOp(), cloneAndFuseFirstUse(), collapseGenericOpIterationDims(), createDecl(), createGlobalVarForEntryPointArgument(), declareReduction(), mlir::bufferization::dropEquivalentBufferResults(), mlir::bufferization::eliminateEmptyTensors(), mlir::linalg::fuseProducerOfBuffer(), mlir::linalg::fuseProducerOfTensor(), fuseWithReshapeByExpansion(), generateGpuBlockIds(), generateTileLoopNest(), getGenericOpLoopRange(), getLibraryCallSymbolRef(), getMangledSortHelperFunc(), mlir::OperationFolder::getOrCreateConstant(), mlir::tensor::getOrCreateDestination(), mlir::linalg::hoistPaddingOnTensors(), inlineIfCase(), inlineWhileCase(), mlir::bufferization::insertTensorCopies(), mlir::linalg::interchangeGenericOp(), legalizeUnresolvedMaterialization(), mlir::loopUnrollByFactor(), mlir::scf::lowerToLoopsUsingSCFForOp(), mlir::transform::gpu::mapNestedForeachToThreadsImpl(), AllocaScopeHoister::matchAndRewrite(), MultiBlockExecuteInliner::matchAndRewrite(), mlir::PatternApplicator::matchAndRewrite(), moveRegionToNewWarpOpAndReplaceReturns(), mlir::memref::multiBuffer(), OpBuilder(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), mlir::outlineSingleBlockRegion(), peelForLoop(), processParallelLoop(), replaceForOpWithNewSignature(), mlir::replaceForOpWithNewYields(), mlir::replaceLoopWithNewYields(), replaceSCFOutputValue(), replaceUnitDimIndexOps(), replaceUsesAndPropagateType(), resolveUsesInRepetitiveRegions(), restoreInsertionPoint(), rewrite(), PadOpVectorizationWithInsertSlicePattern::rewriteUser(), PadOpVectorizationWithTransferWritePattern::rewriteUser(), setInsertionPoint(), setInsertionPointAfter(), setInsertionPointToEnd(), setInsertionPointToStart(), mlir::vector::splitFullAndPartialTransfer(), mlir::linalg::splitReduction(), mlir::linalg::splitReductionByScaling(), tileAndFuseFirstExtractUse(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), mlir::scf::tileConsumerAndFuseProducerGreedilyUsingSCFForOp(), tileLinalgOpImpl(), tilePadOp(), mlir::linalg::tileReductionUsingForeachThread(), mlir::scf::tileReductionUsingScf(), tileToForeachThreadOpImpl(), mlir::transform::tileToForeachThreadOpImpl(), mlir::scf::tileUsingSCFForOp(), and wrapInExecuteRegion().
setInsertionPoint() [2/2]
void mlir::OpBuilder::setInsertionPoint (Operation * op) inline
Sets the insertion point to the specified operation, which will cause subsequent insertions to go right before it.
Definition at line 358 of file Builders.h.
References mlir::Operation::getBlock(), and setInsertionPoint().
setInsertionPointAfter()
void mlir::OpBuilder::setInsertionPointAfter (Operation * op) inline
Sets the insertion point to the node after the specified operation, which will cause subsequent insertions to go right after it.
Definition at line 364 of file Builders.h.
References mlir::Operation::getBlock(), and setInsertionPoint().
Referenced by convertCtlzOp(), createAsyncDispatchFunction(), createBinarySearchFunc(), createCompareFuncImplementation(), createLessThanCompare(), createPartitionFunc(), createScanLoop(), createSortNonstableFunc(), createSortStableFunc(), doubleBuffer(), dropRefIfNoUses(), finalizeWhileOp(), mlir::linalg::TileLoopNest::fuseProducer(), getTiledProducer(), hoistAffineIfOp(), mlir::inlineCall(), mlir::loopUnrollJamByFactor(), mlir::linalg::offsetIndices(), peelForLoop(), promoteSubViews(), mlir::bufferization::replaceOpWithBufferizedValues(), replaceSCFOutputValue(), mlir::scf::ForLoopPipeliningPattern::returningMatchAndRewrite(), mlir::linalg::rewriteAsPaddedOp(), setInsertionPointAfter(), setInsertionPointAfterValue(), mlir::linalg::tileReductionUsingForeachThread(), mlir::scf::tileReductionUsingScf(), mlir::scf::tileUsingSCFForOp(), and updateExpandedGenericOpRegion().
setInsertionPointAfterValue()
void mlir::OpBuilder::setInsertionPointAfterValue (Value val) inline
Sets the insertion point to the node after the specified value.
If value has a defining operation, sets the insertion point to the node after such defining operation. This will cause subsequent insertions to go right after it. Otherwise, value is a BlockArgument. Sets the insertion point to the start of its block.
Definition at line 373 of file Builders.h.
References mlir::Value::cast(), mlir::Value::getDefiningOp(), setInsertionPointAfter(), and setInsertionPointToStart().
Referenced by legalizeUnresolvedMaterialization().
setInsertionPointToEnd()
void mlir::OpBuilder::setInsertionPointToEnd (Block * block) inline
Sets the insertion point to the end of the specified block.
Definition at line 388 of file Builders.h.
References mlir::Block::end(), and setInsertionPoint().
Referenced by addAtomicRMW(), mlir::scf::buildLoopNest(), createAsyncDispatchFunction(), createBinarySearchFunc(), createBlock(), createDecl(), createElementIPowIFunc(), createGpuLaunch(), createParallelComputeFunction(), createPartitionFunc(), createScanLoop(), mlir::impl::ensureRegionTerminator(), finalizeWhileOp(), mlir::linalg::hoistPaddingOnTensors(), lowerEntryPointABIAttr(), mlir::linalg::makeTransposeOp(), AssertOpLowering::matchAndRewrite(), MultiBlockExecuteInliner::matchAndRewrite(), outlineKernelFuncImpl(), mlir::outlineSingleBlockRegion(), mlir::replaceLoopWithNewYields(), mlir::linalg::tileReductionUsingForeachThread(), and tileToForeachThreadOpImpl().
setInsertionPointToStart()
void mlir::OpBuilder::setInsertionPointToStart (Block * block) inline
Sets the insertion point to the start of the specified block.
Definition at line 383 of file Builders.h.
References mlir::Block::begin(), and setInsertionPoint().
Referenced by mlir::bufferization::func_ext::FuncOpInterface::bufferize(), buildAffineLoopNestImpl(), mlir::scf::buildLoopNest(), mlir::async::cloneConstantsIntoTheRegion(), mlir::coalesceLoops(), mlir::spirv::combine(), createBinarySearchFunc(), createCompareFuncImplementation(), createEqCompare(), createLessThanCompare(), createPartitionFunc(), createSortNonstableFunc(), createSortStableFunc(), dropRefIfNoUses(), endIf(), mlir::sparse_tensor::SparseTensorLoopEmitter::enterCoIterationOverTensorsAtDims(), mlir::sparse_tensor::SparseTensorLoopEmitter::enterLoopOverTensorAtDim(), fillStructuredOpRegion(), fuseIfLegal(), generateCollapsedIndexingRegion(), generateFusedElementwiseOpRegion(), genIf(), mlir::sparse_tensor::genValueForDense(), getOrDefineFunction(), getOrInsertBuiltinVariable(), mlir::linalg::hoistPaddingOnTensors(), injectGpuIndexOperations(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::GPUPrintfOpToLLVMCallLowering::matchAndRewrite(), FoldLaunchArguments::matchAndRewrite(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::normalizeAffineFor(), mlir::outlineSingleBlockRegion(), processParallelLoop(), setInsertionPointAfter(), setInsertionPointAfterValue(), mlir::linalg::LinalgTilingOptions::setTileSizes(), mlir::scf::SCFTilingOptions::setTileSizes(), mlir::vector::splitFullAndPartialTransfer(), mlir::scf::tileParallelLoop(), mlir::linalg::tileReductionUsingForeachThread(), tileToForeachThreadOpImpl(), wrapExternalFunction(), wrapForExternalCallers(), and wrapInExecuteRegion().
setListener()
void mlir::OpBuilder::setListener (Listener * newListener) inline
Sets the listener of this builder to the one provided.
Definition at line 268 of file Builders.h.
Referenced by createOrFold(), materializeConstants(), and mlir::RewriterBase::RewriterBase().
tryFold()
LogicalResult OpBuilder::tryFold (Operation * op, SmallVectorImpl< Value > & results)
Attempts to fold the given operation and places new results within 'results'.
Returns success if the operation was folded, failure otherwise. Note: This function does not erase the operation on a successful fold.
Definition at line 440 of file Builders.cpp.
References mlir::Builder::context, mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Operation::fold(), mlir::Operation::getDialect(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Operation::getResults(), mlir::ResultRange::getTypes(), insert(), mlir::m_Constant(), mlir::matchPattern(), mlir::Dialect::materializeConstant(), mlir::success(), and value.
Referenced by createOrFold().
The documentation for this class was generated from the following files:
include/mlir/IR/Builders.h
lib/IR/Builders.cpp