MLIR: mlir::Operation Class Reference
mlir::Operation Class Reference final
Operation is a basic unit of execution within MLIR.
#include "mlir/IR/Operation.h"
Classes
class CloneOptions
Class encompassing various options related to cloning an operation.
class dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
Public Types
using operand_range = OperandRange
using operand_iterator = operand_range::iterator
using operand_type_iterator = operand_range::type_iterator
using operand_type_range = operand_range::type_range
using result_range = ResultRange
Support result iteration.
using result_iterator = result_range::iterator
using result_type_iterator = result_range::type_iterator
Support result type iteration.
using result_type_range = result_range::type_range
using dialect_attr_range = iterator_range< dialect_attr_iterator >
using succ_iterator = SuccessorRange::iterator
using use_iterator = result_range::use_iterator
using use_range = result_range::use_range
using user_iterator = ValueUserIterator< use_iterator, OpOperand >
using user_range = iterator_range< user_iterator >
Public Member Functions
OperationName getName ()
The name of an operation is the key identifier for it.
Optional< RegisteredOperationName > getRegisteredInfo ()
If this operation has a registered operation description, return it.
bool isRegistered ()
Returns true if this operation has a registered operation description, otherwise false.
void erase ()
Remove this operation from its parent block and delete it.
void remove ()
Remove the operation from its parent block, but don't delete it.
Operation * clone (BlockAndValueMapping &mapper, CloneOptions options=CloneOptions::all())
Create a deep copy of this operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Operation * clone (CloneOptions options=CloneOptions::all())
Operation * cloneWithoutRegions (BlockAndValueMapping &mapper)
Create a partial copy of this operation without traversing into attached regions.
Operation * cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Block * getBlock ()
Returns the operation block that contains this operation.
MLIRContext * getContext ()
Return the context this operation is associated with.
Dialect * getDialect ()
Return the dialect this operation is associated with, or nullptr if the associated dialect is not loaded.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
Set the source location the operation was defined or derived from.
Region * getParentRegion ()
Returns the region to which the instruction belongs.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy >
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
template<template< typename T > class Trait>
Operation * getParentWithTrait ()
Returns the closest surrounding parent operation with trait Trait.
bool isProperAncestor (Operation *other)
Return true if this operation is a proper ancestor of the other operation.
bool isAncestor (Operation *other)
Return true if this operation is an ancestor of the other operation.
void replaceUsesOfWith (Value from, Value to)
Replace any uses of 'from' with 'to' within this operation.
template<typename ValuesT >
void replaceAllUsesWith (ValuesT &&values)
Replace all uses of results of this operation with the provided 'values'.
void destroy ()
Destroys this operation and its subclass data.
void dropAllReferences ()
This drops all operand uses from this operation, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
void dropAllDefinedValueUses ()
Drop uses of all values defined by this operation or its nested regions.
void moveBefore (Operation *existingOp)
Unlink this operation from its current block and insert it right before existingOp which may be in the same or another block in the same function.
void moveBefore (Block *block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right before iterator in the specified block.
void moveAfter (Operation *existingOp)
Unlink this operation from its current block and insert it right after existingOp which may be in the same or another block in the same function.
void moveAfter (Block *block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right after iterator in the specified block.
bool isBeforeInBlock (Operation *other)
Given an operation 'other' that is within the same parent block, return whether the current operation is before 'other' in the operation list of the parent block.
void print (raw_ostream &os, const OpPrintingFlags &flags=llvm::None)
void print (raw_ostream &os, AsmState &state)
void dump ()
void setOperands (ValueRange operands)
Replace the current operands of this operation with the ones provided in 'operands'.
void setOperands (unsigned start, unsigned length, ValueRange operands)
Replace the operands beginning at 'start' and ending at 'start' + 'length' with the ones provided in 'operands'.
void insertOperands (unsigned index, ValueRange operands)
Insert the given operands into the operand list at the given 'index'.
unsigned getNumOperands ()
Value getOperand (unsigned idx)
void setOperand (unsigned idx, Value value)
void eraseOperand (unsigned idx)
Erase the operand at position idx.
void eraseOperands (unsigned idx, unsigned length=1)
Erase the operands starting at position idx and ending at position 'idx'+'length'.
void eraseOperands (const BitVector &eraseIndices)
Erases the operands that have their corresponding bit set in eraseIndices and removes them from the operand list.
operand_iterator operand_begin ()
operand_iterator operand_end ()
operand_range getOperands ()
Returns an iterator on the underlying Value's.
MutableArrayRef< OpOperand > getOpOperands ()
OpOperand & getOpOperand (unsigned idx)
operand_type_iterator operand_type_begin ()
operand_type_iterator operand_type_end ()
operand_type_range getOperandTypes ()
unsigned getNumResults ()
Return the number of results held by this operation.
OpResult getResult (unsigned idx)
Get the 'idx'th result of this operation.
result_iterator result_begin ()
result_iterator result_end ()
result_range getResults ()
result_range getOpResults ()
OpResult getOpResult (unsigned idx)
result_type_iterator result_type_begin ()
result_type_iterator result_type_end ()
result_type_range getResultTypes ()
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
DictionaryAttr getAttrDictionary ()
Return all of the attributes on this operation as a DictionaryAttr.
void setAttrs (DictionaryAttr newAttrs)
Set the attribute dictionary on this operation.
void setAttrs (ArrayRef< NamedAttribute > newAttrs)
Attribute getAttr (StringAttr name)
Return the specified attribute if present, null otherwise.
Attribute getAttr (StringRef name)
template<typename AttrClass >
AttrClass getAttrOfType (StringAttr name)
template<typename AttrClass >
AttrClass getAttrOfType (StringRef name)
bool hasAttr (StringAttr name)
Return true if the operation has an attribute with the provided name, false otherwise.
bool hasAttr (StringRef name)
template<typename AttrClass , typename NameT >
bool hasAttrOfType (NameT &&name)
void setAttr (StringAttr name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
Attribute removeAttr (StringAttr name)
Remove the attribute with the specified name if it exists.
Attribute removeAttr (StringRef name)
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
template<typename DialectAttrT >
void setDialectAttrs (DialectAttrT &&dialectAttrs)
Set the dialect attributes for this operation, and preserve all dependent.
void populateDefaultAttrs ()
Sets default attributes on unset attributes.
unsigned getNumRegions ()
Returns the number of regions held by this operation.
MutableArrayRef< Region > getRegions ()
Returns the regions held by this operation.
Region & getRegion (unsigned index)
Returns the region held by this operation at position 'index'.
MutableArrayRef< BlockOperand > getBlockOperands ()
succ_iterator successor_begin ()
succ_iterator successor_end ()
SuccessorRange getSuccessors ()
bool hasSuccessors ()
unsigned getNumSuccessors ()
Block * getSuccessor (unsigned index)
void setSuccessor (Block *block, unsigned index)
LogicalResult fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
Attempt to fold this operation with the specified constant operand values.
template<template< typename T > class Trait>
bool hasTrait ()
Returns true if the operation was registered with a particular trait, e.g.
template<template< typename T > class Trait>
bool mightHaveTrait ()
Returns true if the operation might have the provided trait.
template<WalkOrder Order = WalkOrder::PostOrder, typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==1, RetT > walk (FnT &&callback)
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if_t< llvm::function_traits< std::decay_t< FnT > >::num_args==2, RetT > walk (FnT &&callback)
Generic walker with a stage aware callback.
void dropAllUses ()
Drop all uses of results of this operation.
use_iterator use_begin ()
use_iterator use_end ()
use_range getUses ()
Returns a range of all uses, which is useful for iterating over all uses.
bool hasOneUse ()
Returns true if this operation has exactly one use.
bool use_empty ()
Returns true if this operation has no uses.
bool isUsedOutsideOfBlock (Block *block)
Returns true if the results of this operation are used outside of the given block.
user_iterator user_begin ()
user_iterator user_end ()
user_range getUsers ()
Returns a range of all users.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
Static Public Member Functions
static Operation * create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList &&attributes, BlockRange successors, unsigned numRegions)
Create a new Operation with the specific fields.
static Operation * create (const OperationState &state)
Create a new Operation from the fields stored in state.
static Operation * create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList &&attributes, BlockRange successors={}, RegionRange regions={})
Create a new Operation with the specific fields.
Friends
struct llvm::ilist_traits< Operation >
class Block
class Value
class llvm::ilist_node_with_parent< Operation, Block >
Detailed Description
Operation is a basic unit of execution within MLIR.
Operations can be nested within Regions held by other operations effectively forming a tree. Child operations are organized into operation blocks represented by a 'Block' class.
Definition at line 28 of file Operation.h.
Member Typedef Documentation
dialect_attr_range
using mlir::Operation::dialect_attr_range = iterator_range<dialect_attr_iterator>
Definition at line 435 of file Operation.h.
operand_iterator
using mlir::Operation::operand_iterator = operand_range::iterator
Definition at line 289 of file Operation.h.
operand_range
using mlir::Operation::operand_range = OperandRange
Definition at line 288 of file Operation.h.
operand_type_iterator
using mlir::Operation::operand_type_iterator = operand_range::type_iterator
Definition at line 310 of file Operation.h.
operand_type_range
using mlir::Operation::operand_type_range = operand_range::type_range
Definition at line 311 of file Operation.h.
result_iterator
using mlir::Operation::result_iterator = result_range::iterator
Definition at line 328 of file Operation.h.
result_range
using mlir::Operation::result_range = ResultRange
Support result iteration.
Definition at line 327 of file Operation.h.
result_type_iterator
using mlir::Operation::result_type_iterator = result_range::type_iterator
Support result type iteration.
Definition at line 341 of file Operation.h.
result_type_range
using mlir::Operation::result_type_range = result_range::type_range
Definition at line 342 of file Operation.h.
succ_iterator
using mlir::Operation::succ_iterator = SuccessorRange::iterator
Definition at line 500 of file Operation.h.
use_iterator
using mlir::Operation::use_iterator = result_range::use_iterator
Definition at line 616 of file Operation.h.
use_range
using mlir::Operation::use_range = result_range::use_range
Definition at line 617 of file Operation.h.
user_iterator
using mlir::Operation::user_iterator = ValueUserIterator<use_iterator, OpOperand>
Definition at line 643 of file Operation.h.
user_range
using mlir::Operation::user_range = iterator_range<user_iterator>
Definition at line 644 of file Operation.h.
Member Function Documentation
clone() [1/2]
Operation * Operation::clone (BlockAndValueMapping & mapper, CloneOptions options = CloneOptions::all())
Create a deep copy of this operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Replaces references to cloned sub-operations to the corresponding operation that is copied, and adds those mappings to the map. Optionally, one may configure what parts of the operation to clone using the options parameter.
Calling this method from multiple threads is generally safe if through the process of cloning no new uses of 'Value's from outside the operation are created. Cloning an isolated-from-above operation with no operands, such as top level function operations, is therefore always safe. Using the mapper, it is possible to avoid adding uses to outside operands by remapping them to 'Value's owned by the caller thread.
Replaces references to cloned sub-operations to the corresponding operation that is copied, and adds those mappings to the map.
Definition at line 558 of file Operation.cpp.
References mlir::Region::cloneInto(), create(), getLoc(), getName(), getNumOperands(), getNumRegions(), getNumResults(), getNumSuccessors(), getOperands(), getRegion(), getResult(), getResultTypes(), getSuccessors(), mlir::BlockAndValueMapping::lookupOrDefault(), mlir::BlockAndValueMapping::map(), and options.
Referenced by clone(), mlir::OpBuilder::clone(), cloneWithoutRegions(), fuse(), generateUnrolledLoop(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), and mlir::linalg::splitReductionByScaling().
clone() [2/2]
Operation * Operation::clone (CloneOptions options = CloneOptions::all())
Definition at line 592 of file Operation.cpp.
References clone(), and options.
cloneWithoutRegions() [1/2]
Operation * Operation::cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
The new operation will have the same number of regions as the original one, but they will be left empty.
Definition at line 548 of file Operation.cpp.
cloneWithoutRegions() [2/2]
Operation * Operation::cloneWithoutRegions (BlockAndValueMapping & mapper)
Create a partial copy of this operation without traversing into attached regions.
Create a deep copy of this operation but keep the operation regions empty.
The new operation will have the same number of regions as the original one, but they will be left empty. Operands are remapped using mapper (if present), and mapper is updated to contain the results.
Operands are remapped using mapper (if present), and mapper is updated to contain the results. The mapResults flag specifies whether the results of the cloned operation should be added to the map.
Definition at line 544 of file Operation.cpp.
References mlir::Operation::CloneOptions::all(), and clone().
Referenced by mlir::OpBuilder::cloneWithoutRegions().
create() [1/3]
Operation * Operation::create (const OperationState & state) static
Create a new Operation from the fields stored in state.
Create a new Operation from operation state.
Definition at line 27 of file Operation.cpp.
References mlir::OperationState::attributes, create(), mlir::OperationState::getContext(), mlir::NamedAttrList::getDictionary(), mlir::OperationState::location, mlir::OperationState::name, mlir::OperationState::operands, mlir::OperationState::regions, mlir::OperationState::successors, and mlir::OperationState::types.
create() [2/3]
Operation * Operation::create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList && attributes, BlockRange successors, unsigned numRegions) static
Create a new Operation with the specific fields.
Overload of create that takes an existing DictionaryAttr to avoid unnecessarily uniquing a list of attributes.
Definition at line 49 of file Operation.cpp.
References getBlockOperands(), mlir::Location::getContext(), getRegion(), mlir::OperationName::getRegisteredInfo(), mlir::OperationName::hasTrait(), and mightHaveTrait().
Referenced by clone(), mlir::OpBuilder::create(), create(), mlir::OperationFolder::create(), mlir::OpBuilder::createOrFold(), mlir::spirv::Deserializer::processOp< spirv::GenericCastToPtrExplicitOp >(), mlirOperationCreate(), updateReturnOps(), and widenOp().
create() [3/3]
Operation * Operation::create (Location location, OperationName name, TypeRange resultTypes, ValueRange operands, NamedAttrList && attributes, BlockRange successors = {}, RegionRange regions = {}) static
Create a new Operation with the specific fields.
Definition at line 34 of file Operation.cpp.
References create(), getRegion(), and mlir::Region::takeBody().
destroy()
void Operation::destroy ()
Destroys this operation and its subclass data.
Destroy this operation or one of its subclasses.
Definition at line 165 of file Operation.cpp.
Referenced by mlir::OperationFolder::create(), mlir::OpBuilder::createOrFold(), llvm::ilist_traits<::mlir::Operation >::deleteNode(), and erase().
dialect_attr_begin()
dialect_attr_iterator mlir::Operation::dialect_attr_begin () inline
Definition at line 443 of file Operation.h.
References getAttrs().
dialect_attr_end()
dialect_attr_iterator mlir::Operation::dialect_attr_end () inline
Definition at line 447 of file Operation.h.
References getAttrs().
dropAllDefinedValueUses()
void Operation::dropAllDefinedValueUses ()
Drop uses of all values defined by this operation or its nested regions.
This drops all uses of any values defined by this operation or its nested regions, wherever they are located.
Definition at line 476 of file Operation.cpp.
References mlir::Block::dropAllDefinedValueUses(), dropAllUses(), and getRegions().
dropAllReferences()
void Operation::dropAllReferences ()
This drops all operand uses from this operation, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
Definition at line 463 of file Operation.cpp.
References getBlockOperands(), getOpOperands(), and getRegions().
Referenced by mlir::Block::dropAllReferences().
dropAllUses()
void mlir::Operation::dropAllUses () inline
Drop all uses of results of this operation.
Definition at line 611 of file Operation.h.
References getOpResults().
Referenced by detachNestedAndErase(), and dropAllDefinedValueUses().
dump()
void Operation::dump ()
Definition at line 3505 of file AsmPrinter.cpp.
References print().
Referenced by mlir::checkMemrefAccessDependence(), checkTilingLegalityImpl(), mlir::OpState::dump(), and logSucessfulPatternApplication().
emitError()
InFlightDiagnostic Operation::emitError (const Twine & message = {})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 225 of file Operation.cpp.
References diag(), mlir::emitError(), getContext(), and getLoc().
Referenced by mlir::affineDataCopyGenerate(), applyTilingToAll(), assertDestinationPassingStyle(), mlir::bufferization::bufferizeOp(), checkAffineLoopNestMappableImpl(), checkAndUpdateCapabilityRequirements(), checkAndUpdateExtensionRequirements(), mlir::MemRefRegion::compute(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpThreadprivate(), mlir::convertVectorToNVVMCompatibleMMASync(), mlir::bufferization::deallocateBuffers(), mlir::bufferization::detail::defaultGetBufferType(), diagnoseInvalidOperandDominance(), emitOpError(), generateLocationsFromIR(), mlir::bufferization::getBufferType(), getMemoryFootprintBytes(), mlir::spirv::getPushConstantValue(), mlir::nvgpu::getWarpMatrixInfo(), mlir::insertBackwardComputationSlice(), printOperation(), mlir::detail::verifyBranchSuccessorOperands(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::detail::verifyDataLayoutOp(), verifyFuncOpInterfaceStructAttr(), verifyMemorySemantics(), verifyMmaSyncOp(), mlir::detail::verifyParallelCombiningOpInterface(), verifyPointerAndCoopMatrixType(), verifyPointerAndJointMatrixType(), mlir::detail::verifyShapedDimOpInterface(), verifyShiftOp(), mlir::detail::verifySymbolTable(), verifyTerminatorSuccessors(), mlir::transform::TransformEachOpTrait< OpTy >::verifyTrait(), mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::NavigationTransformOpTrait< OpTy >::verifyTrait(), and walkReferenceCountedValues().
emitOpError()
InFlightDiagnostic Operation::emitOpError (const Twine & message = {})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
Definition at line 512 of file Operation.cpp.
References emitError(), and getName().
Referenced by printOperation(), processOperands(), verifyAlignedClause(), mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::OpTrait::impl::verifyAtLeastNRegions(), mlir::OpTrait::impl::verifyAtLeastNResults(), mlir::OpTrait::impl::verifyAtLeastNSuccessors(), verifyAtomicUpdateOp(), verifyAttributions(), mlir::impl::verifyCastInterfaceOp(), verifyCastOp(), verifyCollapsedShape(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::detail::verifyDestinationStyleOpInterface(), mlir::OpTrait::impl::verifyElementwise(), verifyGatherOrScatterDims(), verifyGroupNonUniformArithmeticOp(), verifyHasBindingUse(), mlir::OpTrait::impl::verifyIsTerminator(), verifyMemoryOpIndexing(), verifyMmaSyncOp(), verifyMultShape(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::OpTrait::impl::verifyNRegions(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyNSuccessors(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOneRegion(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyOneSuccessor(), verifyOpaquePtr(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), verifyOpMetadata(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), verifyReductionVarList(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShapeOrExtentTensorOp(), verifySizeOrIndexOp(), mlir::linalg::detail::verifyStructuredOpInterface(), mlir::detail::verifySymbol(), verifySymbolAttribute(), verifySymbolAttrUse(), mlir::detail::verifySymbolTable(), verifySynchronizationHint(), verifyTileSize(), mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait(), mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::verifyTrait(), verifyTypesAlongAllEdges(), mlir::OpTrait::impl::verifyValueSizeAttr(), verifyVectorMemoryOp(), mlir::OpTrait::impl::verifyZeroOperands(), mlir::OpTrait::impl::verifyZeroRegions(), mlir::OpTrait::impl::verifyZeroResults(), and mlir::OpTrait::impl::verifyZeroSuccessors().
emitRemark()
InFlightDiagnostic Operation::emitRemark (const Twine & message = {})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 246 of file Operation.cpp.
References diag(), mlir::emitRemark(), getContext(), and getLoc().
Referenced by emitRemarkForBlock().
emitWarning()
InFlightDiagnostic Operation::emitWarning (const Twine & message = {})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
Definition at line 237 of file Operation.cpp.
References diag(), mlir::emitWarning(), getContext(), and getLoc().
Referenced by mlir::affineDataCopyGenerate(), getLibraryCallSymbolRef(), and getMemoryFootprintBytes().
erase()
void Operation::erase ()
Remove this operation from its parent block and delete it.
Remove this operation (and its descendants) from its Block and delete all of them.
Definition at line 418 of file Operation.cpp.
References destroy(), and getBlock().
Referenced by mlir::affineScalarReplace(), mlir::collapseParallelLoops(), convertTransferWriteOp(), convertTransferWriteToStores(), convertYieldOp(), createMask(), detachNestedAndErase(), mlir::OpState::erase(), mlir::SymbolTable::erase(), mlir::RewriterBase::eraseOp(), fuseIfLegal(), mlir::OperationFolder::insertKnownConstant(), mlir::normalizeMemRef(), outlineKernelFuncImpl(), mlir::replaceAllMemRefUsesWith(), replaceForOpWithNewSignature(), mlir::replaceForOpWithNewYields(), mlir::RewriterBase::replaceOp(), specializeForLoopForUnrolling(), specializeParallelLoopForUnrolling(), mlir::OpBuilder::tryFold(), mlir::OperationFolder::tryToFold(), updateReturnOps(), and mlir::detail::RecoveryReproducerContext::~RecoveryReproducerContext().
eraseOperand()
void mlir::Operation::eraseOperand (unsigned idx) inline
Erase the operand at position idx.
Definition at line 273 of file Operation.h.
References eraseOperands().
eraseOperands() [1/2]
void mlir::Operation::eraseOperands (const BitVector & eraseIndices) inline
Erases the operands that have their corresponding bit set in eraseIndices and removes them from the operand list.
Definition at line 283 of file Operation.h.
References mlir::detail::OperandStorage::eraseOperands().
eraseOperands() [2/2]
void mlir::Operation::eraseOperands (unsigned idx, unsigned length = 1) inline
Erase the operands starting at position idx and ending at position 'idx'+'length'.
Definition at line 277 of file Operation.h.
References mlir::detail::OperandStorage::eraseOperands().
Referenced by mlir::MutableOperandRange::clear(), mlir::MutableOperandRange::erase(), and eraseOperand().
fold()
LogicalResult Operation::fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > & results)
Attempt to fold this operation with the specified constant operand values.
Attempt to fold this operation using the Op's registered foldHook.
the elements in "operands" will correspond directly to the operands of the operation, but may be null if non-constant. If folding is successful, this fills in the results vector. If not, results is unspecified.
Definition at line 490 of file Operation.cpp.
References mlir::failure(), getDialect(), getRegisteredInfo(), mlir::succeeded(), and mlir::success().
Referenced by mlir::detail::constant_op_binder< AttrT >::match(), mlir::OpBuilder::tryFold(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
getAttr() [1/2]
Attribute mlir::Operation::getAttr (StringAttr name) inline
Return the specified attribute if present, null otherwise.
Definition at line 371 of file Operation.h.
Referenced by createConstFromIntAttribute(), createLinalgBodyCalculationForElementwiseOp(), mlir::LLVM::detail::DebugTranslation::DebugTranslation(), getAttrOfType(), lookupSymbolInImpl(), prepareLLVMModule(), setInPlaceOpOperand(), setLoopMetadata(), mlir::bufferization::shouldDeallocateOpResult(), mlir::detail::verifySymbol(), and verifySymbolAttribute().
getAttr() [2/2]
Attribute mlir::Operation::getAttr (StringRef name) inline
Definition at line 372 of file Operation.h.
getAttrDictionary()
DictionaryAttr mlir::Operation::getAttrDictionary () inline
Return all of the attributes on this operation as a DictionaryAttr.
Definition at line 359 of file Operation.h.
Referenced by mlir::OperationEquivalence::computeHash(), mlir::OperationFingerPrint::OperationFingerPrint(), populateDefaultAttrs(), mlir::AttrTypeReplacer::replaceElementsIn(), mlir::detail::verifyInferredResultTypes(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and walkSymbolRefs().
getAttrOfType() [1/2]
template<typename AttrClass > AttrClass mlir::Operation::getAttrOfType (StringAttr name) inline
Definition at line 375 of file Operation.h.
References mlir::Attribute::dyn_cast_or_null(), and getAttr().
Referenced by mlir::bufferization::allocationDoesNotEscape(), convertOperationImpl(), mlir::function_interface_impl::eraseFunctionArguments(), mlir::function_interface_impl::eraseFunctionResults(), executeGetOperandsResults(), mlir::function_interface_impl::getArgAttrDict(), mlir::impl::getDataLayoutSpec(), getNameIfSymbol(), mlir::function_interface_impl::getResultAttrDict(), mlir::SymbolTable::getSymbolVisibility(), mlir::function_interface_impl::insertFunctionArguments(), mlir::function_interface_impl::insertFunctionResults(), mlir::spirv::lookupEntryPointABI(), mlir::spirv::lookupTargetEnv(), printAtomicUpdateOp(), mlir::function_interface_impl::printFunctionSignature(), printGroupNonUniformArithmeticOp(), printIR(), printVariableDecorations(), mlir::LLVM::ModuleTranslation::setAccessGroupsMetadata(), mlir::LLVM::ModuleTranslation::setAliasScopeMetadata(), mlir::function_interface_impl::detail::setArgResAttrDict(), mlir::function_interface_impl::setFunctionType(), verifyAtomicUpdateOp(), verifyGroupNonUniformArithmeticOp(), mlir::detail::verifySymbol(), mlir::detail::verifySymbolTable(), and mlir::OpTrait::impl::verifyValueSizeAttr().
getAttrOfType() [2/2]
template<typename AttrClass > AttrClass mlir::Operation::getAttrOfType (StringRef name) inline
Definition at line 379 of file Operation.h.
References mlir::Attribute::dyn_cast_or_null(), and getAttr().
getAttrs()
ArrayRef<NamedAttribute> mlir::Operation::getAttrs () inline
Return all of the attributes on this operation.
Definition at line 356 of file Operation.h.
Referenced by cloneOpWithOperandsAndTypes(), dialect_attr_begin(), dialect_attr_end(), getDialectAttrs(), isLegalOp(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::function_interface_impl::printFunctionAttributes(), printNamedStructuredOp(), printOneResultOp(), printVariableDecorations(), mlir::replaceAllMemRefUsesWith(), mlir::impl::scalarizeVectorOp(), setDialectAttrs(), vectorizeOneOp(), and widenOp().
getBlock()
Block* mlir::Operation::getBlock () inline
Returns the operation block that contains this operation.
Definition at line 144 of file Operation.h.
Referenced by llvm::ilist_traits<::mlir::Operation >::addNodeToList(), mlir::detail::ConversionPatternRewriterImpl::applyRewrites(), constructTiledLoopNest(), diagnoseInvalidOperandDominance(), erase(), mlir::Region::findAncestorBlockInRegion(), findInstPosition(), mlir::generateCopyForMemRegion(), getCommonBlock(), getPhiIncomingBlock(), mlir::bufferization::BufferPlacementAllocs::getStartOperation(), mlir::hasNoInterveningEffect(), hoistAffineIfOp(), mlir::inlineRegion(), mlir::OperationFolder::insertKnownConstant(), mlir::sparse_tensor::isAdmissibleBranchExp(), mlir::Liveness::isDeadAfter(), mlir::isLegalForBranchOpInterfaceTypeConversionPattern(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), isRegionOrCallableReturn(), mlir::Value::isUsedOutsideOfBlock(), lastNonTerminatorInRegion(), mlir::linalg::PadOpTransformationPattern::matchAndRewrite(), mayExistInterleavedUses(), mlir::RewriterBase::mergeBlockBefore(), moveAfter(), moveBefore(), mlir::OperationFolder::notifyRemoval(), printIR(), mlir::DominanceInfo::properlyDominates(), mlir::PostDominanceInfo::properlyPostDominates(), remove(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OperationFolder::tryToFold(), mlir::OpTrait::impl::verifyIsTerminator(), verifyResultTypesAreInferrable(), and mlir::dataflow::DeadCodeAnalysis::visit().
getBlockOperands()
MutableArrayRef<BlockOperand> mlir::Operation::getBlockOperands () inline
Definition at line 495 of file Operation.h.
Referenced by create(), dropAllReferences(), getSuccessor(), setSuccessor(), and mlir::SuccessorRange::SuccessorRange().
getContext()
MLIRContext* mlir::Operation::getContext () inline
Return the context this operation is associated with.
Definition at line 147 of file Operation.h.
References mlir::Attribute::getContext().
Referenced by mlir::gpu::addAsyncDependency(), annotateConflict(), mlir::applyOpPatternsAndFold(), mlir::bufferization::func_ext::FuncOpInterface::bufferize(), mlir::bufferization::bufferizeOp(), collectValidReferencesFor(), diagnoseInvalidOperandDominance(), emitError(), emitRemark(), emitWarning(), generateLocationsFromIR(), mlir::getComputationSliceState(), mlir::OpState::getContext(), mlir::Region::getContext(), mlir::Pass::getContext(), mlir::LLVM::ModuleTranslation::getContext(), getLibraryCallSymbolRef(), mlir::linalg::getNeutralElement(), mlir::detail::PassCrashReproducerGenerator::initialize(), mlir::SymbolTable::insert(), mlir::bufferization::insertTensorCopies(), mlir::SymbolTable::lookup(), mlir::SymbolTable::lookupSymbolIn(), mlir::spirv::lookupTargetEnvOrDefault(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), populateDefaultAttrs(), prepareLLVMModule(), removeAttr(), resolveUsesInRepetitiveRegions(), mlir::function_interface_impl::setAllArgAttrDicts(), setAllArgResAttrDicts(), mlir::function_interface_impl::setAllResultAttrDicts(), mlir::function_interface_impl::detail::setArgResAttrDict(), setAttr(), setAttrs(), setDialectAttrs(), mlir::SymbolTable::setSymbolName(), mlir::SymbolTable::setSymbolVisibility(), mlir::SymbolTable::SymbolTable(), tryApply(), mlir::detail::verifyInferredResultTypes(), and verifyOpAndAdjustFlags().
getDialect()
Dialect* mlir::Operation::getDialect () inline
Return the dialect this operation is associated with, or nullptr if the associated dialect is not loaded.
Definition at line 151 of file Operation.h.
References mlir::OperationName::getDialect(), and getName().
Referenced by fold(), mlir::detail::DialectInterfaceCollectionBase::getInterfaceFor(), mlir::Dialect::getOperationPrinter(), mlir::OperationFolder::insertKnownConstant(), mlir::bufferization::BufferizationOptions::isOpAllowed(), isPotentiallyUnknownSymbolTable(), mlir::OpState::print(), mlir::OpBuilder::tryFold(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
getDialectAttrs()
dialect_attr_range mlir::Operation::getDialectAttrs () inline
Return a range corresponding to the dialect attributes for this operation.
Definition at line 438 of file Operation.h.
References getAttrs().
getLoc()
Location mlir::Operation::getLoc () inline
The source location the operation was defined or derived from.
Definition at line 154 of file Operation.h.
Referenced by mlir::affineDataCopyGenerate(), mlir::transform::TransformState::applyTransform(), buildMultiDimReduce(), buildVectorComparison(), canonicalizeMinMaxOp(), checkDoubleConsume(), clone(), cloneAndFuseFirstUse(), computeMemoryOpIndices(), mlir::LLVM::ModuleTranslation::convertBlock(), convertElementwiseOp(), mlir::createAffineComputationSlice(), createConstFromIntAttribute(), createLinalgBodyCalculationForElementwiseOp(), createLinalgBodyCalculationForReduceOp(), createPrivateMemRef(), createSourceLocationInfo(), diagnoseInvalidOperandDominance(), elementwiseMatchAndRewriteHelper(), emitError(), emitRemark(), emitWarning(), mlir::detail::PassCrashReproducerGenerator::finalize(), fuse(), getLibraryCallSymbolRef(), mlir::OpState::getLoc(), mlir::Region::getLoc(), getMemoryFootprintBytes(), getOrCreateOperandsMatchingResultTypes(), mlir::spirv::getPushConstantValue(), mlir::LLVM::detail::handleMultidimensionalVectors(), inlinePayload(), insertCasts(), interruptIfValidLocation(), isFusionProfitable(), legalizeUnresolvedMaterialization(), matchAndReplaceDepthwiseConv(), mlir::ConversionPattern::matchAndRewrite(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::RewriterBase::notifyMatchFailure(), mlir::LLVM::detail::oneToOneRewrite(), mlir::OperationFingerPrint::OperationFingerPrint(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), prepareLLVMModule(), printConstantOp(), printOperation(), reduceMatchAndRewriteHelper(), ReifyExpandOrCollapseShapeOp< OpTy >::reifyResultShapes(), mlir::replaceAllMemRefUsesWith(), mlir::AttrTypeReplacer::replaceElementsIn(), mlir::bufferization::replaceOpWithNewBufferizedOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::PassManager::run(), mlir::impl::scalarizeVectorOp(), mlir::vector::splitFullAndPartialTransfer(), tileAndFuseFirstExtractUse(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), mlir::OpBuilder::tryFold(), unpackPDLOperations(), vectorizeOneOp(), mlir::LLVM::detail::vectorOneToOneRewrite(), verifyAndGetTerminator(), mlir::detail::verifyDataLayoutOp(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifyIsIsolatedFromAbove(), mlir::detail::verifySymbolTable(), widenOp(), and wrapInExecuteRegion().
getName()
OperationName mlir::Operation::getName () inline
The name of an operation is the key identifier for it.
Definition at line 50 of file Operation.h.
Referenced by AncestorKey::AncestorKey(), mlir::bufferization::bufferizeOp(), checkAndUpdateCapabilityRequirements(), checkAndUpdateExtensionRequirements(), mlir::Op< ConcreteType, Traits >::classof(), clone(), cloneOpWithOperandsAndTypes(), mlir::OperationEquivalence::computeHash(), emitOpError(), mlir::ConversionPatternRewriter::eraseOp(), mlir::OpTrait::impl::foldIdempotent(), mlir::OpTrait::impl::foldInvolution(), mlir::detail::RecoveryReproducerContext::generate(), mlir::linalg::generateLibraryCallName(), getDialect(), getElementPtrType(), mlir::OpInterface< ConcreteType, Traits >::getInterfaceFor(), getRegisteredInfo(), mlir::AsmParserState::initialize(), mlir::ConversionTarget::isIllegal(), mlir::ConversionTarget::isLegal(), isRegistered(), mlir::PatternApplicator::matchAndRewrite(), mlirLinalgFillBuiltinNamedOpRegion(), mlir::ConversionPatternRewriter::notifyOperationInserted(), mlir::detail::PassCrashReproducerGenerator::prepareReproducerFor(), mlir::CallGraph::print(), printIR(), mlir::OpState::printOpName(), mlir::spirv::Serializer::printValueIDMap(), mlir::replaceAllMemRefUsesWith(), mlir::ConversionPatternRewriter::replaceOp(), mlir::ConversionPatternRewriter::replaceUsesOfBlockArgument(), mlir::PassManager::run(), mlir::impl::scalarizeVectorOp(), vectorizeOneOp(), verifyMmaSyncOp(), verifyOpAndAdjustFlags(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::transform::TransformEachOpTrait< OpTy >::verifyTrait(), mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::verifyTrait(), mlir::transform::NavigationTransformOpTrait< OpTy >::verifyTrait(), and widenOp().
getNumOperands()
unsigned mlir::Operation::getNumOperands () inline
Definition at line 263 of file Operation.h.
References mlir::detail::OperandStorage::size().
Referenced by addExecuteResults(), clone(), mlir::Region::cloneInto(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpOpRegions(), mlir::createAffineComputationSlice(), elementwiseMatchAndRewriteHelper(), extractOperandTypes(), mlir::OpTrait::impl::foldIdempotent(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getNumOperands(), getOperandValuesImpl(), isAddMul(), mlir::sparse_tensor::isAdmissibleBranchExp(), isChainOfUnaryOpsFrom(), mlir::detail::isConstantLike(), isOpLoopInvariant(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match(), mlir::matchReduction(), materializeConversion(), mlir::MutableOperandRange::MutableOperandRange(), printGroupNonUniformArithmeticOp(), printOperation(), mlir::replaceAllMemRefUsesWith(), setInPlaceOpOperand(), setOperands(), mlir::OpBuilder::tryFold(), vectorizeAffineYieldOp(), mlir::OpTrait::impl::verifyAtLeastNOperands(), verifyAtomicUpdateOp(), verifyGroupNonUniformArithmeticOp(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOperandSizeAttr(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::OpTrait::impl::verifySameTypeOperands(), mlir::OpTrait::impl::verifyZeroOperands(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
getNumRegions()
unsigned mlir::Operation::getNumRegions () inline
Returns the number of regions held by this operation.
Definition at line 477 of file Operation.h.
Referenced by canBeHoisted(), clone(), collectUnderlyingAddressValues(), getBackwardSliceImpl(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getNumRegions(), hoistOpsBetween(), isPotentiallyUnknownSymbolTable(), isRegionReachable(), isVectorizableLoopBodyWithOpCond(), mlir::detail::ConversionPatternRewriterImpl::markNestedOpsIgnored(), mlirLinalgFillBuiltinNamedOpRegion(), mlirOperationGetFirstRegion(), mlirRegionGetNextInOperation(), mlir::impl::scalarizeVectorOp(), mlir::vector::splitFullAndPartialTransfer(), mlir::SymbolTable::SymbolTable(), vectorizeOneOperation(), mlir::OpTrait::impl::verifyAtLeastNRegions(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::OpTrait::impl::verifyNRegions(), mlir::OpTrait::impl::verifyOneRegion(), mlir::detail::verifyParallelCombiningOpInterface(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::detail::verifySymbolTable(), mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait(), mlir::OpTrait::impl::verifyZeroRegions(), mlir::dataflow::DeadCodeAnalysis::visit(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and wrapInExecuteRegion().
getNumResults()
unsigned mlir::Operation::getNumResults () inline
Return the number of results held by this operation.
Definition at line 321 of file Operation.h.
Referenced by clone(), convertOperationImpl(), elementwiseMatchAndRewriteHelper(), mlir::ConversionPatternRewriter::eraseOp(), getLibraryCallSymbolRef(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getNumResults(), mlir::detail::isConstantLike(), VectorizeConvolution::matchAndRewrite(), mlir::matchReduction(), materializeConversion(), mlir::detail::ConversionPatternRewriterImpl::notifyOpReplaced(), mlir::LLVM::detail::oneToOneRewrite(), mlir::OpAsmPrinter::printFunctionalType(), printNVVMIntrinsicOp(), printOneResultOp(), printOperation(), mlir::replaceAllMemRefUsesWith(), mlir::RewriterBase::replaceOp(), mlir::bufferization::replaceOpWithBufferizedValues(), mlir::RewriterBase::replaceOpWithIf(), mlir::impl::scalarizeVectorOp(), unpackPDLOperations(), mlir::OpTrait::impl::verifyAtLeastNResults(), mlir::detail::verifyDestinationStyleOpInterface(), mlir::OpTrait::impl::verifyElementwise(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyResultSizeAttr(), mlir::detail::verifyShapedDimOpInterface(), verifyShapeOrExtentTensorOp(), verifySizeOrIndexOp(), mlir::OpTrait::impl::verifyZeroResults(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and walkReferenceCountedValues().
getNumSuccessors()
unsigned mlir::Operation::getNumSuccessors () inline
Definition at line 506 of file Operation.h.
Referenced by clone(), collectUnderlyingAddressValues(), eraseTerminatorSuccessorOperands(), mlir::Block::getNumSuccessors(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getNumSuccessors(), getPHISourceValue(), getSuccessor(), isRegionOrCallableReturn(), mlir::OperationFingerPrint::OperationFingerPrint(), propagateTerminatorLiveness(), mlir::impl::scalarizeVectorOp(), setSuccessor(), mlir::SuccessorRange::SuccessorRange(), mlir::OpTrait::impl::verifyAtLeastNSuccessors(), mlir::OpTrait::impl::verifyNSuccessors(), mlir::OpTrait::impl::verifyOneSuccessor(), mlir::OpTrait::impl::verifyZeroSuccessors(), and mlir::dataflow::DeadCodeAnalysis::visit().
getOperand()
Value mlir::Operation::getOperand (unsigned idx) inline
Definition at line 267 of file Operation.h.
References mlir::IROperand< DerivedT, IRValueT >::get(), and getOpOperand().
Referenced by adjustAccessChainForBitwidth(), mlir::affineParallelize(), mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpOpRegions(), createLinalgBodyCalculationForElementwiseOp(), diagnoseInvalidOperandDominance(), foldExtractFromBroadcast(), mlir::OpTrait::impl::foldIdempotent(), mlir::OpTrait::impl::foldInvolution(), mlir::OpTrait::OneOperand< ConcreteType >::getOperand(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperand(), getPHISourceValue(), mlir::sparse_tensor::isAdmissibleBranch(), mlir::sparse_tensor::isAdmissibleBranchExp(), isChainOfUnaryOpsFrom(), isOpLoopInvariant(), mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments(), mlir::detail::matchOperandOrValueAtIndex(), mlir::matchReduction(), materializeConversion(), printAtomicUpdateOp(), printGroupNonUniformArithmeticOp(), printOperation(), reduceMatchAndRewriteHelper(), mlir::OpBuilder::tryFold(), verifyAtomicUpdateOp(), verifyCastOp(), verifyGroupNonUniformArithmeticOp(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameTypeOperands(), and verifyShiftOp().
getOperands()
operand_range mlir::Operation::getOperands () inline
Returns an iterator on the underlying Value's.
Definition at line 295 of file Operation.h.
References getOpOperands().
Referenced by canBeHoisted(), clone(), mlir::Region::cloneInto(), mlir::OperationEquivalence::computeHash(), convertElementwiseOp(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), mlir::createAffineComputationSlice(), defaultIsSmallAlloc(), dependsOnCarriedVals(), elementwiseMatchAndRewriteHelper(), extractBeneficiaryOps(), mlir::impl::foldCastInterfaceOp(), forwardTerminatorOperands(), getBackwardSliceImpl(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperands(), getOperandTypes(), getOperandValuesImpl(), getOrCreateOperandsMatchingResultTypes(), getOutermostInvariantForOp(), mlir::linalg::getUpperBoundForIndex(), hasNonAffineUsersOnThePath(), inlineConvertOmpRegions(), inlinePayload(), insertCasts(), isOpReady(), AllocaScopeInliner::matchAndRewrite(), AllocaScopeHoister::matchAndRewrite(), mlir::ConversionPattern::matchAndRewrite(), SortCommutativeOperands::matchAndRewrite(), matchSimpleReduction(), operand_begin(), operand_end(), mlir::OperationFingerPrint::OperationFingerPrint(), mlir::MutableOperandRange::operator OperandRange(), mlir::outlineSingleBlockRegion(), CommutativeOperand::popFrontAndPushAdjacentUnvisitedAncestors(), printAtomicUpdateOp(), mlir::OpAsmPrinter::printFunctionalType(), printNVVMIntrinsicOp(), printOneResultOp(), printOperation(), mlir::replaceAllMemRefUsesWith(), mlir::sparse_tensor::BufferizeDenseOpsPass::runOnOperation(), staticallyNonNegative(), mlir::scf::tileConsumerAndFuseProducerGreedilyUsingSCFForOp(), vectorizeOneOp(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments(), mlir::dataflow::SparseConstantPropagation::visitOperation(), and widenOp().
getOperandTypes()
operand_type_range mlir::Operation::getOperandTypes () inline
Definition at line 314 of file Operation.h.
References getOperands(), and mlir::OperandRange::getTypes().
Referenced by checkSourceOpTypes(), extractOperandTypes(), mlir::linalg::generateLibraryCallName(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperandTypes(), getOpToConvert(), hasTensorSemantics(), insertCasts(), isElementwiseMappableOpOnRankedTensors(), mlir::TypeConverter::isLegal(), isLegalOp(), mlir::outlineSingleBlockRegion(), printOneResultOp(), mlir::impl::verifyCastInterfaceOp(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::OpTrait::impl::verifyElementwise(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShapeOrExtentTensorOp(), and verifySizeOrIndexOp().
getOpOperand()
OpOperand& mlir::Operation::getOpOperand (unsigned idx) inline
Definition at line 305 of file Operation.h.
References mlir::detail::OperandStorage::getOperands().
Referenced by getOperand(), and setOperand().
getOpOperands()
MutableArrayRef<OpOperand> mlir::Operation::getOpOperands () inline
Definition at line 300 of file Operation.h.
References mlir::detail::OperandStorage::getOperands().
Referenced by annotateOpsWithBufferizationMarkers(), assertDestinationPassingStyle(), checkAliasInfoConsistency(), dropAllReferences(), mlir::bufferization::eliminateEmptyTensors(), mlir::memref::foldMemRefCast(), mlir::tensor::foldTensorCast(), mlir::bufferization::OneShotAnalysisState::gatherYieldedTensors(), mlir::bufferization::func_ext::CallOpInterface::getAliasingOpOperand(), getOperands(), inlineRegionAndEmitStore(), replaceUsesOfWith(), setInPlaceOpOperand(), and mlir::visitUsedValuesDefinedAbove().
getOpResult()
OpResult mlir::Operation::getOpResult (unsigned idx) inline
Definition at line 338 of file Operation.h.
References getResult().
getOpResults()
result_range mlir::Operation::getOpResults () inline
Definition at line 337 of file Operation.h.
References getResults().
Referenced by cloneAndFuseFirstUse(), dropAllUses(), forwardTerminatorOperands(), mlir::bufferization::OneShotAnalysisState::gatherUndefinedTensorUses(), mlir::bufferization::func_ext::CallOpInterface::getAliasingOpResult(), isUsedOutsideOfBlock(), and mlir::bufferization::replaceOpWithBufferizedValues().
getParentOfType()
template<typename OpTy > OpTy mlir::Operation::getParentOfType () inline
Return the closest surrounding parent operation that is of type 'OpTy'.
Definition at line 169 of file Operation.h.
Referenced by mlir::AllocationOpLLVMLowering::allocateBufferAutoAlign(), mlir::AllocationOpLLVMLowering::allocateBufferManuallyAlign(), mlir::sparse_tensor::createFuncCall(), mlir::LLVM::createGlobalString(), createSourceLocationInfo(), getAllocEffectFor(), getLibraryCallSymbolRef(), mlir::scf::insideMutuallyExclusiveBranches(), mlir::insideMutuallyExclusiveRegions(), mlir::replaceAllMemRefUsesWith(), and validateSupportedControlFlow().
getParentOp()
Operation* mlir::Operation::getParentOp () inline
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
Definition at line 165 of file Operation.h.
References mlir::Block::getParentOp().
Referenced by mlir::DataLayout::closest(), collectParentLayouts(), collectSymbolScopes(), collectValidReferencesFor(), mlir::DataLayoutAnalysis::DataLayoutAnalysis(), declareReduction(), mlir::Block::findAncestorOpInBlock(), mlir::Region::findAncestorOpInRegion(), findAncestorOpInRegion(), mlir::DataLayoutAnalysis::getAbove(), mlir::LLVM::ModuleTranslation::getAccessGroup(), mlir::LLVM::ModuleTranslation::getAliasScope(), getAllocEffectFor(), getAtMostNEnclosingLoops(), getAutomaticAllocationScope(), mlir::AnalysisManager::getCachedChildAnalysis(), mlir::Pass::getCachedParentAnalysis(), mlir::getEnclosingAffineOps(), getEnclosingRepetitiveRegion(), mlir::getLoopIVs(), mlir::SymbolTable::getNearestSymbolTable(), mlir::getNestingDepth(), getParentWithTrait(), mlir::spirv::getPushConstantValue(), mlir::sparse_tensor::getTop(), happensBefore(), mlir::hasNoInterveningEffect(), mlir::SymbolTable::insert(), isNestedInFunctionOpInterface(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), mlir::detail::ConversionPatternRewriterImpl::isOpIgnored(), isOpReady(), isProperAncestor(), isRegionOrCallableReturn(), mlir::isTopLevelValue(), mlir::spirv::lookupEntryPointABI(), mlir::spirv::lookupTargetEnv(), AllocaScopeHoister::matchAndRewrite(), mlir::matchReduction(), mlir::AnalysisManager::nest(), parentLLVMModule(), mlir::detail::PassCrashReproducerGenerator::prepareReproducerFor(), mlir::Block::print(), mlir::CallGraph::print(), print(), printOperation(), mlir::SymbolTable::remove(), mlir::SymbolUserMap::replaceAllUsesWith(), vectorizeAffineYieldOp(), vectorizeConstant(), verifyHasBindingUse(), verifySymbolAttribute(), mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::verifyTrait(), visit(), mlir::dataflow::DeadCodeAnalysis::visit(), and walkReferencedSymbolNodes().
getParentRegion()
Region* mlir::Operation::getParentRegion () inline
Returns the region to which the instruction belongs.
Returns nullptr if the instruction is unlinked.
Definition at line 161 of file Operation.h.
References mlir::Block::getParent().
Referenced by mlir::Region::findAncestorOpInRegion(), findAncestorOpInRegion(), mlir::getAffineScope(), mlir::getEnclosingRepetitiveRegion(), getEnclosingRepetitiveRegion(), mlir::Region::getParentRegion(), mlir::hasNoInterveningEffect(), mlir::isValidSymbol(), lastNonTerminatorInRegion(), mlir::moveLoopInvariantCode(), and verifyTerminatorSuccessors().
getParentWithTrait()
template<template< typename T > class Trait> Operation* mlir::Operation::getParentWithTrait () inline
Returns the closest surrounding parent operation with trait Trait.
Definition at line 179 of file Operation.h.
References getParentOp(), and hasTrait().
Referenced by getAllocEffectFor(), getDumpRootOp(), and mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait().
getRegion()
Region& mlir::Operation::getRegion (unsigned index) inline
Returns the region held by this operation at position 'index'.
Definition at line 486 of file Operation.h.
References getRegions().
Referenced by mlir::affineParallelize(), mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), clone(), collectSymbolScopes(), collectUnderlyingAddressValues(), convertOmpSections(), create(), mlir::ExecutionEngine::create(), createDecl(), mlir::function_interface_impl::eraseFunctionArguments(), getBackwardSliceImpl(), mlir::OpTrait::SingleBlock< ConcreteType >::getBody(), mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::getBodyBlock(), mlir::OpTrait::SingleBlock< ConcreteType >::getBodyRegion(), mlir::bufferization::getGlobalFor(), getModuleBody(), mlir::spirv::getPushConstantValue(), mlir::OpTrait::OneRegion< ConcreteType >::getRegion(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegion(), mlir::SymbolTable::insert(), mlir::function_interface_impl::insertFunctionArguments(), mlir::SymbolTable::lookupSymbolIn(), mlirLinalgFillBuiltinNamedOpRegion(), mlirOperationGetFirstRegion(), mlirRegionGetNextInOperation(), mlir::function_interface_impl::printFunctionSignature(), mlir::vector::splitFullAndPartialTransfer(), mlir::SymbolTable::SymbolTable(), mlir::SymbolUserMap::SymbolUserMap(), vectorizeStaticLinalgOpPrecondition(), mlir::detail::verifyParallelCombiningOpInterface(), mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyRegionTrait(), mlir::detail::verifySymbolTable(), and mlir::OpTrait::SingleBlock< ConcreteType >::verifyTrait().
getRegions()
MutableArrayRef<Region> mlir::Operation::getRegions () inline
Returns the regions held by this operation.
Definition at line 480 of file Operation.h.
Referenced by mlir::applyPatternsAndFoldGreedily(), mlir::bufferization::BufferizationAliasInfo::BufferizationAliasInfo(), mlir::OpBuilder::clone(), mlir::Region::cloneInto(), collectCallOps(), computeCallGraph(), detachNestedAndErase(), dfsPostorder(), dropAllDefinedValueUses(), dropAllReferences(), mlir::LLVM::ensureDistinctSuccessors(), getForwardSliceImpl(), mlir::getInnermostParallelLoops(), getInstAtPosition(), getRegion(), mlir::Region::getRegionNumber(), mlir::OpTrait::detail::MultiRegionTraitBase< ConcreteType, TraitType >::getRegions(), mlir::dataflow::DeadCodeAnalysis::initialize(), mlir::dataflow::AbstractDenseDataFlowAnalysis::initialize(), mlir::dataflow::AbstractSparseDataFlowAnalysis::initialize(), mlir::bytecode::detail::IRNumberingState::IRNumberingState(), mlir::isMemoryEffectFree(), mlir::isSpeculatable(), mlir::detail::ConversionPatternRewriterImpl::markNestedOpsIgnored(), AllocaScopeHoister::matchAndRewrite(), mergeIdenticalBlocks(), mlir::OperationFingerPrint::OperationFingerPrint(), propagateLiveness(), mlir::AttrTypeReplacer::replaceElementsIn(), validateSupportedControlFlow(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifyIsIsolatedFromAbove(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::detail::verifySymbolTable(), JamBlockGatherer::walk(), mlir::detail::walk(), walkSymbolTable(), mlir::SymbolTable::walkSymbolTables(), walkSymbolUses(), wouldOpBeTriviallyDeadImpl(), and wrapInExecuteRegion().
getRegisteredInfo()
Optional<RegisteredOperationName> mlir::Operation::getRegisteredInfo () inline
If this operation has a registered operation description, return it.
Otherwise return None.
Definition at line 54 of file Operation.h.
References getName(), and mlir::OperationName::getRegisteredInfo().
Referenced by mlir::Op< ConcreteType, Traits >::classof(), fold(), and populateDefaultAttrs().
getResult()
OpResult mlir::Operation::getResult (unsigned idx) inline
Get the 'idx'th result of this operation.
Definition at line 324 of file Operation.h.
Referenced by mlir::affineParallelize(), mlir::bufferization::func_ext::CallOpInterface::bufferize(), buildVectorWrite(), clone(), convertElementwiseOp(), convertOmpThreadprivate(), convertOperationImpl(), createLinalgBodyCalculationForElementwiseOp(), mlir::spirv::Deserializer::processOp< spirv::GenericCastToPtrExplicitOp >(), elementwiseMatchAndRewriteHelper(), mlir::op_definition_impl::foldTrait(), mlir::linalg::TileLoopNest::fuseProducer(), getCollapsedOpOperand(), mlir::AllocationOpLLVMLowering::getMemRefResultType(), mlir::linalg::getNeutralElement(), getOpResult(), mlir::OperationFolder::getOrCreateConstant(), mlir::OpTrait::OneResult< ConcreteType >::getResult(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResult(), mlir::OpTrait::OneTypedResult< ResultType >::Impl< ConcreteType >::getType(), mlir::nvgpu::getWarpMatrixInfo(), mlir::LLVM::detail::handleMultidimensionalVectors(), mlir::bufferization::insertSliceAnchoredEmptyTensorEliminationStep(), mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::detail::constant_float_op_binder::match(), mlir::detail::constant_int_op_binder::match(), matchAndReplaceDepthwiseConv(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), VectorizeConvolution::matchAndRewrite(), TransferReadToVectorLoadLowering::matchAndRewrite(), materializeConversion(), mlir::normalizeAffineFor(), mlir::OperationFolder::notifyRemoval(), mlir::LLVM::detail::oneToOneRewrite(), mlir::outlineSingleBlockRegion(), printConstantOp(), mlir::OpAsmPrinter::printFunctionalType(), printGroupNonUniformArithmeticOp(), printOneResultOp(), printOperation(), reduceMatchAndRewriteHelper(), mlir::impl::scalarizeVectorOp(), mlir::linalg::splitReduction(), mlir::linalg::splitReductionByScaling(), tileAndFuseFirstExtractUse(), tileAndFuseFirstExtractUseThroughContainingOpBlockArgument(), mlir::scf::tileReductionUsingScf(), mlir::OperationFolder::tryToFold(), unpackPDLOperations(), vectorizeOperand(), verifyCastOp(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::detail::verifyShapedDimOpInterface(), verifyShiftOp(), and walkReferenceCountedValues().
getResults()
result_range mlir::Operation::getResults () inline
Definition at line 332 of file Operation.h.
Referenced by mlir::bufferization::BufferizationAliasInfo::BufferizationAliasInfo(), buildVectorWrite(), mlir::async::cloneConstantsIntoTheRegion(), mlir::OperationEquivalence::computeHash(), dfsPostorder(), elementwiseMatchAndRewriteHelper(), extractBeneficiaryOps(), mlir::impl::foldCastInterfaceOp(), getForwardSliceImpl(), getLastDependentOpInRange(), getOpResults(), mlir::tensor::getOrCreateDestinations(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResults(), getResultTypes(), mlir::linalg::getUpperBoundForIndex(), getUses(), invertCollapseShapeIndexing(), mlir::linalg::ExtractSliceOfPadTensorSwapPattern::matchAndRewrite(), mlir::detail::ConversionPatternRewriterImpl::notifyOpReplaced(), mlir::linalg::peelLoop(), mlir::Liveness::print(), mlir::OpAsmPrinter::printFunctionalType(), printOperation(), propagateLiveness(), reduceMatchAndRewriteHelper(), mlir::replaceAllMemRefUsesWith(), mlir::ResultRange::replaceAllUsesWith(), replaceAllUsesWith(), mlir::AttrTypeReplacer::replaceElementsIn(), mlir::RewriterBase::replaceOpWithIf(), mlir::bufferization::replaceOpWithNewBufferizedOp(), result_begin(), result_end(), mlir::sparse_tensor::BufferizeDenseOpsPass::runOnOperation(), mlir::sinkOperationsIntoLaunchOp(), staticallyNonNegative(), mlir::linalg::tileReductionUsingForeachThread(), mlir::scf::tileReductionUsingScf(), mlir::OpBuilder::tryFold(), use_begin(), use_empty(), use_end(), validateSupportedControlFlow(), vectorizeAsLinalgGeneric(), mlir::linalg::vectorizeCopy(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::dataflow::IntegerRangeAnalysis::visitOperation(), widenOp(), and wrapInExecuteRegion().
getResultTypes()
result_type_range mlir::Operation::getResultTypes () inline
Definition at line 345 of file Operation.h.
References getResults(), and mlir::ResultRange::getTypes().
Referenced by checkSourceOpTypes(), clone(), mlir::OperationEquivalence::computeHash(), equivalenceAnalysis(), getOpToConvert(), getOrCreateOperandsMatchingResultTypes(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::getResultTypes(), hasTensorSemantics(), insertCasts(), mlir::TypeConverter::isLegal(), isLegalOp(), mlir::LLVM::detail::oneToOneRewrite(), mlir::outlineSingleBlockRegion(), printNamedStructuredOp(), printNVVMIntrinsicOp(), result_type_begin(), result_type_end(), vectorizeOneOp(), mlir::impl::verifyCastInterfaceOp(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), mlir::OpTrait::impl::verifyElementwise(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), verifyShapeOrExtentTensorOp(), verifySizeOrIndexOp(), walkReferenceCountedValues(), and wrapInExecuteRegion().
getSuccessor()
Block* mlir::Operation::getSuccessor (unsigned index) inline
Definition at line 508 of file Operation.h.
References getBlockOperands(), and getNumSuccessors().
Referenced by eraseTerminatorSuccessorOperands(), getPHISourceValue(), mlir::OpTrait::OneSuccessor< ConcreteType >::getSuccessor(), mlir::Block::getSuccessor(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessor(), mlir::OperationFingerPrint::OperationFingerPrint(), propagateTerminatorLiveness(), and mlir::detail::verifyBranchSuccessorOperands().
getSuccessors()
SuccessorRange mlir::Operation::getSuccessors () inline
Definition at line 503 of file Operation.h.
Referenced by clone(), mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::getSuccessors(), propagateTerminatorLiveness(), successor_begin(), successor_end(), verifyTerminatorSuccessors(), and mlir::dataflow::DeadCodeAnalysis::visit().
getUsers()
user_range mlir::Operation::getUsers () inline
Returns a range of all users.
Definition at line 650 of file Operation.h.
References user_begin(), and user_end().
Referenced by collapseBranch(), dfsPostorder(), mlir::bufferization::BufferPlacementTransformationBase::findCommonDominator(), findMatchingTransferRead(), findUnusedStore(), getForwardSliceImpl(), mlir::nvgpu::getUserContract(), hasBindingUse(), inferFragType(), insertionPointDominatesUses(), mlir::matchReduction(), mlir::moveLoopInvariantCode(), mlir::memref::multiBuffer(), and visit().
getUses()
use_range mlir::Operation::getUses () inline
Returns a range of all uses, which is useful for iterating over all uses.
Definition at line 623 of file Operation.h.
References getResults(), and mlir::ResultRange::getUses().
Referenced by mlir::bufferization::bufferizeOp(), hasOneUse(), and replaceUsesAndPropagateType().
hasAttr() [1/2]
bool mlir::Operation::hasAttr (StringAttr name) inline
Return true if the operation has an attribute with the provided name, false otherwise.
Definition at line 385 of file Operation.h.
Referenced by mlir::bufferization::allocationDoesNotEscape(), mlir::bufferization::insertTensorCopies(), and mlir::bufferization::shouldDeallocateOpResult().
hasAttr() [2/2]
bool mlir::Operation::hasAttr (StringRef name) inline
Definition at line 386 of file Operation.h.
hasAttrOfType()
template<typename AttrClass , typename NameT > bool mlir::Operation::hasAttrOfType (NameT && name) inline
Definition at line 388 of file Operation.h.
hasOneUse()
bool mlir::Operation::hasOneUse () inline
Returns true if this operation has exactly one use.
Definition at line 626 of file Operation.h.
References getUses().
Referenced by mlir::matchReduction().
hasSuccessors()
bool mlir::Operation::hasSuccessors () inline
Definition at line 505 of file Operation.h.
hasTrait()
template<template< typename T > class Trait> bool mlir::Operation::hasTrait () inline
Returns true if the operation was registered with a particular trait, e.g.
hasTrait<OperandsAreSignlessIntegerLike>().
Definition at line 528 of file Operation.h.
References mlir::OperationName::hasTrait().
Referenced by AncestorKey::AncestorKey(), canBeHoisted(), mlir::async::cloneConstantsIntoTheRegion(), collectSymbolScopes(), collectValidReferencesFor(), mlir::OperationEquivalence::computeHash(), mlir::impl::ensureRegionTerminator(), executeGetOperandsResults(), mlir::op_definition_impl::foldTrait(), getBackwardSliceImpl(), getCommonBlock(), mlir::LocalAliasAnalysis::getModRef(), mlir::getMutableRegionBranchSuccessorOperands(), mlir::SymbolTable::getNearestSymbolTable(), getParentWithTrait(), mlir::OpTrait::hasElementwiseMappableTraits(), mlir::bytecode::detail::IRNumberingState::IRNumberingState(), mlir::detail::isConstantLike(), isDirectInModuleLikeOp(), mlir::isLegalForReturnOpTypeConversionPattern(), mlir::isMemoryEffectFree(), isMemRefNormalizable(), isNestedInFunctionOpInterface(), isOpItselfPotentialAutomaticAllocation(), mlir::isRegionReturnLike(), mlir::isTopLevelValue(), isUseSpeciallyKnownDead(), mlir::isValidSymbol(), mlir::SymbolTable::lookupSymbolIn(), lookupSymbolInImpl(), AllocaScopeHoister::matchAndRewrite(), SortCommutativeOperands::matchAndRewrite(), mlirBlockGetTerminator(), mlir::RewritePattern::Pattern(), print(), propagateLiveness(), mlir::LLVM::satisfiesLLVMModule(), mlir::sortTopologically(), mlir::SymbolTable::SymbolTable(), mlir::OpTrait::impl::verifyIsIsolatedFromAbove(), walkSymbolTable(), mlir::SymbolTable::walkSymbolTables(), walkSymbolUses(), and wouldOpBeTriviallyDeadImpl().
insertOperands()
void Operation::insertOperands (unsigned index, ValueRange operands)
Insert the given operands into the operand list at the given 'index'.
Definition at line 213 of file Operation.cpp.
References setOperands().
Referenced by mlir::gpu::addAsyncDependency(), addExecuteResults(), and mlir::MutableOperandRange::append().
isAncestor()
bool mlir::Operation::isAncestor (Operation * other) inline
Return true if this operation is an ancestor of the other operation.
An operation is considered as its own ancestor, use isProperAncestor to avoid this.
Definition at line 194 of file Operation.h.
References isProperAncestor().
Referenced by canBeHoisted(), collectValidReferencesFor(), dependsOnCarriedVals(), and mlir::hasNoInterveningEffect().
isBeforeInBlock()
bool Operation::isBeforeInBlock (Operation * other)
Given an operation 'other' that is within the same parent block, return whether the current operation is before 'other' in the operation list of the parent block.
Note: This function has an average complexity of O(1), but worst case may take O(N) where N is the number of operations within the parent block.
Definition at line 265 of file Operation.cpp.
References mlir::Block::isOpOrderValid(), and mlir::Block::recomputeOpOrder().
Referenced by mlir::detail::ConversionPatternRewriterImpl::applyRewrites(), mlir::LivenessBlockInfo::currentlyLiveValues(), mlir::LivenessBlockInfo::getEndOperation(), getFusedLoopNestInsertionPoint(), hasNonAffineUsersOnThePath(), mlir::Liveness::isDeadAfter(), mayExistInterleavedUses(), mlir::PostDominanceInfo::properlyPostDominates(), and verifyResultTypesAreInferrable().
isProperAncestor()
bool Operation::isProperAncestor (Operation * other)
Return true if this operation is a proper ancestor of the other operation.
Definition at line 176 of file Operation.cpp.
References getParentOp().
Referenced by cloneAndFuseFirstUse(), happensBefore(), isAncestor(), isLocallyDefined(), mlir::AnalysisManager::nest(), and mlir::replaceLoopWithNewYields().
isRegistered()
bool mlir::Operation::isRegistered () inline
Returns true if this operation has a registered operation description, otherwise false.
Definition at line 60 of file Operation.h.
References getName(), and mlir::OperationName::isRegistered().
isUsedOutsideOfBlock()
bool mlir::Operation::isUsedOutsideOfBlock (Block * block) inline
Returns true if the results of this operation are used outside of the given block.
Definition at line 633 of file Operation.h.
References getOpResults(), and mlir::Value::isUsedOutsideOfBlock().
mightHaveTrait()
template<template< typename T > class Trait> bool mlir::Operation::mightHaveTrait () inline
Returns true if the operation might have the provided trait.
This means that either the operation is unregistered, or it was registered with the provide trait.
Definition at line 536 of file Operation.h.
References mlir::OperationName::mightHaveTrait().
Referenced by create(), ensureDistinctSuccessors(), mlir::isNotBranchOpInterfaceOrReturnLikeOp(), isTerminator(), mlir::matchReduction(), mayBeValidWithoutTerminator(), and mlir::wouldOpBeTriviallyDead().
moveAfter() [1/2]
void Operation::moveAfter (Block * block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right after iterator in the specified block.
Definition at line 454 of file Operation.cpp.
References mlir::Block::end(), and moveBefore().
moveAfter() [2/2]
void Operation::moveAfter (Operation * existingOp)
Unlink this operation from its current block and insert it right after existingOp which may be in the same or another block in the same function.
Definition at line 448 of file Operation.cpp.
References getBlock().
moveBefore() [1/2]
void Operation::moveBefore (Block * block, llvm::iplist< Operation >::iterator iterator)
Unlink this operation from its current block and insert it right before iterator in the specified block.
Unlink this operation from its current basic block and insert it right before iterator in the specified basic block.
Definition at line 440 of file Operation.cpp.
References getBlock(), and mlir::Block::getOperations().
moveBefore() [2/2]
void Operation::moveBefore (Operation * existingOp)
Unlink this operation from its current block and insert it right before existingOp which may be in the same or another block in the same function.
Definition at line 434 of file Operation.cpp.
References getBlock().
Referenced by hoistOpsBetween(), mlir::OperationFolder::insertKnownConstant(), moveAfter(), mlir::sortTopologically(), and mlir::OperationFolder::tryToFold().
operand_begin()
operand_iterator mlir::Operation::operand_begin () inline
Definition at line 291 of file Operation.h.
References getOperands().
Referenced by mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_begin(), operand_type_begin(), and mlir::replaceAllMemRefUsesWith().
operand_end()
operand_iterator mlir::Operation::operand_end () inline
Definition at line 292 of file Operation.h.
References getOperands().
Referenced by mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_end(), operand_type_end(), and mlir::replaceAllMemRefUsesWith().
operand_type_begin()
operand_type_iterator mlir::Operation::operand_type_begin () inline
Definition at line 312 of file Operation.h.
References operand_begin().
Referenced by mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_type_begin().
operand_type_end()
operand_type_iterator mlir::Operation::operand_type_end () inline
Definition at line 313 of file Operation.h.
References operand_end().
Referenced by mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::operand_type_end().
populateDefaultAttrs()
void mlir::Operation::populateDefaultAttrs () inline
Sets default attributes on unset attributes.
Definition at line 464 of file Operation.h.
References getAttrDictionary(), getContext(), mlir::NamedAttrList::getDictionary(), getRegisteredInfo(), and setAttrs().
print() [1/2]
void Operation::print (raw_ostream & os, AsmState & state)
Definition at line 3495 of file AsmPrinter.cpp.
References mlir::AsmState::getImpl(), mlir::AsmState::getPrinterFlags(), mlir::detail::AsmStateImpl::initializeAliases(), and mlir::OpPrintingFlags::shouldUseLocalScope().
print() [2/2]
void Operation::print (raw_ostream & os, const OpPrintingFlags & flags = llvm::None)
Definition at line 3475 of file AsmPrinter.cpp.
References getParentOp(), hasTrait(), print(), and mlir::OpPrintingFlags::shouldUseLocalScope().
Referenced by mlir::Diagnostic::appendOp(), mlir::detail::RecoveryReproducerContext::generate(), generateLocationsFromIR(), mlir::Value::print(), mlir::OpState::print(), and printIR().
remove()
void Operation::remove ()
Remove the operation from its parent block, but don't delete it.
Definition at line 426 of file Operation.cpp.
References getBlock().
Referenced by mlir::lsp::MLIRServer::convertFromBytecode().
removeAttr() [1/2]
Attribute mlir::Operation::removeAttr (StringAttr name) inline
Remove the attribute with the specified name if it exists.
Return the attribute that was erased, or nullptr if there was no attribute with such name.
Definition at line 407 of file Operation.h.
References mlir::NamedAttrList::erase(), getContext(), and mlir::NamedAttrList::getDictionary().
Referenced by lowerEntryPointABIAttr(), removeAttr(), setAllArgResAttrDicts(), mlir::function_interface_impl::detail::setArgResAttrDict(), mlir::function_interface_impl::setFunctionType(), and mlir::SymbolTable::setSymbolVisibility().
removeAttr() [2/2]
Attribute mlir::Operation::removeAttr (StringRef name) inline
Definition at line 414 of file Operation.h.
References getContext(), and removeAttr().
replaceAllUsesWith()
template<typename ValuesT > void mlir::Operation::replaceAllUsesWith (ValuesT && values) inline
Replace all uses of results of this operation with the provided 'values'.
Definition at line 203 of file Operation.h.
References getResults(), and mlir::ResultRange::replaceAllUsesWith().
Referenced by convertToLaunchFuncOp(), mlir::OperationFolder::insertKnownConstant(), FoldLaunchArguments::matchAndRewrite(), mlir::promoteIfSingleIteration(), mlir::replaceAllMemRefUsesWith(), mlir::OpTrait::OneResult< ConcreteType >::replaceAllUsesWith(), mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::replaceAllUsesWith(), mlir::RewriterBase::replaceOp(), and updateCalls().
replaceUsesOfWith()
void Operation::replaceUsesOfWith (Value from, Value to)
Replace any uses of 'from' with 'to' within this operation.
Definition at line 184 of file Operation.cpp.
References getOpOperands().
Referenced by mlir::inlineCall(), and replaceConstantUsesOf().
result_begin()
result_iterator mlir::Operation::result_begin () inline
Definition at line 330 of file Operation.h.
References getResults().
Referenced by mlir::OperationFolder::create(), and mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_begin().
result_end()
result_iterator mlir::Operation::result_end () inline
Definition at line 331 of file Operation.h.
References getResults().
Referenced by mlir::OperationFolder::create(), and mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_end().
result_type_begin()
result_type_iterator mlir::Operation::result_type_begin () inline
Definition at line 343 of file Operation.h.
References getResultTypes().
Referenced by mlir::OperationFolder::insertKnownConstant(), materializeConversion(), and mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_type_begin().
result_type_end()
result_type_iterator mlir::Operation::result_type_end () inline
Definition at line 344 of file Operation.h.
References getResultTypes().
Referenced by mlir::OpTrait::detail::MultiResultTraitBase< ConcreteType, TraitType >::result_type_end().
setAttr() [1/2]
void mlir::Operation::setAttr (StringAttr name, Attribute value) inline
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 395 of file Operation.h.
References getContext(), mlir::NamedAttrList::getDictionary(), mlir::NamedAttrList::set(), and value.
Referenced by mlir::gpu::addAsyncDependency(), mlir::bufferization::allocateTensorForShapedValue(), annotateConflict(), mlir::function_interface_impl::eraseFunctionArguments(), mlir::function_interface_impl::eraseFunctionResults(), mlir::sparse_tensor::getFunc(), getLibraryCallSymbolRef(), mlir::function_interface_impl::insertFunctionArguments(), mlir::function_interface_impl::insertFunctionResults(), mlir::bufferization::insertTensorCopies(), lowerAsEntryFunction(), matchAndReplaceDepthwiseConv(), outlineKernelFuncImpl(), setAllArgResAttrDicts(), mlir::function_interface_impl::detail::setArgResAttrDict(), setAttr(), mlir::function_interface_impl::setFunctionType(), setInPlaceOpOperand(), mlir::SymbolTable::setSymbolName(), mlir::SymbolTable::setSymbolVisibility(), and mlir::vector::splitFullAndPartialTransfer().
setAttr() [2/2]
void mlir::Operation::setAttr (StringRef name, Attribute value) inline
Definition at line 400 of file Operation.h.
References getContext(), setAttr(), and value.
setAttrs() [1/2]
void mlir::Operation::setAttrs (ArrayRef< NamedAttribute > newAttrs) inline
Definition at line 366 of file Operation.h.
References getContext(), and setAttrs().
setAttrs() [2/2]
void mlir::Operation::setAttrs (DictionaryAttr newAttrs) inline
Set the attribute dictionary on this operation.
Definition at line 362 of file Operation.h.
Referenced by mlir::bufferization::func_ext::CallOpInterface::bufferize(), populateDefaultAttrs(), mlir::AttrTypeReplacer::replaceElementsIn(), setAttrs(), setDialectAttrs(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
setDialectAttrs()
template<typename DialectAttrT > void mlir::Operation::setDialectAttrs (DialectAttrT && dialectAttrs) inline
Set the dialect attributes for this operation, and preserve all dependent.
Definition at line 454 of file Operation.h.
References mlir::NamedAttrList::append(), getAttrs(), getContext(), mlir::NamedAttrList::getDictionary(), mlir::NamedAttrList::push_back(), and setAttrs().
setLoc()
void mlir::Operation::setLoc (Location loc) inline
Set the source location the operation was defined or derived from.
Definition at line 157 of file Operation.h.
Referenced by generateLocationsFromIR(), and mlir::AttrTypeReplacer::replaceElementsIn().
setOperand()
void mlir::Operation::setOperand (unsigned idx, Value value) inline
Definition at line 268 of file Operation.h.
References getOpOperand(), mlir::IROperand< DerivedT, IRValueT >::set(), and value.
Referenced by mlir::MutableOperandRange::assign(), mlir::createAffineComputationSlice(), mlir::replaceAllMemRefUsesWith(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::setOperand(), mlir::OpTrait::OneOperand< ConcreteType >::setOperand(), mlir::linalg::splitReduction(), mlir::linalg::splitReductionByScaling(), and tileAndFuseFirstExtractUseThroughContainingOpBlockArgument().
setOperands() [1/2]
void Operation::setOperands (unsigned start, unsigned length, ValueRange operands)
Replace the operands beginning at 'start' and ending at 'start' + 'length' with the ones provided in 'operands'.
'operands' may be smaller or larger than the range pointed to by 'start'+'length'.
Definition at line 203 of file Operation.cpp.
References getNumOperands(), and mlir::detail::OperandStorage::setOperands().
setOperands() [2/2]
void Operation::setOperands (ValueRange operands)
Replace the current operands of this operation with the ones provided in 'operands'.
Definition at line 194 of file Operation.cpp.
References mlir::detail::OperandStorage::setOperands().
Referenced by mlir::affineParallelize(), mlir::MutableOperandRange::assign(), mlir::Region::cloneInto(), generateUnrolledLoop(), insertOperands(), SortCommutativeOperands::matchAndRewrite(), and mlir::dataflow::SparseConstantPropagation::visitOperation().
setSuccessor()
void Operation::setSuccessor (Block * block, unsigned index)
Definition at line 484 of file Operation.cpp.
References getBlockOperands(), and getNumSuccessors().
Referenced by mlir::OpTrait::detail::MultiSuccessorTraitBase< ConcreteType, TraitType >::setSuccessor(), and mlir::OpTrait::OneSuccessor< ConcreteType >::setSuccessor().
successor_begin()
succ_iterator mlir::Operation::successor_begin () inline
Definition at line 501 of file Operation.h.
References getSuccessors().
successor_end()
succ_iterator mlir::Operation::successor_end () inline
Definition at line 502 of file Operation.h.
References getSuccessors().
use_begin()
use_iterator mlir::Operation::use_begin () inline
Definition at line 619 of file Operation.h.
References getResults(), and mlir::ResultRange::use_begin().
Referenced by user_begin().
use_empty()
bool mlir::Operation::use_empty () inline
Returns true if this operation has no uses.
Definition at line 629 of file Operation.h.
References getResults(), and mlir::ResultRange::use_empty().
Referenced by mlir::RewriterBase::eraseBlock(), mlir::RewriterBase::eraseOp(), mlir::isOpTriviallyDead(), isResultValueDead(), and mlir::OpState::use_empty().
use_end()
use_iterator mlir::Operation::use_end () inline
Definition at line 620 of file Operation.h.
References getResults(), and mlir::ResultRange::use_end().
Referenced by user_end().
user_begin()
user_iterator mlir::Operation::user_begin () inline
Definition at line 646 of file Operation.h.
References use_begin().
Referenced by getUsers().
user_end()
user_iterator mlir::Operation::user_end () inline
Definition at line 647 of file Operation.h.
References use_end().
Referenced by getUsers().
walk() [1/2]
template<WalkOrder Order = WalkOrder::PostOrder, typename FnT , typename RetT = detail::walkResultType<FnT>> std::enable_if_t<llvm::function_traits<std::decay_t<FnT> >::num_args == 1, RetT> mlir::Operation::walk (FnT && callback) inline
Walk the operation by calling the callback for each nested operation (including this one), block or region, depending on the callback provided.
Regions, blocks and operations at the same nesting level are visited in lexicographical order. The walk order for enclosing regions, blocks and operations with respect to their nested ones is specified by 'Order' (post-order by default). A callback on a block or operation is allowed to erase that block or operation if either:
the walk is in post-order, or
the walk is in pre-order and the walk is skipped after the erasure.
The callback method can take any of the following forms: void(Operation*) : Walk all operations opaquely.
op->walk([](Operation nestedOp) { ...}); void(OpT) : Walk all operations of the given derived type.
op->walk([](ReturnOp returnOp) { ...}); WalkResult(Operation|OpT) : Walk operations, but allow for interruption/skipping.
op->walk([](... op) { // Skip the walk of this op based on some invariant. if (some_invariant) return WalkResult::skip(); // Interrupt, i.e cancel, the walk based on some invariant. if (another_invariant) return WalkResult::interrupt(); return WalkResult::advance(); });
Definition at line 574 of file Operation.h.
Referenced by mlir::bufferization::analyzeOp(), annotateOpsWithBufferizationMarkers(), assertDestinationPassingStyle(), mlir::bufferization::BufferizationAliasInfo::BufferizationAliasInfo(), mlir::bufferization::bufferizeOp(), buildBlockMapping(), canBeHoisted(), checkAliasInfoConsistency(), mlir::DataLayoutAnalysis::DataLayoutAnalysis(), mlir::bufferization::deallocateBuffers(), mlir::LLVM::detail::DebugTranslation::DebugTranslation(), mlir::bufferization::eliminateEmptyTensors(), mlir::LLVM::ensureDistinctSuccessors(), equivalenceAnalysis(), mlir::finalizeParallelLoopToGPUConversion(), mlir::transform::gpu::findTopLevelForeachThreadOp(), mlir::bufferization::OneShotAnalysisState::gatherUndefinedTensorUses(), mlir::bufferization::OneShotAnalysisState::gatherYieldedTensors(), generateLocationsFromIR(), getFirstDependentOpInRange(), getLastDependentOpInRange(), getLoadAndStoreMemRefAccesses(), getOpToConvert(), getShmReadAndWriteOps(), hasNonAffineUsersOnThePath(), inPlaceAnalysis(), mlir::bufferization::insertTensorCopies(), isOpReady(), mlir::transform::gpu::mapNestedForeachToThreadsImpl(), mlir::detail::ConversionPatternRewriterImpl::markNestedOpsIgnored(), mlir::NestedPattern::match(), mlir::bufferization::OneShotAnalysisState::OneShotAnalysisState(), mlir::OperationFingerPrint::OperationFingerPrint(), mlir::nvgpu::optimizeSharedMemoryReadsAndWrites(), outlineKernelFuncImpl(), mlir::Liveness::print(), resolveUsesInRepetitiveRegions(), mlir::vector::transferOpflowOpt(), validateSupportedControlFlow(), mlir::OpState::walk(), and walkReferenceCountedValues().
walk() [2/2]
template<typename FnT , typename RetT = detail::walkResultType<FnT>> std::enable_if_t<llvm::function_traits<std::decay_t<FnT> >::num_args == 2, RetT> mlir::Operation::walk (FnT && callback) inline
Generic walker with a stage aware callback.
Walk the operation by calling the callback for each nested operation (including this one) N+1 times, where N is the number of regions attached to that operation.
The callback method can take any of the following forms: void(Operation *, const WalkStage &) : Walk all operation opaquely
op->walk([](Operation nestedOp, const WalkStage &stage) { ...}); void(OpT, const WalkStage &) : Walk all operations of the given derived type.
op->walk([](ReturnOp returnOp, const WalkStage &stage) { ...}); WalkResult(Operation|OpT, const WalkStage &stage) : Walk operations, but allow for interruption/skipping.
op->walk([](... op, const WalkStage &stage) { // Skip the walk of this op based on some invariant. if (some_invariant) return WalkResult::skip(); // Interrupt, i.e cancel, the walk based on some invariant. if (another_invariant) return WalkResult::interrupt(); return WalkResult::advance(); });
Definition at line 602 of file Operation.h.
References mlir::detail::walk().
Friends And Related Function Documentation
Block
friend class Block friend
Definition at line 784 of file Operation.h.
llvm::ilist_node_with_parent< Operation, Block >
friend class llvm::ilist_node_with_parent< Operation, Block > friend
Definition at line 787 of file Operation.h.
llvm::ilist_traits< Operation >
friend struct llvm::ilist_traits< Operation > friend
Definition at line 778 of file Operation.h.
Value
friend class Value friend
Definition at line 787 of file Operation.h.
The documentation for this class was generated from the following files:
include/mlir/IR/Operation.h
lib/IR/AsmPrinter.cpp
lib/IR/Operation.cpp