MLIR: mlir::python::PyOperationBase Class Reference
mlir::python::PyOperationBase Class Reference abstract
Base class for PyOperation and PyOpView which exposes the primary, user visible methods for manipulating it.
#include "Bindings/Python/IRModule.h"
Public Member Functions
virtual ~PyOperationBase ()=default
void print (pybind11::object fileObject, bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool assumeVerified)
Implements the bound 'print' method and helps with others.
pybind11::object getAsm (bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool assumeVerified)
void writeBytecode (const pybind11::object &fileObject)
void moveAfter (PyOperationBase &other)
Moves the operation before or after the other operation.
void moveBefore (PyOperationBase &other)
virtual PyOperation & getOperation ()=0
Each must provide access to the raw Operation.
Detailed Description
Base class for PyOperation and PyOpView which exposes the primary, user visible methods for manipulating it.
Definition at line 501 of file IRModule.h.
Constructor & Destructor Documentation
~PyOperationBase()
virtual mlir::python::PyOperationBase::~PyOperationBase () virtual default
Member Function Documentation
getAsm()
py::object PyOperationBase::getAsm (bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool assumeVerified)
Definition at line 1040 of file IRCore.cpp.
References print().
getOperation()
virtual PyOperation& mlir::python::PyOperationBase::getOperation () pure virtual
Each must provide access to the raw Operation.
Implemented in mlir::python::PyOpView, and mlir::python::PyOperation.
Referenced by mlir::python::PySymbolTable::erase(), mlir::python::PySymbolTable::getSymbolName(), mlir::python::PySymbolTable::getVisibility(), mlir::python::PyInsertionPoint::insert(), mlir::python::PySymbolTable::insert(), moveAfter(), moveBefore(), print(), mlir::python::PySymbolTable::PySymbolTable(), mlir::python::PySymbolTable::replaceAllSymbolUses(), mlir::python::PySymbolTable::setSymbolName(), mlir::python::PySymbolTable::setVisibility(), mlir::python::PySymbolTable::walkSymbolTables(), and writeBytecode().
moveAfter()
void PyOperationBase::moveAfter (PyOperationBase & other)
Moves the operation before or after the other operation.
Definition at line 1062 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), getOperation(), and mlirOperationMoveAfter().
moveBefore()
void PyOperationBase::moveBefore (PyOperationBase & other)
Definition at line 1071 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), getOperation(), and mlirOperationMoveBefore().
print()
void PyOperationBase::print (pybind11::object fileObject, bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope, bool assumeVerified)
Implements the bound 'print' method and helps with others.
Definition at line 995 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::PyFileAccumulator::getCallback(), getOperation(), mlir::PyFileAccumulator::getUserData(), mlirOperationPrintWithFlags(), mlirOperationVerify(), mlirOpPrintingFlagsCreate(), mlirOpPrintingFlagsDestroy(), mlirOpPrintingFlagsElideLargeElementsAttrs(), mlirOpPrintingFlagsEnableDebugInfo(), mlirOpPrintingFlagsPrintGenericOpForm(), and mlirOpPrintingFlagsUseLocalScope().
Referenced by getAsm().
writeBytecode()
void PyOperationBase::writeBytecode (const pybind11::object & fileObject)
Definition at line 1032 of file IRCore.cpp.
References mlir::python::PyOperation::checkValid(), mlir::PyFileAccumulator::getCallback(), getOperation(), mlir::PyFileAccumulator::getUserData(), and mlirOperationWriteBytecode().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModule.h
lib/Bindings/Python/IRCore.cpp