MLIR: mlir::PDLPatternConfigBase< T > Class Template Reference
mlir::PDLPatternConfigBase< T > Class Template Reference
This class provides a base class for users implementing a type of pattern configuration.
#include "mlir/IR/PatternMatch.h"
Static Public Member Functions
static bool classof (const PDLPatternConfig *config)
Support LLVM style casting.
static TypeID getConfigID ()
Return the type id used for this configuration.
Protected Member Functions
PDLPatternConfigBase ()
Protected Member Functions inherited from mlir::PDLPatternConfig
PDLPatternConfig (TypeID id)
Additional Inherited Members
Public Member Functions inherited from mlir::PDLPatternConfig
virtual ~PDLPatternConfig ()=default
virtual void notifyRewriteBegin (PatternRewriter &rewriter)
Hooks that are invoked at the beginning and end of a rewrite of a matched pattern.
virtual void notifyRewriteEnd (PatternRewriter &rewriter)
TypeID getTypeID () const
Return the TypeID that represents this configuration.
Detailed Description
template<typename T>
class mlir::PDLPatternConfigBase< T >
This class provides a base class for users implementing a type of pattern configuration.
Definition at line 840 of file PatternMatch.h.
Constructor & Destructor Documentation
PDLPatternConfigBase()
template<typename T > mlir::PDLPatternConfigBase< T >::PDLPatternConfigBase () inline protected
Definition at line 851 of file PatternMatch.h.
Member Function Documentation
classof()
template<typename T > static bool mlir::PDLPatternConfigBase< T >::classof (const PDLPatternConfig * config) inline static
Support LLVM style casting.
Definition at line 843 of file PatternMatch.h.
References mlir::PDLPatternConfigBase< T >::getConfigID(), and mlir::PDLPatternConfig::getTypeID().
getConfigID()
template<typename T > static TypeID mlir::PDLPatternConfigBase< T >::getConfigID () inline static
Return the type id used for this configuration.
Definition at line 848 of file PatternMatch.h.
Referenced by mlir::PDLPatternConfigBase< T >::classof().
The documentation for this class was generated from the following file:
include/mlir/IR/PatternMatch.h