MLIR: mlir::BytecodeWriterConfig Class Reference
mlir::BytecodeWriterConfig Class Reference
This class contains the configuration used for the bytecode writer.
#include "mlir/Bytecode/BytecodeWriter.h"
Classes
struct Impl
Public Member Functions
BytecodeWriterConfig (StringRef producer="MLIR" LLVM_VERSION_STRING)
producer is an optional string that can be used to identify the producer of the bytecode when reading.
BytecodeWriterConfig (FallbackAsmResourceMap &map, StringRef producer="MLIR" LLVM_VERSION_STRING)
map is a fallback resource map, which when provided will attach resource printers for the fallback resources within the map.
~BytecodeWriterConfig ()
const Impl & getImpl () const
Return an instance of the internal implementation.
void attachResourcePrinter (std::unique_ptr< AsmResourcePrinter > printer)
Attach the given resource printer to the writer configuration.
template<typename CallableT >
std::enable_if_t< std::is_convertible< CallableT, function_ref< void(Operation *, AsmResourceBuilder &)> >::value > attachResourcePrinter (StringRef name, CallableT &&printFn)
Attach an resource printer, in the form of a callable, to the configuration.
void attachFallbackResourcePrinter (FallbackAsmResourceMap &map)
Attach resource printers to the AsmState for the fallback resources in the given map.
Detailed Description
This class contains the configuration used for the bytecode writer.
It controls various aspects of bytecode generation, and contains all of the various bytecode writer hooks.
Definition at line 24 of file BytecodeWriter.h.
Constructor & Destructor Documentation
BytecodeWriterConfig() [1/2]
BytecodeWriterConfig::BytecodeWriterConfig (StringRef producer = "MLIR" LLVM_VERSION_STRING)
producer is an optional string that can be used to identify the producer of the bytecode when reading.
It has no functional effect on the bytecode serialization.
Definition at line 40 of file BytecodeWriter.cpp.
BytecodeWriterConfig() [2/2]
BytecodeWriterConfig::BytecodeWriterConfig (FallbackAsmResourceMap & map, StringRef producer = "MLIR" LLVM_VERSION_STRING)
map is a fallback resource map, which when provided will attach resource printers for the fallback resources within the map.
Definition at line 42 of file BytecodeWriter.cpp.
References attachFallbackResourcePrinter().
~BytecodeWriterConfig()
BytecodeWriterConfig::~BytecodeWriterConfig () default
Member Function Documentation
attachFallbackResourcePrinter()
void mlir::BytecodeWriterConfig::attachFallbackResourcePrinter (FallbackAsmResourceMap & map) inline
Attach resource printers to the AsmState for the fallback resources in the given map.
Definition at line 62 of file BytecodeWriter.h.
References attachResourcePrinter(), and mlir::FallbackAsmResourceMap::getPrinters().
Referenced by BytecodeWriterConfig().
attachResourcePrinter() [1/2]
void BytecodeWriterConfig::attachResourcePrinter (std::unique_ptr< AsmResourcePrinter > printer)
Attach the given resource printer to the writer configuration.
Definition at line 49 of file BytecodeWriter.cpp.
Referenced by attachFallbackResourcePrinter(), and attachResourcePrinter().
attachResourcePrinter() [2/2]
template<typename CallableT > std::enable_if_t<std::is_convertible< CallableT, function_ref<void(Operation *, AsmResourceBuilder &)> >::value> mlir::BytecodeWriterConfig::attachResourcePrinter (StringRef name, CallableT && printFn) inline
Attach an resource printer, in the form of a callable, to the configuration.
Definition at line 55 of file BytecodeWriter.h.
References attachResourcePrinter(), and mlir::AsmResourcePrinter::fromCallable().
getImpl()
const Impl& mlir::BytecodeWriterConfig::getImpl () const inline
Return an instance of the internal implementation.
Definition at line 41 of file BytecodeWriter.h.
Referenced by mlir::writeBytecodeToFile().
The documentation for this class was generated from the following files:
include/mlir/Bytecode/BytecodeWriter.h
lib/Bytecode/Writer/BytecodeWriter.cpp