MLIR: mlir::dataflow::IntegerValueRange Class Reference
mlir::dataflow::IntegerValueRange Class Reference
This lattice value represents the integer range of an SSA value.
#include "mlir/Analysis/DataFlow/IntegerRangeAnalysis.h"
Public Member Functions
IntegerValueRange (Optional< ConstantIntRanges > value=None)
Create an integer value range lattice value.
bool isUninitialized () const
Whether the range is uninitialized.
const ConstantIntRanges & getValue () const
Get the known integer value range.
bool operator== (const IntegerValueRange &rhs) const
Compare two ranges.
void print (raw_ostream &os) const
Print the integer value range.
Static Public Member Functions
static IntegerValueRange getMaxRange (Value value)
Create a maximal range ([0, uint_max(t)] / [int_min(t), int_max(t)]) range that is used to mark the value as unable to be analyzed further, where t is the type of value.
static IntegerValueRange join (const IntegerValueRange &lhs, const IntegerValueRange &rhs)
Take the union of two ranges.
Detailed Description
This lattice value represents the integer range of an SSA value.
Definition at line 25 of file IntegerRangeAnalysis.h.
Constructor & Destructor Documentation
IntegerValueRange()
mlir::dataflow::IntegerValueRange::IntegerValueRange (Optional< ConstantIntRanges > value = None) inline
Create an integer value range lattice value.
Definition at line 33 of file IntegerRangeAnalysis.h.
Member Function Documentation
getMaxRange()
IntegerValueRange IntegerValueRange::getMaxRange (Value value) static
Create a maximal range ([0, uint_max(t)] / [int_min(t), int_max(t)]) range that is used to mark the value as unable to be analyzed further, where t is the type of value.
Definition at line 26 of file IntegerRangeAnalysis.cpp.
References mlir::ConstantIntRanges::getStorageBitwidth(), and mlir::Value::getType().
Referenced by mlir::dataflow::IntegerRangeAnalysis::setToEntryState(), mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments(), and mlir::dataflow::IntegerRangeAnalysis::visitOperation().
getValue()
const ConstantIntRanges& mlir::dataflow::IntegerValueRange::getValue () const inline
Get the known integer value range.
Definition at line 41 of file IntegerRangeAnalysis.h.
References isUninitialized().
Referenced by mlir::dataflow::IntegerValueRangeLattice::onUpdate(), and mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments().
isUninitialized()
bool mlir::dataflow::IntegerValueRange::isUninitialized () const inline
Whether the range is uninitialized.
This happens when the state hasn't been set during the analysis.
Definition at line 38 of file IntegerRangeAnalysis.h.
Referenced by getValue(), mlir::dataflow::IntegerRangeAnalysis::visitNonControlFlowArguments(), and mlir::dataflow::IntegerRangeAnalysis::visitOperation().
join()
static IntegerValueRange mlir::dataflow::IntegerValueRange::join (const IntegerValueRange & lhs, const IntegerValueRange & rhs) inline static
Take the union of two ranges.
Definition at line 52 of file IntegerRangeAnalysis.h.
operator==()
bool mlir::dataflow::IntegerValueRange::operator== (const IntegerValueRange & rhs) const inline
Compare two ranges.
Definition at line 47 of file IntegerRangeAnalysis.h.
print()
void mlir::dataflow::IntegerValueRange::print (raw_ostream & os) const inline
Print the integer value range.
Definition at line 62 of file IntegerRangeAnalysis.h.
The documentation for this class was generated from the following files:
include/mlir/Analysis/DataFlow/IntegerRangeAnalysis.h
lib/Analysis/DataFlow/IntegerRangeAnalysis.cpp