MLIR: mlir::AttrTypeSubElementWalker Class Reference
mlir::AttrTypeSubElementWalker Class Reference
AttrTypeSubElementHandler.
#include "mlir/IR/SubElementInterfaces.h"
Public Member Functions
AttrTypeSubElementWalker (function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn)
void walk (Attribute element)
Walk an attribute.
void walk (Type element)
Walk a type.
template<typename RangeT >
void walkRange (RangeT &&elements)
Walk a range of attributes or types.
Detailed Description
AttrTypeSubElementHandler.
This class is used by AttrTypeSubElementHandler instances to walking sub attributes and types.
Definition at line 138 of file SubElementInterfaces.h.
Constructor & Destructor Documentation
AttrTypeSubElementWalker()
mlir::AttrTypeSubElementWalker::AttrTypeSubElementWalker (function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn) inline
Definition at line 140 of file SubElementInterfaces.h.
Member Function Documentation
walk() [1/2]
void mlir::AttrTypeSubElementWalker::walk (Attribute element) inline
Walk an attribute.
Definition at line 145 of file SubElementInterfaces.h.
Referenced by mlir::AttrTypeSubElementHandler< Location >::walk(), mlir::AttrTypeSubElementHandler< T, std::enable_if_t< std::is_base_of_v< Attribute, T >||std::is_base_of_v< Type, T > > >::walk(), mlir::AttrTypeSubElementHandler< NamedAttribute >::walk(), and walkRange().
walk() [2/2]
void mlir::AttrTypeSubElementWalker::walk (Type element) inline
Walk a type.
Definition at line 150 of file SubElementInterfaces.h.
walkRange()
template<typename RangeT > void mlir::AttrTypeSubElementWalker::walkRange (RangeT && elements) inline
Walk a range of attributes or types.
Definition at line 156 of file SubElementInterfaces.h.
References walk().
Referenced by mlir::AttrTypeSubElementHandler< TypeRange >::walk().
The documentation for this class was generated from the following file:
include/mlir/IR/SubElementInterfaces.h