MLIR: mlir::sparse_tensor::SparseTensorNNZ Class Reference
mlir::sparse_tensor::SparseTensorNNZ Class Reference final
Statistics regarding the number of nonzero subtensors in a source tensor, for direct sparse=>sparse conversion a la https://arxiv.org/abs/2001.02609.
#include "mlir/ExecutionEngine/SparseTensor/Storage.h"
Public Types
using NNZConsumer = const std::function< void(uint64_t)> &
The type of callback functions which receive an nnz-statistic.
Public Member Functions
SparseTensorNNZ (const std::vector< uint64_t > &lvlSizes, const std::vector< DimLevelType > &lvlTypes)
Allocates the statistics structure for the desired target-tensor level structure (i.e., sizes and types).
SparseTensorNNZ (const SparseTensorNNZ &)=delete
SparseTensorNNZ & operator= (const SparseTensorNNZ &)=delete
uint64_t getLvlRank () const
Gets the target-tensor's level-rank.
template<typename V >
void initialize (SparseTensorEnumeratorBase< V > &enumerator)
Enumerates the source tensor to fill in the statistics.
void forallIndices (uint64_t stopLvl, NNZConsumer yield) const
Lexicographically enumerates all indicies for levels strictly less than stopLvl, and passes their nnz statistic to the callback.
Detailed Description
Statistics regarding the number of nonzero subtensors in a source tensor, for direct sparse=>sparse conversion a la https://arxiv.org/abs/2001.02609.
N.B., this class stores references to the parameters passed to the constructor; thus, objects of this class must not outlive those parameters.
This class does not have the "dimension" vs "level" distinction, but since it is used for initializing the levels of a SparseTensorStorage object, we use the "level" name throughout for the sake of consistency.
Definition at line 877 of file Storage.h.
Member Typedef Documentation
NNZConsumer
using mlir::sparse_tensor::SparseTensorNNZ::NNZConsumer = const std::function<void(uint64_t)> &
The type of callback functions which receive an nnz-statistic.
Definition at line 911 of file Storage.h.
Constructor & Destructor Documentation
SparseTensorNNZ() [1/2]
SparseTensorNNZ::SparseTensorNNZ (const std::vector< uint64_t > & lvlSizes, const std::vector< DimLevelType > & lvlTypes)
Allocates the statistics structure for the desired target-tensor level structure (i.e., sizes and types).
This constructor does not actually populate the statistics, however; for that see initialize.
Precondition: lvlSizes must not contain zeros. Asserts: lvlSizes.size() == lvlTypes.size().
Definition at line 24 of file NNZ.cpp.
References mlir::sparse_tensor::detail::checkedMul(), getLvlRank(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), and MLIR_SPARSETENSOR_FATAL.
SparseTensorNNZ() [2/2]
mlir::sparse_tensor::SparseTensorNNZ::SparseTensorNNZ (const SparseTensorNNZ &) delete
Member Function Documentation
forallIndices()
void SparseTensorNNZ::forallIndices (uint64_t stopLvl, SparseTensorNNZ::NNZConsumer yield) const
Lexicographically enumerates all indicies for levels strictly less than stopLvl, and passes their nnz statistic to the callback.
Since our use-case only requires the statistic not the coordinates themselves, we do not bother to construct those coordinates.
Definition at line 56 of file NNZ.cpp.
References getLvlRank(), and mlir::sparse_tensor::isCompressedDLT().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
getLvlRank()
uint64_t mlir::sparse_tensor::SparseTensorNNZ::getLvlRank () const inline
Gets the target-tensor's level-rank.
Definition at line 893 of file Storage.h.
Referenced by forallIndices(), and SparseTensorNNZ().
initialize()
template<typename V > void mlir::sparse_tensor::SparseTensorNNZ::initialize (SparseTensorEnumeratorBase< V > & enumerator) inline
Enumerates the source tensor to fill in the statistics.
The enumerator should already incorporate the mapping from the source tensor-dimensions to the target storage-levels.
Asserts:
enumerator.getTrgRank() == getLvlRank().
enumerator.getTrgSizes() == lvlSizes.
Definition at line 903 of file Storage.h.
References mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::forallElements(), mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getTrgRank(), and mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getTrgSizes().
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
operator=()
SparseTensorNNZ& mlir::sparse_tensor::SparseTensorNNZ::operator= (const SparseTensorNNZ &) delete
The documentation for this class was generated from the following files:
include/mlir/ExecutionEngine/SparseTensor/Storage.h
lib/ExecutionEngine/SparseTensor/NNZ.cpp