MLIR: lib/Bindings/Python/DialectPDL.cpp File Reference
DialectPDL.cpp File Reference
#include "mlir-c/Dialect/PDL.h"
#include "mlir-c/IR.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
Functions
void populateDialectPDLSubmodule (const pybind11::module &m)
PYBIND11_MODULE (_mlirDialectsPDL, m)
Function Documentation
populateDialectPDLSubmodule()
void populateDialectPDLSubmodule (const pybind11::module & m)
Definition at line 19 of file DialectPDL.cpp.
References mlirPDLAttributeTypeGet(), mlirPDLOperationTypeGet(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLTypeTypeGet(), mlirPDLValueTypeGet(), mlirTypeIsAPDLAttributeType(), mlirTypeIsAPDLOperationType(), mlirTypeIsAPDLRangeType(), mlirTypeIsAPDLType(), mlirTypeIsAPDLTypeType(), and mlirTypeIsAPDLValueType().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (_mlirDialectsPDL , m)
Definition at line 99 of file DialectPDL.cpp.
References populateDialectPDLSubmodule().