MLIR: lib/Bindings/Python/DialectTransform.cpp File Reference
DialectTransform.cpp File Reference
#include "mlir-c/Dialect/Transform.h"
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
Functions
void populateDialectTransformSubmodule (const pybind11::module &m)
PYBIND11_MODULE (_mlirDialectsTransform, m)
Function Documentation
populateDialectTransformSubmodule()
void populateDialectTransformSubmodule (const pybind11::module & m)
Definition at line 19 of file DialectTransform.cpp.
References MlirStringRef::data, MlirStringRef::length, mlirStringRefCreate(), mlirTransformAnyOpTypeGet(), mlirTransformOperationTypeGet(), mlirTransformOperationTypeGetOperationName(), mlirTypeIsATransformAnyOpType(), and mlirTypeIsATransformOperationType().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (_mlirDialectsTransform , m)
Definition at line 61 of file DialectTransform.cpp.
References populateDialectTransformSubmodule().