MLIR: lib/Dialect/Bufferization/Transforms/EmptyTensorElimination.cpp File Reference
EmptyTensorElimination.cpp File Reference
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/Transforms.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
mlir::bufferization
Macros
#define GEN_PASS_DEF_EMPTYTENSORELIMINATION
Functions
static bool neededValuesDominateInsertionPoint (const DominanceInfo &domInfo, Operation *insertionPoint, const SmallVector< Value > &neededValues)
Return true if all neededValues are in scope at the given insertionPoint.
static bool insertionPointDominatesUses (const DominanceInfo &domInfo, Operation *insertionPoint, Operation *emptyTensorOp)
Return true if the given insertionPoint dominates all uses of emptyTensorOp.
static Operation * findValidInsertionPoint (Operation *emptyTensorOp, const SmallVector< Value > &neededValues)
Find a valid insertion point for a replacement of emptyTensorOp, assuming that the replacement may use any value from neededValues.
Macro Definition Documentation
GEN_PASS_DEF_EMPTYTENSORELIMINATION
#define GEN_PASS_DEF_EMPTYTENSORELIMINATION
Definition at line 21 of file EmptyTensorElimination.cpp.
Function Documentation
findValidInsertionPoint()
static Operation* findValidInsertionPoint (Operation * emptyTensorOp, const SmallVector< Value > & neededValues) static
Find a valid insertion point for a replacement of emptyTensorOp, assuming that the replacement may use any value from neededValues.
Definition at line 63 of file EmptyTensorElimination.cpp.
References insertionPointDominatesUses(), and neededValuesDominateInsertionPoint().
Referenced by mlir::bufferization::eliminateEmptyTensors().
insertionPointDominatesUses()
static bool insertionPointDominatesUses (const DominanceInfo & domInfo, Operation * insertionPoint, Operation * emptyTensorOp) static
Return true if the given insertionPoint dominates all uses of emptyTensorOp.
Definition at line 51 of file EmptyTensorElimination.cpp.
References mlir::DominanceInfo::dominates(), and mlir::Operation::getUsers().
Referenced by findValidInsertionPoint().
neededValuesDominateInsertionPoint()
static bool neededValuesDominateInsertionPoint (const DominanceInfo & domInfo, Operation * insertionPoint, const SmallVector< Value > & neededValues) static
Return true if all neededValues are in scope at the given insertionPoint.
Definition at line 32 of file EmptyTensorElimination.cpp.
References mlir::DominanceInfo::dominates(), and mlir::Block::findAncestorOpInBlock().
Referenced by findValidInsertionPoint().