MLIR: lib/Dialect/Linalg/Transforms/EraseUnusedOperandsAndResults.cpp File Reference
EraseUnusedOperandsAndResults.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
Functions
static bool isResultValueDead (linalg::GenericOp genericOp, OpResult result)
Return true if the result of an operation genericOp is dead.
Function Documentation
isResultValueDead()
static bool isResultValueDead (linalg::GenericOp genericOp, OpResult result) static
Return true if the result of an operation genericOp is dead.
Definition at line 17 of file EraseUnusedOperandsAndResults.cpp.
References mlir::OpResult::getResultNumber(), mlir::Value::hasOneUse(), mlir::Operation::use_empty(), mlir::Value::use_empty(), and mlir::Value::user_begin().