MLIR: lib/IR/ExtensibleDialect.cpp File Reference
ExtensibleDialect.cpp File Reference
#include "mlir/IR/ExtensibleDialect.h"
#include "mlir/IR/AttributeSupport.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/StorageUniquerSupport.h"
#include "mlir/Support/LogicalResult.h"
Classes
struct mlir::detail::DynamicTypeStorage
Storage of DynamicType.
struct mlir::detail::DynamicAttrStorage
Storage of DynamicAttr.
Namespaces
mlir
Include the generated interface declarations.
mlir::detail
Detect if any of the given parameter types has a sub-element handler.
Functions
static LogicalResult typeOrAttrParser (AsmParser &parser, SmallVectorImpl< Attribute > &parsedParams)
Default parser for dynamic attribute or type parameters.
static void typeOrAttrPrinter (AsmPrinter &printer, ArrayRef< Attribute > params)
Default printer for dynamic attribute or type parameters.
Function Documentation
typeOrAttrParser()
static LogicalResult typeOrAttrParser (AsmParser & parser, SmallVectorImpl< Attribute > & parsedParams) static
Default parser for dynamic attribute or type parameters.
Parse in the format '(<>)?' or '<attr (,attr)*>'.
Definition at line 25 of file ExtensibleDialect.cpp.
References mlir::failure(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseOptionalGreater(), mlir::AsmParser::parseOptionalLess(), and mlir::success().
Referenced by mlir::DynamicAttrDefinition::get(), and mlir::DynamicTypeDefinition::get().
typeOrAttrPrinter()
static void typeOrAttrPrinter (AsmPrinter & printer, ArrayRef< Attribute > params) static
Default printer for dynamic attribute or type parameters.
Print in the format '(<>)?' or '<attr (,attr)*>'.
Definition at line 47 of file ExtensibleDialect.cpp.
References mlir::AsmPrinter::getStream().
Referenced by mlir::DynamicAttrDefinition::get(), and mlir::DynamicTypeDefinition::get().