MLIR: lib/Rewrite/FrozenRewritePatternSet.cpp File Reference
FrozenRewritePatternSet.cpp File Reference
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "ByteCode.h"
#include "mlir/Conversion/PDLToPDLInterp/PDLToPDLInterp.h"
#include "mlir/Dialect/PDL/IR/PDLOps.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
Functions
static LogicalResult convertPDLToPDLInterp (ModuleOp pdlModule, DenseMap< Operation *, PDLPatternConfigSet * > &configMap)
Function Documentation
convertPDLToPDLInterp()
static LogicalResult convertPDLToPDLInterp (ModuleOp pdlModule, DenseMap< Operation *, PDLPatternConfigSet * > & configMap) static
Lower the PDL pattern module to the interpreter dialect.
Definition at line 20 of file FrozenRewritePatternSet.cpp.
References mlir::OpPassManager::addPass(), mlir::createPDLToPDLInterpPass(), mlir::PassManager::enableVerifier(), mlir::failed(), mlir::failure(), mlir::isOpTriviallyDead(), mlir::PassManager::run(), and mlir::success().
Referenced by mlir::FrozenRewritePatternSet::FrozenRewritePatternSet().