MLIR: lib/IR/AffineMap.cpp File Reference
AffineMap.cpp File Reference
#include "mlir/IR/AffineMap.h"
#include "AffineMapDetail.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"
#include <numeric>
Functions
template<typename AffineExprContainer >
static SmallVector< AffineMap, 4 > inferFromExprList (ArrayRef< AffineExprContainer > exprsList)
static SmallVector< AffineMap > compressUnusedImpl (ArrayRef< AffineMap > maps, llvm::function_ref< AffineMap(AffineMap)> compressionFun)
Function Documentation
compressUnusedImpl()
static SmallVector<AffineMap> compressUnusedImpl (ArrayRef< AffineMap > maps, llvm::function_ref< AffineMap(AffineMap)> compressionFun) static
Definition at line 579 of file AffineMap.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by mlir::compressUnusedDims(), and mlir::compressUnusedSymbols().
inferFromExprList()
template<typename AffineExprContainer > static SmallVector<AffineMap, 4> inferFromExprList (ArrayRef< AffineExprContainer > exprsList) static
Definition at line 221 of file AffineMap.cpp.
References mlir::AffineMap::get(), and mlir::getMaxDimAndSymbol().
Referenced by mlir::AffineMap::inferFromExprList().