MLIR: lib/CAPI/Dialect/Linalg.cpp File Reference
Linalg.cpp File Reference
#include "mlir-c/Dialect/Linalg.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
Functions
void mlirLinalgFillBuiltinNamedOpRegion (MlirOperation mlirOp)
Apply the special region builder for the builtin named Linalg op.
Function Documentation
mlirLinalgFillBuiltinNamedOpRegion()
void mlirLinalgFillBuiltinNamedOpRegion (MlirOperation mlirOp)
Apply the special region builder for the builtin named Linalg op.
Assert that op is a builtin named Linalg op.
Definition at line 18 of file Linalg.cpp.
References mlir::OpBuilder::createBlock(), mlir::Operation::getAttrs(), mlir::Region::getBlocks(), mlir::Operation::getContext(), mlir::getElementTypeOrSelf(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), mlir::OperationName::getStringRef(), mlir::OpBuilder::setInsertionPointToStart(), and unwrap().
Referenced by populateDialectLinalgSubmodule().