MLIR: lib/Dialect/Linalg/IR/LinalgInterfaces.cpp File Reference
LinalgInterfaces.cpp File Reference
#include "mlir/Dialect/Linalg/IR/LinalgInterfaces.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/Complex/IR/Complex.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/SmallBitVector.h"
#include "mlir/Dialect/Linalg/IR/LinalgInterfaces.cpp.inc"
Classes
struct HasAffineDimExprVisitor
Visitor to check if any of the given set of positions from AffineDimExprs are used within an AffineExpr.
Enumerations
enum class MatchContractionResult {
Success = 0 , NotLinalgOp , WrongNumOperands , NoReduction ,
NotProjectedPermutations , NotAddMul
}
enum class MatchConvolutionResult {
Success = 0 , NotLinalgOp , WrongNumOperands , WrongInputIndexingMap ,
NotProjectedPermutations , NonConvolutionLoop , OutputDimsNotParallel , NonOutputDimNotReduction
}
enum class MatchFillResult { Success = 0 , NotLinalgOp , WrongNumOperands , NotScalarInput }
Functions
static bool isChainOfUnaryOpsFrom (Value v, Value from)
Return true if the use-def chain from v to from consists of 0 or more unary single-operand operations.
template<typename OpType >
static OpType getSingleOpOfType (Block &block)
Return the unique instance of OpType in block if it is indeed unique.
template<typename AddOpType , typename MulOpType >
static bool isAddMul (Block &block)
Detect whether res is any permutation of u5(u1(c) + u2(u3(a) * u4(b))) on the field (AddOpType, MulOpType), where u1, u2, u3, u4 and u5 represent unary operations that may change the type.
static MatchContractionResult isContractionInterfaceImpl (Operation *op)
template<typename T >
static T getAffineExprOfType (AffineExpr lhs, AffineExpr rhs)
Of the given two expressions returns one that is of type T (lhs gets preference over rhs)
static llvm::SmallDenseSet< unsigned > getPreservedDims (AffineMap map)
static MatchConvolutionResult isConvolutionInterfaceImpl (Operation *op)
static MatchFillResult isFillInterfaceImpl (Operation *op)
static Value createOrFoldDimOp (OpBuilder &b, Location loc, Value source, int64_t dim)
Helper function that creates a memref::DimOp or tensor::DimOp depending on the type of source.
static OpFoldResult createFoldedDimOp (OpBuilder &b, Location loc, Value source, int64_t dim)
static std::pair< int64_t, int64_t > getResultsPositionInLoopsToShapeMap (LinalgOp &op)
Enumeration Type Documentation
MatchContractionResult
enum MatchContractionResult strong
Enumerator
Success
NotLinalgOp
WrongNumOperands
NoReduction
NotProjectedPermutations
NotAddMul
Definition at line 110 of file LinalgInterfaces.cpp.
MatchConvolutionResult
enum MatchConvolutionResult strong
Enumerator
Success
NotLinalgOp
WrongNumOperands
WrongInputIndexingMap
NotProjectedPermutations
NonConvolutionLoop
OutputDimsNotParallel
NonOutputDimNotReduction
Definition at line 266 of file LinalgInterfaces.cpp.
MatchFillResult
enum MatchFillResult strong
Enumerator
Success
NotLinalgOp
WrongNumOperands
NotScalarInput
Definition at line 428 of file LinalgInterfaces.cpp.
Function Documentation
createFoldedDimOp()
static OpFoldResult createFoldedDimOp (OpBuilder & b, Location loc, Value source, int64_t dim) static
Definition at line 475 of file LinalgInterfaces.cpp.
References mlir::Type::cast(), mlir::linalg::createOrFoldDimOp(), mlir::Builder::getIndexAttr(), and mlir::Value::getType().
Referenced by mlir::linalg::computeSliceParameters().
createOrFoldDimOp()
static Value createOrFoldDimOp (OpBuilder & b, Location loc, Value source, int64_t dim) static
Helper function that creates a memref::DimOp or tensor::DimOp depending on the type of source.
Definition at line 467 of file LinalgInterfaces.cpp.
References mlir::OpBuilder::createOrFold(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::linalg::createFoldedDimOp(), and mlir::linalg::getDynOperands().
getAffineExprOfType()
template<typename T > static T getAffineExprOfType (AffineExpr lhs, AffineExpr rhs) static
Of the given two expressions returns one that is of type T (lhs gets preference over rhs)
Definition at line 183 of file LinalgInterfaces.cpp.
getPreservedDims()
static llvm::SmallDenseSet<unsigned> getPreservedDims (AffineMap map) static
Definition at line 257 of file LinalgInterfaces.cpp.
References mlir::AffineExpr::cast(), mlir::AffineDimExpr::getPosition(), mlir::AffineMap::getResults(), and mlir::AffineMap::isProjectedPermutation().
Referenced by isConvolutionInterfaceImpl().
getResultsPositionInLoopsToShapeMap()
static std::pair<int64_t, int64_t> getResultsPositionInLoopsToShapeMap (LinalgOp & op) static
Definition at line 555 of file LinalgInterfaces.cpp.
getSingleOpOfType()
template<typename OpType > static OpType getSingleOpOfType (Block & block) static
Return the unique instance of OpType in block if it is indeed unique.
Return null if none or more than 1 instances exist.
Definition at line 64 of file LinalgInterfaces.cpp.
isAddMul()
template<typename AddOpType , typename MulOpType > static bool isAddMul (Block & block) static
Detect whether res is any permutation of u5(u1(c) + u2(u3(a) * u4(b))) on the field (AddOpType, MulOpType), where u1, u2, u3, u4 and u5 represent unary operations that may change the type.
Definition at line 81 of file LinalgInterfaces.cpp.
References mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), and mlir::Block::getTerminator().
isChainOfUnaryOpsFrom()
static bool isChainOfUnaryOpsFrom (Value v, Value from) static
Return true if the use-def chain from v to from consists of 0 or more unary single-operand operations.
Definition at line 50 of file LinalgInterfaces.cpp.
References mlir::Value::getDefiningOp(), mlir::Operation::getNumOperands(), and mlir::Operation::getOperand().
isContractionInterfaceImpl()
static MatchContractionResult isContractionInterfaceImpl (Operation * op) static
Definition at line 118 of file LinalgInterfaces.cpp.
References mlir::AffineMap::isProjectedPermutation(), NoReduction, NotAddMul, NotLinalgOp, NotProjectedPermutations, Success, and WrongNumOperands.
Referenced by mlir::linalg::isaContractionOpInterface().
isConvolutionInterfaceImpl()
static MatchConvolutionResult isConvolutionInterfaceImpl (Operation * op) static
Definition at line 277 of file LinalgInterfaces.cpp.
References mlir::failed(), getPreservedDims(), NonConvolutionLoop, NonOutputDimNotReduction, NotLinalgOp, NotProjectedPermutations, OutputDimsNotParallel, Success, WrongInputIndexingMap, and WrongNumOperands.
isFillInterfaceImpl()
static MatchFillResult isFillInterfaceImpl (Operation * op) static
Definition at line 435 of file LinalgInterfaces.cpp.
References NotLinalgOp, NotScalarInput, Success, value, and WrongNumOperands.