MLIR: lib/Dialect/Affine/Transforms/LoopFusion.cpp File Reference
LoopFusion.cpp File Reference
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/Dialect/Affine/Analysis/AffineAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
#include "mlir/Dialect/Affine/Analysis/LoopAnalysis.h"
#include "mlir/Dialect/Affine/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/LoopFusionUtils.h"
#include "mlir/Dialect/Affine/LoopUtils.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <iomanip>
#include <sstream>
#include "mlir/Dialect/Affine/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_AFFINELOOPFUSION
#define DEBUG_TYPE "affine-loop-fusion"
Functions
static void sinkSequentialLoops (MemRefDependenceGraph::Node *node)
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType)
static Value createPrivateMemRef (AffineForOp forOp, Operation *srcStoreOpInst, unsigned dstLoopDepth, Optional< unsigned > fastMemorySpace, uint64_t localBufSizeThreshold)
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, Value memref, MemRefDependenceGraph *mdg)
Walking from node 'srcId' to node 'dstId' (exclusive of 'srcId' and 'dstId'), if there is any non-affine operation accessing 'memref', return true.
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, MemRefDependenceGraph *mdg)
Check whether a memref value in node 'srcId' has a non-affine that is between node 'srcId' and node 'dstId' (exclusive of 'srcNode' and 'dstNode').
static bool isFusionProfitable (Operation *srcOpInst, Operation *srcStoreOpInst, AffineForOp dstForOp, ArrayRef< ComputationSliceState > depthSliceUnions, unsigned maxLegalFusionDepth, unsigned *dstLoopDepth, double computeToleranceThreshold)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-fusion"
Definition at line 44 of file LoopFusion.cpp.
GEN_PASS_DEF_AFFINELOOPFUSION
#define GEN_PASS_DEF_AFFINELOOPFUSION
Definition at line 40 of file LoopFusion.cpp.
Function Documentation
createPrivateMemRef()
static Value createPrivateMemRef (AffineForOp forOp, Operation * srcStoreOpInst, unsigned dstLoopDepth, Optional< unsigned > fastMemorySpace, uint64_t localBufSizeThreshold) static
Definition at line 891 of file LoopFusion.cpp.
References mlir::MemRefRegion::compute(), mlir::OpBuilder::create(), mlir::floorDiv(), mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineDimExpr(), mlir::MemRefRegion::getConstantBoundingSizeAndShape(), mlir::MemRefRegion::getConstraints(), mlir::Operation::getLoc(), getMemRefEltSizeInBytes(), mlir::presburger::IntegerRelation::getNumCols(), mlir::presburger::IntegerRelation::getNumVars(), mlir::FlatAffineValueConstraints::getValues(), mlir::simplifyAffineExpr(), and mlir::succeeded().
getMemRefEltSizeInBytes()
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType) static
Definition at line 872 of file LoopFusion.cpp.
Referenced by createPrivateMemRef().
hasNonAffineUsersOnThePath() [1/2]
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, MemRefDependenceGraph * mdg) static
Check whether a memref value in node 'srcId' has a non-affine that is between node 'srcId' and node 'dstId' (exclusive of 'srcNode' and 'dstNode').
Definition at line 1028 of file LoopFusion.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getOperands(), and hasNonAffineUsersOnThePath().
hasNonAffineUsersOnThePath() [2/2]
static bool hasNonAffineUsersOnThePath (unsigned srcId, unsigned dstId, Value memref, MemRefDependenceGraph * mdg) static
Walking from node 'srcId' to node 'dstId' (exclusive of 'srcId' and 'dstId'), if there is any non-affine operation accessing 'memref', return true.
Otherwise, return false.
Definition at line 994 of file LoopFusion.cpp.
References mlir::WalkResult::advance(), mlir::Value::getUsers(), mlir::WalkResult::interrupt(), mlir::Operation::isBeforeInBlock(), and mlir::Operation::walk().
Referenced by hasNonAffineUsersOnThePath().
isFusionProfitable()
static bool isFusionProfitable (Operation * srcOpInst, Operation * srcStoreOpInst, AffineForOp dstForOp, ArrayRef< ComputationSliceState > depthSliceUnions, unsigned maxLegalFusionDepth, unsigned * dstLoopDepth, double computeToleranceThreshold) static
Definition at line 1089 of file LoopFusion.cpp.
References mlir::MemRefRegion::compute(), mlir::failed(), mlir::getComputeCost(), mlir::getFusionComputeCost(), mlir::Operation::getLoc(), mlir::getLoopIVs(), mlir::getLoopNestStats(), mlir::getMemoryFootprintBytes(), mlir::MemRefRegion::getRegionSize(), mlir::ComputationSliceState::isEmpty(), and max().
sinkSequentialLoops()
static void sinkSequentialLoops (MemRefDependenceGraph::Node * node) static
Definition at line 865 of file LoopFusion.cpp.
References mlir::sinkSequentialLoops().