MLIR: lib/Dialect/Affine/Transforms/LoopUnroll.cpp File Reference
LoopUnroll.cpp File Reference
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/Dialect/Affine/Analysis/LoopAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/LoopUtils.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/Affine/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_AFFINELOOPUNROLL
#define DEBUG_TYPE "affine-loop-unroll"
Functions
static bool isInnermostAffineForOp (AffineForOp op)
Returns true if no other affine.for ops are nested within op.
static void gatherInnermostLoops (func::FuncOp f, SmallVectorImpl< AffineForOp > &loops)
Gathers loops that have no affine.for's nested within.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-unroll"
Definition at line 31 of file LoopUnroll.cpp.
GEN_PASS_DEF_AFFINELOOPUNROLL
#define GEN_PASS_DEF_AFFINELOOPUNROLL
Definition at line 27 of file LoopUnroll.cpp.
Function Documentation
gatherInnermostLoops()
static void gatherInnermostLoops (func::FuncOp f, SmallVectorImpl< AffineForOp > & loops) static
Gathers loops that have no affine.for's nested within.
Definition at line 81 of file LoopUnroll.cpp.
References isInnermostAffineForOp().
isInnermostAffineForOp()
static bool isInnermostAffineForOp (AffineForOp op) static
Returns true if no other affine.for ops are nested within op.
Definition at line 72 of file LoopUnroll.cpp.
References mlir::WalkResult::interrupt().
Referenced by gatherInnermostLoops().