MLIR: lib/Bindings/Python/MainModule.cpp File Reference
MainModule.cpp File Reference
#include <tuple>
#include "PybindUtils.h"
#include "Globals.h"
#include "IRModule.h"
#include "Pass.h"
Functions
PYBIND11_MODULE (_mlir, m)
Function Documentation
PYBIND11_MODULE()
PYBIND11_MODULE (_mlir , m)
Definition at line 25 of file MainModule.cpp.
References mlir::python::PyOpView::createRawSubclass(), mlir::python::PyGlobals::get(), mlir::python::PyGlobals::getDialectSearchPrefixes(), mlir::python::populateIRAffine(), mlir::python::populateIRAttributes(), mlir::python::populateIRCore(), mlir::python::populateIRInterfaces(), mlir::python::populateIRTypes(), mlir::python::populatePassManagerSubmodule(), mlir::python::PyGlobals::registerDialectImpl(), mlir::python::PyGlobals::registerOperationImpl(), and mlir::python::PyGlobals::setDialectSearchPrefixes().