MLIR: lib/Analysis/Presburger/Matrix.cpp File Reference
Matrix.cpp File Reference
#include "mlir/Analysis/Presburger/Matrix.h"
#include "mlir/Analysis/Presburger/Utils.h"
#include "llvm/Support/MathExtras.h"
Functions
static void modEntryColumnOperation (Matrix &m, unsigned row, unsigned sourceCol, unsigned targetCol, Matrix &otherMatrix)
Set M(row, targetCol) to its remainder on division by M(row, sourceCol) by subtracting from column targetCol an appropriate integer multiple of sourceCol.
Function Documentation
modEntryColumnOperation()
static void modEntryColumnOperation (Matrix & m, unsigned row, unsigned sourceCol, unsigned targetCol, Matrix & otherMatrix) static
Set M(row, targetCol) to its remainder on division by M(row, sourceCol) by subtracting from column targetCol an appropriate integer multiple of sourceCol.
This brings M(row, targetCol) to the range [0, M(row, sourceCol)). Apply the same column operation to otherMatrix, with the same integer multiple.
Definition at line 260 of file Matrix.cpp.
References mlir::presburger::Matrix::addToColumn(), and mlir::presburger::floorDiv().
Referenced by mlir::presburger::Matrix::computeHermiteNormalForm().