MLIR: include/mlir-c/Dialect/Linalg.h File Reference
Linalg.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
#include "mlir/Dialect/Linalg/Passes.capi.h.inc"
Functions
MLIR_CAPI_EXPORTED void mlirLinalgFillBuiltinNamedOpRegion (MlirOperation mlirOp)
Apply the special region builder for the builtin named Linalg op.
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Linalg, linalg)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Linalg , linalg)
mlirLinalgFillBuiltinNamedOpRegion()
MLIR_CAPI_EXPORTED void mlirLinalgFillBuiltinNamedOpRegion (MlirOperation mlirOp)
Apply the special region builder for the builtin named Linalg op.
Assert that mlirOp is a builtin named Linalg op.
Assert that op is a builtin named Linalg op.
Definition at line 18 of file Linalg.cpp.
References mlir::OpBuilder::createBlock(), mlir::Operation::getAttrs(), mlir::Region::getBlocks(), mlir::Operation::getContext(), mlir::getElementTypeOrSelf(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), mlir::OperationName::getStringRef(), mlir::OpBuilder::setInsertionPointToStart(), and unwrap().
Referenced by populateDialectLinalgSubmodule().