MLIR: mlir::shape Namespace Reference
mlir::shape Namespace Reference
Classes
struct ShapeMappingValue
ShapeMappingValue works as the value of ShapeMappingAnalysis table, where funcSymbol is the symbol of mapping function, and inputs are the actual parameters for the function.
struct ShapeMappingAnalysis
ShapeMappingAnalysis is used together with OutlineShapeComputationPass to preserve Value and corresponding shape function / arguments mapping information.
Functions
RankedTensorType getExtentTensorType (MLIRContext *ctx, int64_t rank=ShapedType::kDynamicSize)
Alias type for extent tensors.
bool isExtentTensorType (Type)
LogicalResult getShapeVec (Value input, SmallVectorImpl< int64_t > &shapeValues)
void registerBufferizableOpInterfaceExternalModels (DialectRegistry &registry)
Function Documentation
getExtentTensorType()
RankedTensorType mlir::shape::getExtentTensorType (MLIRContext * ctx, int64_t rank = ShapedType::kDynamicSize)
Alias type for extent tensors.
Definition at line 39 of file Shape.cpp.
getShapeVec()
LogicalResult mlir::shape::getShapeVec (Value input, SmallVectorImpl< int64_t > & shapeValues)
Definition at line 48 of file Shape.cpp.
References mlir::failure(), mlir::Value::getDefiningOp(), mlir::m_Constant(), mlir::matchPattern(), and mlir::success().
isExtentTensorType()
bool mlir::shape::isExtentTensorType (Type type)
Definition at line 43 of file Shape.cpp.
References mlir::Type::dyn_cast().
registerBufferizableOpInterfaceExternalModels()
void mlir::shape::registerBufferizableOpInterfaceExternalModels (DialectRegistry & registry)
Definition at line 153 of file BufferizableOpInterfaceImpl.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::registerAllDialects().