MLIR: mlir::transform::detail Namespace Reference
mlir::transform::detail Namespace Reference
Functions
void checkImplementsTransformOpInterface (StringRef name, MLIRContext *context)
Asserts that the operations provided as template arguments implement the TransformOpInterface and MemoryEffectsOpInterface.
void checkImplementsTransformTypeInterface (TypeID typeID, MLIRContext *context)
Asserts that the type provided as template argument implements the TransformTypeInterface.
LogicalResult mapPossibleTopLevelTransformOpBlockArguments (TransformState &state, Operation *op, Region &region)
Maps the only block argument of the op with PossibleTopLevelTransformOpTrait to either the list of operations associated with its operand or the root of the payload IR, depending on what is available in the context.
LogicalResult verifyPossibleTopLevelTransformOpTrait (Operation *op)
Verification hook for PossibleTopLevelTransformOpTrait.
template<typename FnTy >
DiagnosedSilenceableFailure applyTransformToEach (Location loc, int expectedNumResults, ArrayRef< Operation * > targets, SmallVectorImpl< SmallVector< Operation * >> &results, FnTy transform)
Applies a one-to-one or a one-to-many transform to each of the given targets.
static SmallVector< SmallVector< Operation *, 1 > > transposeResults (const SmallVector< SmallVector< Operation * >, 1 > &m)
Helper function: transpose MxN into NxM; assumes that the input is a valid.
Function Documentation
applyTransformToEach()
template<typename FnTy > DiagnosedSilenceableFailure mlir::transform::detail::applyTransformToEach (Location loc, int expectedNumResults, ArrayRef< Operation * > targets, SmallVectorImpl< SmallVector< Operation * >> & results, FnTy transform)
Applies a one-to-one or a one-to-many transform to each of the given targets.
Puts the results of transforms, if any, in results in the same order. Fails if any of the application fails. Individual transforms must be callable with the following signature:
DiagnosedSilenceableFailure(OpTy, SmallVector<Operation*> &results, state) where OpTy is either
Operation *, in which case the transform is always applied;
a concrete Op class, in which case a check is performed whether targets contains operations of the same class and a silenceable failure is reported if it does not.
Definition at line 918 of file TransformInterfaces.h.
References diag(), mlir::Error, mlir::DiagnosedSilenceableFailure::isDefiniteFailure(), mlir::DiagnosedSilenceableFailure::isSilenceableFailure(), mlir::DiagnosedSilenceableFailure::silenceableFailure(), mlir::DiagnosedSilenceableFailure::success(), mlir::DiagnosedSilenceableFailure::takeDiagnostics(), and value.
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply().
checkImplementsTransformOpInterface()
void mlir::transform::detail::checkImplementsTransformOpInterface (StringRef name, MLIRContext * context)
Asserts that the operations provided as template arguments implement the TransformOpInterface and MemoryEffectsOpInterface.
This must be a dynamic assertion since interface implementations may be registered at runtime.
Definition at line 22 of file TransformDialect.cpp.
References mlir::OperationName::hasInterface(), mlir::RegisteredOperationName::hasTrait(), and mlir::RegisteredOperationName::lookup().
checkImplementsTransformTypeInterface()
void mlir::transform::detail::checkImplementsTransformTypeInterface (TypeID typeID, MLIRContext * context)
Asserts that the type provided as template argument implements the TransformTypeInterface.
This must be a dynamic assertion since interface implementations may be registered at runtime.
Definition at line 38 of file TransformDialect.cpp.
References mlir::AbstractType::lookup().
mapPossibleTopLevelTransformOpBlockArguments()
LogicalResult mlir::transform::detail::mapPossibleTopLevelTransformOpBlockArguments (TransformState & state, Operation * op, Region & region)
Maps the only block argument of the op with PossibleTopLevelTransformOpTrait to either the list of operations associated with its operand or the root of the payload IR, depending on what is available in the context.
Definition at line 338 of file TransformInterfaces.cpp.
References mlir::Region::front(), mlir::Block::getArgument(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::transform::TransformState::getPayloadOps(), mlir::transform::TransformState::getTopLevel(), and mlir::transform::TransformState::mapBlockArguments().
Referenced by mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::mapBlockArguments().
transposeResults()
static SmallVector<SmallVector<Operation *, 1> > mlir::transform::detail::transposeResults (const SmallVector< SmallVector< Operation * >, 1 > & m) inline static
Helper function: transpose MxN into NxM; assumes that the input is a valid.
Definition at line 958 of file TransformInterfaces.h.
verifyPossibleTopLevelTransformOpTrait()
LogicalResult mlir::transform::detail::verifyPossibleTopLevelTransformOpTrait (Operation * op)
Verification hook for PossibleTopLevelTransformOpTrait.
Definition at line 350 of file TransformInterfaces.cpp.
References diag(), mlir::Operation::emitOpError(), mlir::Region::front(), mlir::Block::getArgumentTypes(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getNumRegions(), mlir::Operation::getParentWithTrait(), mlir::Operation::getRegion(), and mlir::success().
Referenced by mlir::transform::PossibleTopLevelTransformOpTrait< OpTy >::verifyTrait().