MLIR: mlir::sparse_tensor::detail Namespace Reference
mlir::sparse_tensor::detail Namespace Reference
Classes
struct is_complex
struct is_complex< std::complex< T > >
class PermutationRef
A non-owning class for capturing the knowledge that isPermutation is true, to avoid needing to assert it repeatedly.
Functions
template<typename T , typename U >
constexpr bool safelyEQ (T t, U u) noexcept
template<typename T , typename U >
constexpr bool safelyNE (T t, U u) noexcept
template<typename T , typename U >
constexpr bool safelyLT (T t, U u) noexcept
template<typename T , typename U >
constexpr bool safelyGT (T t, U u) noexcept
template<typename T , typename U >
constexpr bool safelyLE (T t, U u) noexcept
template<typename T , typename U >
constexpr bool safelyGE (T t, U u) noexcept
template<typename To , typename From >
To checkOverflowCast (From x)
A version of static_cast<To> which checks for overflow/underflow.
uint64_t checkedMul (uint64_t lhs, uint64_t rhs)
A version of operator* on uint64_t which guards against overflows (when assertions are enabled).
template<typename V >
std::enable_if_t<!is_complex< V >::value, V > readCOOValue (char **linePtr, bool is_pattern)
Reads an element of a non-complex type for the current indices in coordinate scheme.
template<typename V >
std::enable_if_t< is_complex< V >::value, V > readCOOValue (char **linePtr, bool is_pattern)
Reads an element of a complex type for the current indices in coordinate scheme.
MLIR_SPARSETENSOR_PURE bool isPermutation (uint64_t size, const uint64_t *perm)
Checks whether the perm array is a permutation of [0 .. size).
void assertIsPermutation (uint64_t size, const uint64_t *perm)
Wrapper around isPermutation to ensure consistent error messages.
Function Documentation
assertIsPermutation()
void mlir::sparse_tensor::detail::assertIsPermutation (uint64_t size, const uint64_t * perm) inline
Wrapper around isPermutation to ensure consistent error messages.
Definition at line 39 of file PermutationRef.h.
References isPermutation(), and MLIR_SPARSETENSOR_FATAL.
Referenced by mlir::sparse_tensor::detail::PermutationRef::PermutationRef().
checkedMul()
uint64_t mlir::sparse_tensor::detail::checkedMul (uint64_t lhs, uint64_t rhs) inline
A version of operator* on uint64_t which guards against overflows (when assertions are enabled).
Definition at line 138 of file ArithmeticUtils.h.
Referenced by mlir::sparse_tensor::SparseTensorNNZ::SparseTensorNNZ(), and mlir::sparse_tensor::SparseTensorStorage< P, I, V >::SparseTensorStorage().
checkOverflowCast()
template<typename To , typename From > To mlir::sparse_tensor::detail::checkOverflowCast (From x) inline
A version of static_cast<To> which checks for overflow/underflow.
The implementation avoids performing runtime assertions whenever the types alone are sufficient to statically prove that overflow cannot happen.
Definition at line 121 of file ArithmeticUtils.h.
References max(), min(), safelyGE(), and safelyLE().
isPermutation()
bool mlir::sparse_tensor::detail::isPermutation (uint64_t size, const uint64_t * perm)
Checks whether the perm array is a permutation of [0 .. size).
Definition at line 15 of file PermutationRef.cpp.
Referenced by assertIsPermutation().
readCOOValue() [1/2]
template<typename V > std::enable_if_t<!is_complex<V>::value, V> mlir::sparse_tensor::detail::readCOOValue (char ** linePtr, bool is_pattern) inline
Reads an element of a non-complex type for the current indices in coordinate scheme.
Definition at line 49 of file File.h.
readCOOValue() [2/2]
template<typename V > std::enable_if_t<is_complex<V>::value, V> mlir::sparse_tensor::detail::readCOOValue (char ** linePtr, bool is_pattern) inline
Reads an element of a complex type for the current indices in coordinate scheme.
Definition at line 59 of file File.h.
safelyEQ()
template<typename T , typename U > constexpr bool mlir::sparse_tensor::detail::safelyEQ (T t, U u) constexpr noexcept
Definition at line 53 of file ArithmeticUtils.h.
Referenced by safelyNE().
safelyGE()
template<typename T , typename U > constexpr bool mlir::sparse_tensor::detail::safelyGE (T t, U u) constexpr noexcept
Definition at line 92 of file ArithmeticUtils.h.
References safelyLT().
Referenced by checkOverflowCast().
safelyGT()
template<typename T , typename U > constexpr bool mlir::sparse_tensor::detail::safelyGT (T t, U u) constexpr noexcept
Definition at line 82 of file ArithmeticUtils.h.
References safelyLT().
Referenced by safelyLE().
safelyLE()
template<typename T , typename U > constexpr bool mlir::sparse_tensor::detail::safelyLE (T t, U u) constexpr noexcept
Definition at line 87 of file ArithmeticUtils.h.
References safelyGT().
Referenced by checkOverflowCast().
safelyLT()
template<typename T , typename U > constexpr bool mlir::sparse_tensor::detail::safelyLT (T t, U u) constexpr noexcept
Definition at line 70 of file ArithmeticUtils.h.
Referenced by safelyGE(), and safelyGT().
safelyNE()
template<typename T , typename U > constexpr bool mlir::sparse_tensor::detail::safelyNE (T t, U u) constexpr noexcept
Definition at line 65 of file ArithmeticUtils.h.
References safelyEQ().