MLIR: mlir::nvgpu Namespace Reference
mlir::nvgpu Namespace Reference
Classes
struct WarpMatrixInfo
Collects information about a warp-level matrix operand represented by a VectorType.
struct FragmentElementInfo
Specifies information about the registers which compose a matrix fragment according to the PTX documentation.
struct LdMatrixParams
Encapsulates the parameters needed to lower a nvgpu.ldmatrix operation to nvvm.ldmatrix.
struct PrepareContractToGPUMMASync
Transform vector.contract into (m,k)x(n,k)x(m,n) form so that it can be converted to nvgpu.mma.sync.
Enumerations
enum class MmaSyncF32Lowering { TF32 = 0 , TF32x3 = 1 , Unkown = 2 }
Rewrites patterns.
enum class MatMulOperandRole : int32_t { A = 0 , B , C }
Represents the role of an operand in an MMA instruction: result := matmul(A, B) + C
Functions
std::unique_ptr< Pass > createOptimizeSharedMemoryPass ()
Create a pass to optimize shared memory reads and writes.
mlir::LogicalResult optimizeSharedMemoryReadsAndWrites (Operation *parentOp, Value memrefValue)
Passes.
void populateMmaSyncF32ToTF32Patterns (RewritePatternSet &patterns, nvgpu::MmaSyncF32Lowering precision=nvgpu::MmaSyncF32Lowering::TF32)
Collect patterns to convert mma.sync on f32 input and rewrite to use tensor cores with user provided level of accuracy: (a) tf32 (1 mma.sync per warp-level matrix-multiply-accumulate) (b) tf32x3 (3 mma.sync per warp-level matrix-multiply-accumulate) Typically, tf32 tensor core acceleration comes at a cost of accuracy from missing precision bits.
FailureOr< vector::ContractionOp > getUserContract (Operation *op)
Returns the first user of the op that is vector.contract.
FailureOr< WarpMatrixInfo > getWarpMatrixInfo (Operation *op)
If op is a vector.transfer_write, return the WarpMatrixInfo for the vector operand.
int64_t inferTileWidthInBits (const WarpMatrixInfo &type)
Returns the number of bits in a single tile row.
FailureOr< FragmentElementInfo > getMmaSyncRegisterType (const WarpMatrixInfo &type)
Returns a FragmentElementInfo struct describing the register types for the given matrix fragment type.
FailureOr< AffineMap > getLaneIdAndValueIdToOperandCoord (Location loc, OpBuilder &builder, const WarpMatrixInfo &fragmentType)
Returns an AffineMap which maps a two dimensions representing (laneId, logicalValueId) and returns two results representing offsets within a matrix operand.
FailureOr< LdMatrixParams > getLdMatrixParams (const WarpMatrixInfo &type, bool transpose)
Given type that contains info for a warp-matrix operand and whether or not the load is a transposed load, return the LdMatrixParams.
FailureOr< AffineMap > getLaneIdToLdMatrixMatrixCoord (Location loc, OpBuilder &builder, const LdMatrixParams &params)
Returns an AffineMap which maps a single dimension representing the laneId to two results representing offsets within the matrix operand that should be the pointer locations a thread should pass to the ldmatrix instruction.
Enumeration Type Documentation
MatMulOperandRole
enum mlir::nvgpu::MatMulOperandRole : int32_t strong
Represents the role of an operand in an MMA instruction: result := matmul(A, B) + C
Enumerator
A
B
C
Definition at line 26 of file MMAUtils.h.
MmaSyncF32Lowering
enum mlir::nvgpu::MmaSyncF32Lowering strong
Rewrites patterns.
Enum to control the lowering of nvgpu.mmasync.
Enumerator
TF32
TF32x3
Unkown
Definition at line 56 of file Transforms.h.
Function Documentation
createOptimizeSharedMemoryPass()
std::unique_ptr< Pass > mlir::nvgpu::createOptimizeSharedMemoryPass ()
Create a pass to optimize shared memory reads and writes.
Definition at line 278 of file OptimizeSharedMemory.cpp.
getLaneIdAndValueIdToOperandCoord()
FailureOr< AffineMap > mlir::nvgpu::getLaneIdAndValueIdToOperandCoord (Location loc, OpBuilder & builder, const WarpMatrixInfo & fragmentType)
Returns an AffineMap which maps a two dimensions representing (laneId, logicalValueId) and returns two results representing offsets within a matrix operand.
The offsets point to the values the thread is responsible for (AKA the matrix fragment values) during a warp-collective matrix operation. For a visual reference of this LaneId -> (row, col) mapping, please see NVIDIA's PTX documentation: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#warp-level-matrix-instructions-for-mma
Definition at line 173 of file MMAUtils.cpp.
References mlir::bindDims(), mlir::failed(), mlir::failure(), mlir::AffineExpr::floorDiv(), mlir::AffineMap::get(), mlir::Builder::getContext(), mlir::Type::getIntOrFloatBitWidth(), getMmaSyncRegisterType(), getRegisterIndexToTileOffsetMap(), mlir::AffineMap::getResult(), inferTileWidthInBits(), isAccumulatorOrResult(), kThreadsPerRow, mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertTransferWriteToStores(), and createNonLdMatrixLoads().
getLaneIdToLdMatrixMatrixCoord()
FailureOr< AffineMap > mlir::nvgpu::getLaneIdToLdMatrixMatrixCoord (Location loc, OpBuilder & builder, const LdMatrixParams & params)
Returns an AffineMap which maps a single dimension representing the laneId to two results representing offsets within the matrix operand that should be the pointer locations a thread should pass to the ldmatrix instruction.
Definition at line 238 of file MMAUtils.cpp.
References mlir::nvgpu::LdMatrixParams::contiguousDimType, mlir::failure(), mlir::AffineExpr::floorDiv(), mlir::nvgpu::LdMatrixParams::fragmentType, mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), and kNumRowsPerTile.
Referenced by creatLdMatrixCompatibleLoads().
getLdMatrixParams()
FailureOr< nvgpu::LdMatrixParams > mlir::nvgpu::getLdMatrixParams (const WarpMatrixInfo & type, bool transpose)
Given type that contains info for a warp-matrix operand and whether or not the load is a transposed load, return the LdMatrixParams.
Definition at line 209 of file MMAUtils.cpp.
References A, C, mlir::nvgpu::LdMatrixParams::contiguousDimType, mlir::failure(), mlir::nvgpu::LdMatrixParams::fragmentType, mlir::Type::getIntOrFloatBitWidth(), kNumRowsPerTile, mlir::nvgpu::LdMatrixParams::numTiles, mlir::nvgpu::WarpMatrixInfo::operandRole, mlir::nvgpu::LdMatrixParams::targetLayout, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by creatLdMatrixCompatibleLoads().
getMmaSyncRegisterType()
FailureOr< FragmentElementInfo > mlir::nvgpu::getMmaSyncRegisterType (const WarpMatrixInfo & type)
Returns a FragmentElementInfo struct describing the register types for the given matrix fragment type.
Definition at line 100 of file MMAUtils.cpp.
References mlir::failure(), mlir::LLVM::getFixedVectorType(), inferNumRegistersPerMatrixFragment(), isAccumulatorOrResult(), mlir::Type::isF16(), mlir::Type::isF32(), mlir::Type::isF64(), mlir::Type::isInteger(), mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertConstantOpMmaSync(), convertExtractStridedSlice(), convertTransferWriteToStores(), createNonLdMatrixLoads(), creatLdMatrixCompatibleLoads(), and getLaneIdAndValueIdToOperandCoord().
getUserContract()
FailureOr< vector::ContractionOp > mlir::nvgpu::getUserContract (Operation * op)
Returns the first user of the op that is vector.contract.
If no vector.contract user exists, return failure.
Definition at line 50 of file MMAUtils.cpp.
References mlir::failure(), and mlir::Operation::getUsers().
Referenced by extractStridedSliceSupportsMMAMatrixType(), and getWarpMatrixInfo().
getWarpMatrixInfo()
FailureOr< WarpMatrixInfo > mlir::nvgpu::getWarpMatrixInfo (Operation * op)
If op is a vector.transfer_write, return the WarpMatrixInfo for the vector operand.
If op is a vector.transfer_read, vector.contraction, or arith.constant, return the WarpMatrixInfo corresponding to the result. Otherwise, return failure.
Definition at line 58 of file MMAUtils.cpp.
References A, B, C, mlir::Type::cast(), mlir::Operation::emitError(), mlir::failed(), mlir::Operation::getResult(), mlir::Value::getType(), getUserContract(), mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertConstantOpMmaSync(), convertExtractStridedSlice(), convertTransferReadToLoads(), convertTransferWriteToStores(), createNonLdMatrixLoads(), creatLdMatrixCompatibleLoads(), and extractStridedSliceSupportsMMAMatrixType().
inferTileWidthInBits()
int64_t mlir::nvgpu::inferTileWidthInBits (const WarpMatrixInfo & type)
Returns the number of bits in a single tile row.
It is either 128, 256, or 512 bits depending on the data type and` whether the operand is an accumulator/result operand
Definition at line 87 of file MMAUtils.cpp.
References mlir::Type::getIntOrFloatBitWidth(), isAccumulatorOrResult(), mlir::nvgpu::WarpMatrixInfo::operandRole, and mlir::nvgpu::WarpMatrixInfo::vectorType.
Referenced by convertTransferReadToLoads(), getLaneIdAndValueIdToOperandCoord(), and inferNumRegistersPerMatrixFragment().
optimizeSharedMemoryReadsAndWrites()
mlir::LogicalResult mlir::nvgpu::optimizeSharedMemoryReadsAndWrites (Operation * parentOp, Value memrefValue)
Passes.
Optimizes vectorized accesses to a shared memory buffer specified by memrefValue. This transformation assumes the following: 1) All relevant accesses to memrefValue are contained with parentOp. 2) The function will fail precondition checks if any subviews are taken of memrefValue. All reads/writes to memrefValue should occur through memrefValue directly.
Shared memory bank conflicts occur when multiple threads attempt to read or write locations assigned to the same shared memory bank. For 2^N byte vectorized accesses, we need to be concerned with conflicts among threads identified as (tid) -> tid.floordiv(2^{7-N}). As such, this transformation changes any indexed memory access (vector.load, memref.load, nvgpu.ldmatrix, etc) such that the final dimension's index value is permuted such that newColIndex = oldColIndex % vectorSize + perm[rowIndex](oldColIndex/vectorSize, rowIndex) where rowIndex is the index for the second-to last dimension and perm[rowIndex] is a permutation function that depends on the row Index. The permutation function is chosen to ensure that sequential distributed+vectorized reads/writes down a single dimension of the memref have minimal conflicts.
Definition at line 181 of file OptimizeSharedMemory.cpp.
References mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::Operation::getContext(), getIndices(), mlir::Operation::getLoc(), getShmReadAndWriteOps(), mlir::Value::getType(), kDefaultVectorSizeBits, kSharedMemoryLineSizeBytes, setIndices(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), transformIndices(), and mlir::Operation::walk().
populateMmaSyncF32ToTF32Patterns()
void mlir::nvgpu::populateMmaSyncF32ToTF32Patterns (RewritePatternSet & patterns, nvgpu::MmaSyncF32Lowering precision = nvgpu::MmaSyncF32Lowering::TF32)
Collect patterns to convert mma.sync on f32 input and rewrite to use tensor cores with user provided level of accuracy: (a) tf32 (1 mma.sync per warp-level matrix-multiply-accumulate) (b) tf32x3 (3 mma.sync per warp-level matrix-multiply-accumulate) Typically, tf32 tensor core acceleration comes at a cost of accuracy from missing precision bits.
While f32 has 23 precision bits, tf32 has only 10 precision bits. tf32x3 aims to recover the precision bits by spliting each operand into two tf32 values and issue three mma.sync tensor core operations.
Definition at line 69 of file MmaSyncTF32Transform.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().