MLIR: mlir::transform::gpu Namespace Reference
mlir::transform::gpu Namespace Reference
Functions
DiagnosedSilenceableFailure mapNestedForeachToThreadsImpl (RewriterBase &rewriter, Operation *target, const SmallVectorImpl< int64_t > &blockDim, bool syncAfterDistribute, llvm::Optional< TransformOpInterface > transformOp, const ArrayRef< DeviceMappingAttrInterface > &threadMappingAttributes)
Searches scf.foreach_thread ops nested under target and maps each such op to GPU threads.
DiagnosedSilenceableFailure mapForeachToBlocksImpl (RewriterBase &rewriter, scf::ForeachThreadOp foreachThreadOp, function_ref< void(RewriterBase &, scf::ForeachThreadOp, SmallVectorImpl< Value > &)> blockIdGenerator, SmallVectorImpl< int64_t > &gridDims, TransformOpInterface transformOp, const ArrayRef< DeviceMappingAttrInterface > &mappingAttributes)
Maps the top level scf.foreach_thread op to GPU Thread Blocks.
DiagnosedSilenceableFailure findTopLevelForeachThreadOp (Operation *target, scf::ForeachThreadOp &topLevelForeachThreadOp, TransformOpInterface transformOp)
Finds the top level scf::ForeachThreadOp of given target.
Function Documentation
findTopLevelForeachThreadOp()
DiagnosedSilenceableFailure mlir::transform::gpu::findTopLevelForeachThreadOp (Operation * target, scf::ForeachThreadOp & topLevelForeachThreadOp, TransformOpInterface transformOp)
Finds the top level scf::ForeachThreadOp of given target.
Definition at line 260 of file GPUTransformOps.cpp.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), mlir::DiagnosedSilenceableFailure::success(), and mlir::Operation::walk().
mapForeachToBlocksImpl()
DiagnosedSilenceableFailure mlir::transform::gpu::mapForeachToBlocksImpl (RewriterBase & rewriter, scf::ForeachThreadOp foreachThreadOp, function_ref< void(RewriterBase &, scf::ForeachThreadOp, SmallVectorImpl< Value > &)> blockIdGenerator, SmallVectorImpl< int64_t > & gridDims, TransformOpInterface transformOp, const ArrayRef< DeviceMappingAttrInterface > & mappingAttributes)
Maps the top level scf.foreach_thread op to GPU Thread Blocks.
Mapping is one-to-one and the induction variables of scf.foreach_thread are rewritten to gpu.block_id according to the thread_dim_apping attribute. Dynamic, scf.foreach_thread trip counts are currently not supported. Dynamic block dim sizes are currently not supported.
Definition at line 174 of file GPUTransformOps.cpp.
References mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::Block::front(), mlir::Value::getDefiningOp(), mlir::Block::getOperations(), mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::map(), mlir::RewriterBase::replaceAllUsesWith(), mlir::DiagnosedSilenceableFailure::success(), and mlir::arith::ConstantIndexOp::value().
mapNestedForeachToThreadsImpl()
DiagnosedSilenceableFailure mlir::transform::gpu::mapNestedForeachToThreadsImpl (RewriterBase & rewriter, Operation * target, const SmallVectorImpl< int64_t > & blockDim, bool syncAfterDistribute, llvm::Optional< TransformOpInterface > transformOp, const ArrayRef< DeviceMappingAttrInterface > & threadMappingAttributes)
Searches scf.foreach_thread ops nested under target and maps each such op to GPU threads.
Mapping is one-to-one and the induction variables of scf.foreach_thread are rewritten to gpu.thread_id according to the thread_dim_apping attribute. Sibling scf.foreach_thread are supported in which case, the union of the number of threads is computed and may result in predication. Dynamic, scf.foreach_thread trip counts are currently not supported. Dynamic block dim sizes are currently not supported.
Definition at line 505 of file GPUTransformOps.cpp.
References mlir::WalkResult::advance(), checkAttributeType(), diag(), mlir::WalkResult::interrupt(), rewriteOneForeachThreadToGpuThreads(), mlir::OpBuilder::setInsertionPoint(), mlir::DiagnosedSilenceableFailure::success(), and mlir::Operation::walk().