MLIR: mlir::LLVM::detail Namespace Reference
mlir::LLVM::detail Namespace Reference
Classes
struct NDVectorTypeInfo
struct LLVMStructTypeStorage
Type storage for LLVM structure types.
struct LLVMTypeAndSizeStorage
Common storage used for LLVM dialect types that need an element type and a number: arrays, fixed and scalable vectors.
class DebugTranslation
class TypeFromLLVMIRTranslatorImpl
Support for translating LLVM IR types to MLIR LLVM dialect types.
class TypeToLLVMIRTranslatorImpl
Support for translating MLIR LLVM dialect types to LLVM IR.
Functions
LogicalResult oneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, ArrayRef< NamedAttribute > targetAttrs, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
NDVectorTypeInfo extractNDVectorTypeInfo (VectorType vectorType, LLVMTypeConverter &converter)
SmallVector< int64_t, 4 > getCoordinates (ArrayRef< int64_t > basis, unsigned linearIndex)
void nDVectorIterate (const NDVectorTypeInfo &info, OpBuilder &builder, function_ref< void(ArrayRef< int64_t >)> fun)
LogicalResult handleMultidimensionalVectors (Operation *op, ValueRange operands, LLVMTypeConverter &typeConverter, std::function< Value(Type, ValueRange)> createOperand, ConversionPatternRewriter &rewriter)
LogicalResult vectorOneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, ArrayRef< NamedAttribute > targetAttrs, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Type parseType (DialectAsmParser &parser)
Parses an LLVM dialect type.
void printType (Type type, AsmPrinter &printer)
Prints an LLVM Dialect type.
void connectPHINodes (Region &region, const ModuleTranslation &state)
For all blocks in the region that were converted to LLVM IR using the given ModuleTranslation, connect the PHI nodes of the corresponding LLVM IR blocks to the results of preceding blocks.
SetVector< Block * > getTopologicallySortedBlocks (Region &region)
Get a topologically sorted list of blocks of the given region.
llvm::Constant * getLLVMConstant (llvm::Type *llvmType, Attribute attr, Location loc, const ModuleTranslation &moduleTranslation)
Create an LLVM IR constant of llvmType from the MLIR attribute attr.
llvm::Value * createIntrinsicCall (llvm::IRBuilderBase &builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value * > args={}, ArrayRef< llvm::Type * > tys={})
Creates a call to an LLVM IR intrinsic function with the given arguments.
Function Documentation
connectPHINodes()
void mlir::LLVM::detail::connectPHINodes (Region & region, const ModuleTranslation & state)
For all blocks in the region that were converted to LLVM IR using the given ModuleTranslation, connect the PHI nodes of the corresponding LLVM IR blocks to the results of preceding blocks.
Connect the PHI nodes to the results of preceding blocks.
Definition at line 499 of file ModuleTranslation.cpp.
References mlir::detail::enumerate(), getPHISourceValue(), mlir::LLVM::ModuleTranslation::lookupBlock(), mlir::LLVM::ModuleTranslation::lookupBranch(), and mlir::LLVM::ModuleTranslation::lookupValue().
Referenced by convertOmpOpRegions().
createIntrinsicCall()
llvm::Value * mlir::LLVM::detail::createIntrinsicCall (llvm::IRBuilderBase & builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value * > args = {}, ArrayRef< llvm::Type * > tys = {})
Creates a call to an LLVM IR intrinsic function with the given arguments.
Definition at line 546 of file ModuleTranslation.cpp.
extractNDVectorTypeInfo()
LLVM::detail::NDVectorTypeInfo mlir::LLVM::detail::extractNDVectorTypeInfo (VectorType vectorType, LLVMTypeConverter & converter)
Definition at line 19 of file VectorPattern.cpp.
References mlir::LLVM::detail::NDVectorTypeInfo::arraySizes, mlir::LLVMTypeConverter::convertType(), getElementType(), mlir::LLVM::isCompatibleType(), mlir::LLVM::isCompatibleVectorType(), mlir::LLVM::detail::NDVectorTypeInfo::llvm1DVectorTy, and mlir::LLVM::detail::NDVectorTypeInfo::llvmNDVectorTy.
Referenced by handleMultidimensionalVectors().
getCoordinates()
SmallVector< int64_t, 4 > mlir::LLVM::detail::getCoordinates (ArrayRef< int64_t > basis, unsigned linearIndex)
Definition at line 48 of file VectorPattern.cpp.
Referenced by nDVectorIterate().
getLLVMConstant()
llvm::Constant * mlir::LLVM::detail::getLLVMConstant (llvm::Type * llvmType, Attribute attr, Location loc, const ModuleTranslation & moduleTranslation)
Create an LLVM IR constant of llvmType from the MLIR attribute attr.
This currently supports integer, floating point, splat and dense element attributes and combinations thereof. Also, an array attribute with two elements is supported to represent a complex constant. In case of error, report it to loc and return nullptr.
Definition at line 288 of file ModuleTranslation.cpp.
References buildSequentialConstant(), convertDenseElementsAttr(), mlir::Attribute::dyn_cast(), mlir::emitError(), getInnermostElementType(), mlir::LLVM::ModuleTranslation::getLLVMContext(), and mlir::LLVM::ModuleTranslation::lookupFunction().
Referenced by convertDenseElementsAttr().
getTopologicallySortedBlocks()
SetVector< Block * > mlir::LLVM::detail::getTopologicallySortedBlocks (Region & region)
Get a topologically sorted list of blocks of the given region.
Sort function blocks topologically.
Definition at line 530 of file ModuleTranslation.cpp.
References mlir::Region::getBlocks().
Referenced by convertDataOp(), and convertOmpOpRegions().
handleMultidimensionalVectors()
LogicalResult mlir::LLVM::detail::handleMultidimensionalVectors (Operation * op, ValueRange operands, LLVMTypeConverter & typeConverter, std::function< Value(Type, ValueRange)> createOperand, ConversionPatternRewriter & rewriter)
Definition at line 80 of file VectorPattern.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), extractNDVectorTypeInfo(), mlir::Operation::getLoc(), mlir::Operation::getResult(), mlir::Value::getType(), nDVectorIterate(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
nDVectorIterate()
void mlir::LLVM::detail::nDVectorIterate (const NDVectorTypeInfo & info, OpBuilder & builder, function_ref< void(ArrayRef< int64_t >)> fun)
Definition at line 64 of file VectorPattern.cpp.
References mlir::LLVM::detail::NDVectorTypeInfo::arraySizes, and getCoordinates().
Referenced by handleMultidimensionalVectors().
oneToOneRewrite()
LogicalResult mlir::LLVM::detail::oneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, ArrayRef< NamedAttribute > targetAttrs, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
Definition at line 309 of file Pattern.cpp.
References mlir::OpBuilder::create(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), mlir::Builder::getStringAttr(), mlir::LLVMTypeConverter::packFunctionResults(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
Referenced by mlir::OneToOneConvertToLLVMPattern< SourceOp, TargetOp >::matchAndRewrite(), and vectorOneToOneRewrite().
parseType()
Type mlir::LLVM::detail::parseType (DialectAsmParser & parser)
Parses an LLVM dialect type.
Parses one of the LLVM dialect types.
Definition at line 347 of file LLVMTypeSyntax.cpp.
printType()
void mlir::LLVM::detail::printType (Type type, AsmPrinter & printer)
Prints an LLVM Dialect type.
Prints the given LLVM dialect type recursively.
This leverages closedness of the LLVM dialect type system to avoid printing the dialect prefix repeatedly. For recursive structures, only prints the name of the structure when printing a self-reference. Note that this does not apply to sibling references. For example, struct<"a", (ptr<struct<"a">>)> struct<"c", (ptr<struct<"b", (ptr<struct<"c">>)>>, ptr<struct<"b", (ptr<struct<"c">>)>>)> note that "b" is printed twice.
Definition at line 111 of file LLVMTypeSyntax.cpp.
Referenced by dispatchPrint().
vectorOneToOneRewrite()
LogicalResult mlir::LLVM::detail::vectorOneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, ArrayRef< NamedAttribute > targetAttrs, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Definition at line 106 of file VectorPattern.cpp.
References mlir::OpBuilder::create(), mlir::failure(), mlir::Operation::getLoc(), mlir::Builder::getStringAttr(), mlir::ValueRange::getType(), mlir::ValueRange::getTypes(), handleMultidimensionalVectors(), mlir::LLVM::isCompatibleType(), and oneToOneRewrite().
Referenced by mlir::VectorConvertToLLVMPattern< SourceOp, TargetOp, AttrConvert >::matchAndRewrite().