MLIR: lib/TableGen/Operator.cpp File Reference
Operator.cpp File Reference
#include "mlir/TableGen/Operator.h"
#include "mlir/TableGen/Predicate.h"
#include "mlir/TableGen/Trait.h"
#include "mlir/TableGen/Type.h"
#include "llvm/ADT/EquivalenceClasses.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
Macros
#define DEBUG_TYPE "mlir-tblgen-operator"
Functions
static int resultIndex (int i)
static SmallVector< std::string, 2 > getGetterOrSetterNames (bool isGetter, const Operator &op, StringRef name)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-tblgen-operator"
Definition at line 29 of file Operator.cpp.
Function Documentation
getGetterOrSetterNames()
static SmallVector<std::string, 2> getGetterOrSetterNames (bool isGetter, const Operator & op, StringRef name) static
Definition at line 697 of file Operator.cpp.
References mlir::tblgen::Dialect::Both, mlir::tblgen::Operator::getDialect(), mlir::tblgen::Dialect::getEmitAccessorPrefix(), mlir::tblgen::Operator::getLoc(), mlir::tblgen::Operator::getNumOperands(), mlir::tblgen::Operator::getNumRegions(), mlir::tblgen::Operator::getNumResults(), mlir::tblgen::Operator::getNumVariableLengthOperands(), mlir::tblgen::Operator::getNumVariadicRegions(), mlir::tblgen::Operator::getQualCppClassName(), and mlir::tblgen::Dialect::Raw.
Referenced by mlir::tblgen::Operator::getGetterNames(), and mlir::tblgen::Operator::getSetterNames().
resultIndex()
static int resultIndex (int i) static
Definition at line 308 of file Operator.cpp.