MLIR: lib/Analysis/Presburger/PWMAFunction.cpp File Reference
PWMAFunction.cpp File Reference
#include "mlir/Analysis/Presburger/PWMAFunction.h"
#include "mlir/Analysis/Presburger/Simplex.h"
Functions
static SmallVector< MPInt, 8 > subtractExprs (ArrayRef< MPInt > vecA, ArrayRef< MPInt > vecB)
template<bool lexMin>
static PresburgerSet tiebreakLex (const PWMAFunction::Piece &pieceA, const PWMAFunction::Piece &pieceB)
A tiebreak function which breaks ties by comparing the outputs lexicographically.
static void addDivisionConstraints (IntegerRelation &rel, const DivisionRepr &divs)
Adds division constraints corresponding to local variables, given a relation and division representations of the local variables in the relation.
Function Documentation
addDivisionConstraints()
static void addDivisionConstraints (IntegerRelation & rel, const DivisionRepr & divs) static
Adds division constraints corresponding to local variables, given a relation and division representations of the local variables in the relation.
Definition at line 362 of file PWMAFunction.cpp.
References mlir::presburger::IntegerRelation::addInequality(), mlir::presburger::DivisionRepr::getDenom(), mlir::presburger::DivisionRepr::getDividend(), mlir::presburger::getDivLowerBound(), mlir::presburger::DivisionRepr::getDivOffset(), mlir::presburger::getDivUpperBound(), mlir::presburger::DivisionRepr::getNumDivs(), mlir::presburger::IntegerRelation::getNumLocalVars(), mlir::presburger::IntegerRelation::getNumVars(), mlir::presburger::DivisionRepr::getNumVars(), and mlir::presburger::DivisionRepr::hasAllReprs().
Referenced by mlir::presburger::MultiAffineFunction::getAsRelation().
subtractExprs()
static SmallVector<MPInt, 8> subtractExprs (ArrayRef< MPInt > vecA, ArrayRef< MPInt > vecB) static
Definition at line 32 of file PWMAFunction.cpp.
Referenced by tiebreakLex().
tiebreakLex()
template<bool lexMin> static PresburgerSet tiebreakLex (const PWMAFunction::Piece & pieceA, const PWMAFunction::Piece & pieceB) static
A tiebreak function which breaks ties by comparing the outputs lexicographically.
If lexMin is true, then the ties are broken by taking the lexicographically smaller output and otherwise, by taking the lexicographically larger output.
Definition at line 269 of file PWMAFunction.cpp.
References mlir::presburger::IntegerRelation::addBound(), mlir::presburger::IntegerRelation::addEquality(), mlir::presburger::PWMAFunction::Piece::domain, mlir::presburger::PresburgerSet::getEmpty(), mlir::presburger::PresburgerSpace::getNumLocalVars(), mlir::presburger::MultiAffineFunction::getNumOutputs(), mlir::presburger::PresburgerSpace::getNumVars(), mlir::presburger::MultiAffineFunction::getOutputExpr(), mlir::presburger::PresburgerRelation::getSpace(), mlir::presburger::MultiAffineFunction::getSpace(), mlir::presburger::PresburgerSet::intersect(), mlir::presburger::PresburgerSpace::isCompatible(), mlir::presburger::PWMAFunction::Piece::output, mlir::presburger::IntegerRelation::removeInequality(), subtractExprs(), and mlir::presburger::PresburgerRelation::unionInPlace().