MLIR: lib/ExecutionEngine/RunnerUtils.cpp File Reference
RunnerUtils.cpp File Reference
#include "mlir/ExecutionEngine/RunnerUtils.h"
#include <chrono>
Functions
void _mlir_ciface_printMemrefShapeI8 (UnrankedMemRefType< int8_t > *M)
void _mlir_ciface_printMemrefShapeI32 (UnrankedMemRefType< int32_t > *M)
void _mlir_ciface_printMemrefShapeI64 (UnrankedMemRefType< int64_t > *M)
void _mlir_ciface_printMemrefShapeF32 (UnrankedMemRefType< float > *M)
void _mlir_ciface_printMemrefShapeF64 (UnrankedMemRefType< double > *M)
void _mlir_ciface_printMemrefVector4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > *M)
void _mlir_ciface_printMemrefI8 (UnrankedMemRefType< int8_t > *M)
void _mlir_ciface_printMemrefI32 (UnrankedMemRefType< int32_t > *M)
void _mlir_ciface_printMemrefI64 (UnrankedMemRefType< int64_t > *M)
void _mlir_ciface_printMemrefF32 (UnrankedMemRefType< float > *M)
void _mlir_ciface_printMemrefF64 (UnrankedMemRefType< double > *M)
int64_t _mlir_ciface_nanoTime ()
void printMemrefI32 (int64_t rank, void *ptr)
void printMemrefI64 (int64_t rank, void *ptr)
void printMemrefF32 (int64_t rank, void *ptr)
void printMemrefF64 (int64_t rank, void *ptr)
void printCString (char *str)
void _mlir_ciface_printMemref0dF32 (StridedMemRefType< float, 0 > *M)
void _mlir_ciface_printMemref1dF32 (StridedMemRefType< float, 1 > *M)
void _mlir_ciface_printMemref2dF32 (StridedMemRefType< float, 2 > *M)
void _mlir_ciface_printMemref3dF32 (StridedMemRefType< float, 3 > *M)
void _mlir_ciface_printMemref4dF32 (StridedMemRefType< float, 4 > *M)
int64_t _mlir_ciface_verifyMemRefI32 (UnrankedMemRefType< int32_t > *actual, UnrankedMemRefType< int32_t > *expected)
int64_t _mlir_ciface_verifyMemRefF32 (UnrankedMemRefType< float > *actual, UnrankedMemRefType< float > *expected)
int64_t _mlir_ciface_verifyMemRefF64 (UnrankedMemRefType< double > *actual, UnrankedMemRefType< double > *expected)
int64_t verifyMemRefI32 (int64_t rank, void *actualPtr, void *expectedPtr)
int64_t verifyMemRefF32 (int64_t rank, void *actualPtr, void *expectedPtr)
int64_t verifyMemRefF64 (int64_t rank, void *actualPtr, void *expectedPtr)
Function Documentation
_mlir_ciface_nanoTime()
int64_t _mlir_ciface_nanoTime ()
Definition at line 79 of file RunnerUtils.cpp.
_mlir_ciface_printMemref0dF32()
void _mlir_ciface_printMemref0dF32 (StridedMemRefType< float, 0 > * M)
Definition at line 109 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref1dF32()
void _mlir_ciface_printMemref1dF32 (StridedMemRefType< float, 1 > * M)
Definition at line 112 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref2dF32()
void _mlir_ciface_printMemref2dF32 (StridedMemRefType< float, 2 > * M)
Definition at line 115 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref3dF32()
void _mlir_ciface_printMemref3dF32 (StridedMemRefType< float, 3 > * M)
Definition at line 118 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemref4dF32()
void _mlir_ciface_printMemref4dF32 (StridedMemRefType< float, 4 > * M)
Definition at line 121 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemrefF32()
void _mlir_ciface_printMemrefF32 (UnrankedMemRefType< float > * M)
Definition at line 71 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefF32().
_mlir_ciface_printMemrefF64()
void _mlir_ciface_printMemrefF64 (UnrankedMemRefType< double > * M)
Definition at line 75 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefF64().
_mlir_ciface_printMemrefI32()
void _mlir_ciface_printMemrefI32 (UnrankedMemRefType< int32_t > * M)
Definition at line 63 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefI32().
_mlir_ciface_printMemrefI64()
void _mlir_ciface_printMemrefI64 (UnrankedMemRefType< int64_t > * M)
Definition at line 67 of file RunnerUtils.cpp.
References impl::printMemRef().
Referenced by printMemrefI64().
_mlir_ciface_printMemrefI8()
void _mlir_ciface_printMemrefI8 (UnrankedMemRefType< int8_t > * M)
Definition at line 59 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_printMemrefShapeF32()
void _mlir_ciface_printMemrefShapeF32 (UnrankedMemRefType< float > * M)
Definition at line 41 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeF64()
void _mlir_ciface_printMemrefShapeF64 (UnrankedMemRefType< double > * M)
Definition at line 48 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeI32()
void _mlir_ciface_printMemrefShapeI32 (UnrankedMemRefType< int32_t > * M)
Definition at line 28 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeI64()
void _mlir_ciface_printMemrefShapeI64 (UnrankedMemRefType< int64_t > * M)
Definition at line 35 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefShapeI8()
void _mlir_ciface_printMemrefShapeI8 (UnrankedMemRefType< int8_t > * M)
Definition at line 21 of file RunnerUtils.cpp.
References printMemRefMetaData().
_mlir_ciface_printMemrefVector4x4xf32()
void _mlir_ciface_printMemrefVector4x4xf32 (StridedMemRefType< Vector2D< 4, 4, float >, 2 > * M)
Definition at line 54 of file RunnerUtils.cpp.
References impl::printMemRef().
_mlir_ciface_verifyMemRefF32()
int64_t _mlir_ciface_verifyMemRefF32 (UnrankedMemRefType< float > * actual, UnrankedMemRefType< float > * expected)
Definition at line 132 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefF32().
_mlir_ciface_verifyMemRefF64()
int64_t _mlir_ciface_verifyMemRefF64 (UnrankedMemRefType< double > * actual, UnrankedMemRefType< double > * expected)
Definition at line 138 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefF64().
_mlir_ciface_verifyMemRefI32()
int64_t _mlir_ciface_verifyMemRefI32 (UnrankedMemRefType< int32_t > * actual, UnrankedMemRefType< int32_t > * expected)
Definition at line 126 of file RunnerUtils.cpp.
References impl::verifyMemRef().
Referenced by verifyMemRefI32().
printCString()
void printCString (char * str)
Definition at line 107 of file RunnerUtils.cpp.
printMemrefF32()
void printMemrefF32 (int64_t rank, void * ptr)
Definition at line 97 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefF32().
printMemrefF64()
void printMemrefF64 (int64_t rank, void * ptr)
Definition at line 102 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefF64().
printMemrefI32()
void printMemrefI32 (int64_t rank, void * ptr)
Definition at line 87 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefI32().
printMemrefI64()
void printMemrefI64 (int64_t rank, void * ptr)
Definition at line 92 of file RunnerUtils.cpp.
References _mlir_ciface_printMemrefI64().
verifyMemRefF32()
int64_t verifyMemRefF32 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 150 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefF32().
verifyMemRefF64()
int64_t verifyMemRefF64 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 157 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefF64().
verifyMemRefI32()
int64_t verifyMemRefI32 (int64_t rank, void * actualPtr, void * expectedPtr)
Definition at line 143 of file RunnerUtils.cpp.
References _mlir_ciface_verifyMemRefI32().