MLIR: lib/Analysis/SliceAnalysis.cpp File Reference
SliceAnalysis.cpp File Reference
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Support/LLVM.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
Functions
static void getForwardSliceImpl (Operation *op, SetVector< Operation * > *forwardSlice, TransitiveFilter filter)
static void getBackwardSliceImpl (Operation *op, SetVector< Operation * > *backwardSlice, TransitiveFilter filter)
static void dfsPostorder (Operation *root, DFSState *state)
static bool dependsOnCarriedVals (Value value, ArrayRef< BlockArgument > iterCarriedArgs, Operation *ancestorOp)
Returns true if value (transitively) depends on iteration-carried values of the given ancestorOp.
Function Documentation
dependsOnCarriedVals()
static bool dependsOnCarriedVals (Value value, ArrayRef< BlockArgument > iterCarriedArgs, Operation * ancestorOp) static
Returns true if value (transitively) depends on iteration-carried values of the given ancestorOp.
Definition at line 220 of file SliceAnalysis.cpp.
References mlir::getBackwardSlice(), mlir::Operation::getOperands(), mlir::Operation::isAncestor(), and value.
Referenced by mlir::matchReduction().
dfsPostorder()
static void dfsPostorder (Operation * root, DFSState * state) static
Definition at line 173 of file SliceAnalysis.cpp.
References mlir::Operation::getRegions(), mlir::Operation::getResults(), and mlir::Operation::getUsers().
Referenced by mlir::topologicalSort().
getBackwardSliceImpl()
static void getBackwardSliceImpl (Operation * op, SetVector< Operation * > * backwardSlice, TransitiveFilter filter) static
Definition at line 79 of file SliceAnalysis.cpp.
References mlir::detail::enumerate(), mlir::Region::getBlocks(), mlir::Operation::getNumRegions(), mlir::Operation::getOperands(), mlir::Block::getParentOp(), mlir::Operation::getRegion(), and mlir::Operation::hasTrait().
Referenced by mlir::getBackwardSlice().
getForwardSliceImpl()
static void getForwardSliceImpl (Operation * op, SetVector< Operation * > * forwardSlice, TransitiveFilter filter) static
Definition at line 27 of file SliceAnalysis.cpp.
References mlir::Operation::getRegions(), mlir::Operation::getResults(), and mlir::Operation::getUsers().
Referenced by mlir::getForwardSlice().