MLIR: lib/Dialect/SparseTensor/Transforms/Sparsification.cpp File Reference
Sparsification.cpp File Reference
#include "CodegenUtils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Transforms/Transforms.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Dialect/SparseTensor/Utils/Merger.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/TensorEncoding.h"
#include "llvm/ADT/SmallBitVector.h"
Functions
static AffineMap permute (MLIRContext *context, AffineMap m, std::vector< unsigned > &topSort)
Helper method to construct a permuted dimension ordering that adheres to the given topological sort.
static bool findAffine (Merger &merger, unsigned tensor, unsigned dim, AffineExpr a, DimLevelType dlt, bool setLvlFormat=true)
Helper method to inspect affine expressions.
static bool findSparseAnnotations (Merger &merger, linalg::GenericOp op)
Helper method to inspect sparse encodings in the tensor types.
static bool topSortOptimal (unsigned n, ArrayRef< utils::IteratorType > iteratorTypes, std::vector< unsigned > &topSort, std::vector< unsigned > &inDegree, std::vector< std::vector< bool >> &adjM)
A helper to compute a topological sort.
static void addAffineOrderings (std::vector< std::vector< bool >> &adjM, std::vector< unsigned > &inDegree, AffineExpr a, AffineExpr b, unsigned fidx)
Helper method to add all constraints from the indices in one affine expression before all indices in the other affine expression.
static bool computeIterationGraph (Merger &merger, linalg::GenericOp op, std::vector< unsigned > &topSort, unsigned mask, OpOperand *skip=nullptr)
Computes a topologically sorted iteration graph for the linalg operation.
static bool isMaterializing (Value val)
Returns true if tensor materializes uninitialized into the computation.
static bool isAdmissibleTensorExp (Merger &merger, linalg::GenericOp op, std::vector< unsigned > &topSort, unsigned exp, OpOperand **sparseOut, unsigned &outerParNest)
Returns true when the tensor expression is admissible for codegen.
static Reduction getReduction (Kind kind)
Maps operation to reduction.
static void updateReduc (Merger &merger, CodeGen &codegen, Value reduc)
Updates scalarized reduction value.
static Value getCustomRedId (Operation *op)
Extracts identity from custom reduce.
static Optional< Operation * > genLoopBoundary (CodeGen &codegen, Merger &merger, function_ref< Optional< Operation * >(MutableArrayRef< Value > reduc)> callback)
Generates loop boundary statements (entering/exiting loops).
static void genBuffers (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op)
Local bufferization of all dense and sparse data structures.
static Value genAffine (CodeGen &codegen, OpBuilder &builder, AffineExpr a, Location loc)
Generates an affine expression.
static Value genIndex (CodeGen &codegen, linalg::GenericOp op, OpOperand *t)
Generates index for load/store on sparse tensor.
static Value genSubscript (CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, OpOperand *t, SmallVectorImpl< Value > &args)
Generates subscript for load/store on a dense or sparse tensor.
static Value genInsertionLoad (CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, OpOperand *t)
Generates insertion code to implement dynamic tensor load.
static Value genInsertionLoadReduce (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, OpOperand *t)
Generates insertion code to implement dynamic tensor load for reduction.
static void genInsertionStore (CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, OpOperand *t, Value rhs)
Generates insertion code to implement dynamic tensor store.
static Value genTensorLoad (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned exp)
Generates a load on a dense or sparse tensor.
static void genTensorStore (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned exp, Value rhs)
Generates a store on a dense or sparse tensor.
static Value genInvariantValue (Merger &merger, CodeGen &codegen, OpBuilder &builder, unsigned exp)
Generates an invariant value.
static Value genIndexValue (CodeGen &codegen, OpBuilder &builder, unsigned idx)
Generates an index value.
static Value relinkBranch (CodeGen &codegen, RewriterBase &rewriter, Block *block, Value e, unsigned ldx)
Semi-ring branches are simply inlined by the sparse compiler.
static Value genExp (Merger &merger, CodeGen &codegen, RewriterBase &rewriter, linalg::GenericOp op, unsigned exp, unsigned ldx)
Recursively generates tensor expression.
static bool isInvariantAffine (const CodeGen &codegen, AffineExpr a, unsigned ldx, bool &atLevel)
Determines if affine expression is invariant.
static void genInvariants (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned exp, unsigned ldx, bool atStart, unsigned last=-1u)
Hoists loop invariant tensor loads for which indices have been exhausted.
static void genExpansion (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned at, bool atStart)
Generates an expanded access pattern in innermost dimension.
static bool isParallelFor (CodeGen &codegen, bool isOuter, bool isSparse)
Returns parallelization strategy.
static Operation * genFor (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, bool isOuter, bool isInner, unsigned idx, size_t tid, size_t dim, ArrayRef< size_t > extraTids, ArrayRef< size_t > extraDims)
Generates a for-loop on a single index.
static Operation * genWhile (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned idx, bool needsUniv, ArrayRef< size_t > condTids, ArrayRef< size_t > condDims, ArrayRef< size_t > extraTids, ArrayRef< size_t > extraDims)
Emit a while-loop for co-iteration over multiple indices.
static Operation * genLoop (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned at, bool needsUniv, ArrayRef< size_t > condTids, ArrayRef< size_t > condDims, ArrayRef< size_t > extraTids, ArrayRef< size_t > extraDims)
Generates a for-loop or a while-loop, depending on whether it implements singleton iteration or co-iteration over the given conjunction.
static void finalizeWhileOp (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned idx, bool needsUniv, BitVector &induction, scf::WhileOp whileOp)
Generates the induction structure for a while-loop.
static scf::IfOp genIf (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned idx, BitVector &conditions)
Generates a single if-statement within a while-loop.
static void endIf (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, scf::IfOp ifOp, Operation *loop, Value redInput, Value cntInput, Value insInput)
Generates end of true branch of if-statement within a while-loop.
static bool startLoopSeq (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned exp, unsigned at, unsigned idx, unsigned ldx, unsigned lts)
Starts a loop sequence at given level.
static void translateBitsToTidDimPairs (Merger &merger, CodeGen &codegen, unsigned li, unsigned idx, SmallVectorImpl< size_t > &condTids, SmallVectorImpl< size_t > &condDims, SmallVectorImpl< size_t > &extraTids, SmallVectorImpl< size_t > &extraDims)
static Operation * startLoop (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned at, unsigned li, bool needsUniv)
Starts a single loop in current sequence.
static bool endLoop (Merger &merger, CodeGen &codegen, RewriterBase &rewriter, linalg::GenericOp op, Operation *loop, unsigned idx, unsigned li, bool needsUniv)
Ends a single loop in current sequence. Returns new values for needsUniv.
static void endLoopSeq (Merger &merger, CodeGen &codegen, OpBuilder &builder, linalg::GenericOp op, unsigned exp, unsigned at, unsigned idx, unsigned ldx)
Ends a loop sequence at given level.
static void genStmt (Merger &merger, CodeGen &codegen, RewriterBase &rewriter, linalg::GenericOp op, unsigned exp, unsigned at)
Recursively generates code while computing iteration lattices in order to manage the complexity of implementing co-iteration over unions and intersections of sparse iterations spaces.
static void genResult (Merger &merger, CodeGen &codegen, RewriterBase &rewriter, linalg::GenericOp op)
Converts the result computed by the sparse kernel into the required form.
Function Documentation
addAffineOrderings()
static void addAffineOrderings (std::vector< std::vector< bool >> & adjM, std::vector< unsigned > & inDegree, AffineExpr a, AffineExpr b, unsigned fidx) static
Helper method to add all constraints from the indices in one affine expression before all indices in the other affine expression.
For example i0+i1 < i2+i3+1 yields i0<i2, i0<i3, i1<i2, and i1<i3.
Definition at line 222 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::DimId, mlir::AffineExpr::getKind(), and mlir::Mul.
Referenced by computeIterationGraph().
computeIterationGraph()
static bool computeIterationGraph (Merger & merger, linalg::GenericOp op, std::vector< unsigned > & topSort, unsigned mask, OpOperand * skip = nullptr) static
Computes a topologically sorted iteration graph for the linalg operation.
Ensures all tensors are visited in natural index order. This is essential for sparse storage formats since these only support access along fixed dimensions. Even for dense storage formats, however, the natural index order yields innermost unit-stride access with better spatial locality.
Definition at line 253 of file Sparsification.cpp.
References addAffineOrderings(), mlir::sparse_tensor::Merger::getDimLevelType(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), mlir::sparse_tensor::isUndefDLT(), mlir::sparse_tensor::toOrigDim(), and topSortOptimal().
endIf()
static void endIf (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, scf::IfOp ifOp, Operation * loop, Value redInput, Value cntInput, Value insInput) static
Generates end of true branch of if-statement within a while-loop.
Definition at line 1056 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::setInsertionPointToStart(), and updateReduc().
endLoop()
static bool endLoop (Merger & merger, CodeGen & codegen, RewriterBase & rewriter, linalg::GenericOp op, Operation * loop, unsigned idx, unsigned li, bool needsUniv) static
Ends a single loop in current sequence. Returns new values for needsUniv.
Definition at line 1191 of file Sparsification.cpp.
References mlir::sparse_tensor::LatPoint::bits, finalizeWhileOp(), genLoopBoundary(), and mlir::sparse_tensor::Merger::lat().
endLoopSeq()
static void endLoopSeq (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned exp, unsigned at, unsigned idx, unsigned ldx) static
Ends a loop sequence at given level.
Definition at line 1211 of file Sparsification.cpp.
References genExpansion(), and genInvariants().
finalizeWhileOp()
static void finalizeWhileOp (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned idx, bool needsUniv, BitVector & induction, scf::WhileOp whileOp) static
Generates the induction structure for a while-loop.
Definition at line 986 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::getInsertionBlock(), mlir::Block::getParentOp(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), and updateReduc().
Referenced by endLoop().
findAffine()
static bool findAffine (Merger & merger, unsigned tensor, unsigned dim, AffineExpr a, DimLevelType dlt, bool setLvlFormat = true) static
Helper method to inspect affine expressions.
Rejects cases where the same index is used more than once. Also rejects compound affine expressions in sparse dimensions.
Definition at line 128 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::Constant, mlir::DimId, mlir::sparse_tensor::Merger::getDimLevelType(), mlir::AffineExpr::getKind(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isUndefDLT(), mlir::Mul, and mlir::sparse_tensor::Merger::setDimAndDimLevelType().
Referenced by findSparseAnnotations().
findSparseAnnotations()
static bool findSparseAnnotations (Merger & merger, linalg::GenericOp op) static
Helper method to inspect sparse encodings in the tensor types.
Fills the per-dimension sparsity information for all tensors. Returns true if the sparse annotations and affine subscript expressions of all tensors are admissible. Returns false if no annotations are found or inadmissible constructs occur.
Definition at line 163 of file Sparsification.cpp.
References findAffine(), mlir::sparse_tensor::getDimLevelType(), mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::sparse_tensor::toOrigDim().
genAffine()
static Value genAffine (CodeGen & codegen, OpBuilder & builder, AffineExpr a, Location loc) static
Generates an affine expression.
Definition at line 492 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::Constant, mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::DimId, mlir::AffineExpr::getKind(), and mlir::Mul.
Referenced by genSubscript().
genBuffers()
static void genBuffers (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op) static
Local bufferization of all dense and sparse data structures.
Generates buffer for the output tensor. Note that all sparse kernels assume that when all elements are written to (viz. x(i) = y(i) * z(i)), the output buffer is already initialized to all zeroes and only nonzeroes values are computed and written out. For updates (viz. x(i) += y(i) * z(i)), only nonzeroes values are used for the updates and no assumption on the original contents of the output buffer is necessary.
Definition at line 447 of file Sparsification.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::Value::getType().
genExp()
static Value genExp (Merger & merger, CodeGen & codegen, RewriterBase & rewriter, linalg::GenericOp op, unsigned exp, unsigned ldx) static
Recursively generates tensor expression.
Definition at line 736 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::buildExp(), mlir::sparse_tensor::TensorExp::children, mlir::sparse_tensor::Children::e0, mlir::sparse_tensor::Children::e1, mlir::sparse_tensor::Merger::exp(), genIndexValue(), genInvariantValue(), genTensorLoad(), mlir::Value::getParentBlock(), mlir::sparse_tensor::TensorExp::index, mlir::sparse_tensor::kBinary, mlir::sparse_tensor::kBinaryBranch, mlir::sparse_tensor::TensorExp::kind, mlir::sparse_tensor::kIndex, mlir::sparse_tensor::kInvariant, mlir::sparse_tensor::kReduce, mlir::sparse_tensor::kSelect, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::kUnary, relinkBranch(), and mlir::sparse_tensor::TensorExp::val.
genExpansion()
static void genExpansion (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned at, bool atStart) static
Generates an expanded access pattern in innermost dimension.
Definition at line 856 of file Sparsification.cpp.
Referenced by endLoopSeq(), and startLoopSeq().
genFor()
static Operation* genFor (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, bool isOuter, bool isInner, unsigned idx, size_t tid, size_t dim, ArrayRef< size_t > extraTids, ArrayRef< size_t > extraDims) static
Generates a for-loop on a single index.
Definition at line 927 of file Sparsification.cpp.
References genLoopBoundary(), mlir::sparse_tensor::Merger::getDimLevelType(), mlir::sparse_tensor::isCompressedDLT(), isParallelFor(), mlir::sparse_tensor::isSingletonDLT(), and value.
Referenced by genLoop().
genIf()
static scf::IfOp genIf (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned idx, BitVector & conditions) static
Generates a single if-statement within a while-loop.
Definition at line 1018 of file Sparsification.cpp.
References mlir::sparse_tensor::constantI1(), mlir::OpBuilder::create(), mlir::sparse_tensor::Merger::getDimLevelType(), mlir::sparse_tensor::Merger::getDimNum(), mlir::Builder::getIndexType(), mlir::sparse_tensor::Merger::index(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::isSingletonDLT(), mlir::sparse_tensor::isUndefDLT(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::sparse_tensor::Merger::tensor().
genIndex()
static Value genIndex (CodeGen & codegen, linalg::GenericOp op, OpOperand * t) static
Generates index for load/store on sparse tensor.
Definition at line 521 of file Sparsification.cpp.
References mlir::AffineExpr::cast(), mlir::DimId, mlir::IROperand< DerivedT, IRValueT >::get(), mlir::AffineExpr::getKind(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), and mlir::sparse_tensor::toOrigDim().
Referenced by genInsertionLoad(), and genInsertionLoadReduce().
genIndexValue()
static Value genIndexValue (CodeGen & codegen, OpBuilder & builder, unsigned idx) inline static
Generates an index value.
Definition at line 711 of file Sparsification.cpp.
Referenced by genExp(), and relinkBranch().
genInsertionLoad()
static Value genInsertionLoad (CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, OpOperand * t) static
Generates insertion code to implement dynamic tensor load.
Definition at line 556 of file Sparsification.cpp.
References mlir::sparse_tensor::constantZero(), mlir::OpBuilder::create(), genIndex(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::getElementTypeOrSelf(), and mlir::Value::getType().
Referenced by genTensorLoad().
genInsertionLoadReduce()
static Value genInsertionLoadReduce (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, OpOperand * t) static
Generates insertion code to implement dynamic tensor load for reduction.
Definition at line 570 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::Merger::exp(), genIndex(), getCustomRedId(), and mlir::sparse_tensor::TensorExp::op.
Referenced by genTensorLoad().
genInsertionStore()
static void genInsertionStore (CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, OpOperand * t, Value rhs) static
Generates insertion code to implement dynamic tensor store.
Definition at line 589 of file Sparsification.cpp.
genInvariants()
static void genInvariants (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned exp, unsigned ldx, bool atStart, unsigned last = -1u) static
Hoists loop invariant tensor loads for which indices have been exhausted.
Definition at line 801 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::exp(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), isInvariantAffine(), mlir::sparse_tensor::TensorExp::kind, mlir::sparse_tensor::kTensor, mlir::sparse_tensor::TensorExp::tensor, and mlir::sparse_tensor::toOrigDim().
Referenced by endLoopSeq(), and startLoopSeq().
genInvariantValue()
static Value genInvariantValue (Merger & merger, CodeGen & codegen, OpBuilder & builder, unsigned exp) inline static
Generates an invariant value.
Definition at line 705 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::exp(), and mlir::sparse_tensor::TensorExp::val.
Referenced by genExp().
genLoop()
static Operation* genLoop (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned at, bool needsUniv, ArrayRef< size_t > condTids, ArrayRef< size_t > condDims, ArrayRef< size_t > extraTids, ArrayRef< size_t > extraDims) static
Generates a for-loop or a while-loop, depending on whether it implements singleton iteration or co-iteration over the given conjunction.
Definition at line 967 of file Sparsification.cpp.
References genFor(), and genWhile().
Referenced by startLoop().
genLoopBoundary()
static Optional<Operation *> genLoopBoundary (CodeGen & codegen, Merger & merger, function_ref< Optional< Operation * >(MutableArrayRef< Value > reduc)> callback) static
Generates loop boundary statements (entering/exiting loops).
The function passes and updates the reduction value.
Definition at line 420 of file Sparsification.cpp.
References updateReduc().
Referenced by endLoop(), genFor(), and genWhile().
genResult()
static void genResult (Merger & merger, CodeGen & codegen, RewriterBase & rewriter, linalg::GenericOp op) static
Converts the result computed by the sparse kernel into the required form.
Definition at line 1288 of file Sparsification.cpp.
genStmt()
static void genStmt (Merger & merger, CodeGen & codegen, RewriterBase & rewriter, linalg::GenericOp op, unsigned exp, unsigned at) static
Recursively generates code while computing iteration lattices in order to manage the complexity of implementing co-iteration over unions and intersections of sparse iterations spaces.
Definition at line 1225 of file Sparsification.cpp.
genSubscript()
static Value genSubscript (CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, OpOperand * t, SmallVectorImpl< Value > & args) static
Generates subscript for load/store on a dense or sparse tensor.
Definition at line 531 of file Sparsification.cpp.
References mlir::DimId, genAffine(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::Value::getType(), and mlir::sparse_tensor::toOrigDim().
Referenced by genTensorLoad().
genTensorLoad()
static Value genTensorLoad (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned exp) static
Generates a load on a dense or sparse tensor.
Definition at line 637 of file Sparsification.cpp.
References mlir::OpBuilder::create(), mlir::sparse_tensor::Merger::exp(), genInsertionLoad(), genInsertionLoadReduce(), genSubscript(), mlir::sparse_tensor::TensorExp::tensor, and mlir::sparse_tensor::TensorExp::val.
Referenced by genExp().
genTensorStore()
static void genTensorStore (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned exp, Value rhs) static
Generates a store on a dense or sparse tensor.
Definition at line 658 of file Sparsification.cpp.
genWhile()
static Operation* genWhile (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned idx, bool needsUniv, ArrayRef< size_t > condTids, ArrayRef< size_t > condDims, ArrayRef< size_t > extraTids, ArrayRef< size_t > extraDims) static
Emit a while-loop for co-iteration over multiple indices.
Definition at line 948 of file Sparsification.cpp.
References genLoopBoundary(), and value.
Referenced by genLoop().
getCustomRedId()
static Value getCustomRedId (Operation * op) static
Extracts identity from custom reduce.
Definition at line 410 of file Sparsification.cpp.
Referenced by genInsertionLoadReduce().
getReduction()
static Reduction getReduction (Kind kind) static
Maps operation to reduction.
Definition at line 377 of file Sparsification.cpp.
isAdmissibleTensorExp()
static bool isAdmissibleTensorExp (Merger & merger, linalg::GenericOp op, std::vector< unsigned > & topSort, unsigned exp, OpOperand ** sparseOut, unsigned & outerParNest) static
Returns true when the tensor expression is admissible for codegen.
Since all sparse input tensors are admissible, we just need to check whether the out tensor in the tensor expression codegen is admissible. Sets sparseOut to the tensor and outerParNest to the outer injective nesting depth when a "truly dynamic" sparse tensor output occurs.
Definition at line 319 of file Sparsification.cpp.
isInvariantAffine()
static bool isInvariantAffine (const CodeGen & codegen, AffineExpr a, unsigned ldx, bool & atLevel) static
Determines if affine expression is invariant.
Definition at line 780 of file Sparsification.cpp.
References mlir::Add, mlir::AffineExpr::cast(), mlir::DimId, mlir::AffineExpr::getKind(), and mlir::Mul.
Referenced by genInvariants().
isMaterializing()
static bool isMaterializing (Value val) static
Returns true if tensor materializes uninitialized into the computation.
Definition at line 309 of file Sparsification.cpp.
References mlir::Value::getDefiningOp().
isParallelFor()
static bool isParallelFor (CodeGen & codegen, bool isOuter, bool isSparse) static
Returns parallelization strategy.
Any implicit loop in the Linalg operation that is marked "parallel" is a candidate. Whether it is actually converted to a parallel operation depends on the requested strategy.
Definition at line 903 of file Sparsification.cpp.
References mlir::kAnyStorageAnyLoop, mlir::kAnyStorageOuterLoop, mlir::kDenseAnyLoop, mlir::kDenseOuterLoop, and mlir::kNone.
Referenced by genFor().
permute()
static AffineMap permute (MLIRContext * context, AffineMap m, std::vector< unsigned > & topSort) static
Helper method to construct a permuted dimension ordering that adheres to the given topological sort.
Definition at line 109 of file Sparsification.cpp.
References mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::getPermutationMap().
Referenced by mlir::sparse_tensor::detail::PermutationRef::permute().
relinkBranch()
static Value relinkBranch (CodeGen & codegen, RewriterBase & rewriter, Block * block, Value e, unsigned ldx) static
Semi-ring branches are simply inlined by the sparse compiler.
Prior analysis has verified that all computations are "local" to the inlined branch or otherwise invariantly defined outside the loop nest, with the exception of index computations, which need to be relinked to actual inlined cloned code.
Definition at line 721 of file Sparsification.cpp.
References genIndexValue(), and mlir::Value::getDefiningOp().
Referenced by genExp().
startLoop()
static Operation* startLoop (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned at, unsigned li, bool needsUniv) static
Starts a single loop in current sequence.
Definition at line 1173 of file Sparsification.cpp.
References genLoop(), and translateBitsToTidDimPairs().
startLoopSeq()
static bool startLoopSeq (Merger & merger, CodeGen & codegen, OpBuilder & builder, linalg::GenericOp op, unsigned exp, unsigned at, unsigned idx, unsigned ldx, unsigned lts) static
Starts a loop sequence at given level.
Returns true if the universal loop index must be maintained at this level.
Definition at line 1083 of file Sparsification.cpp.
References mlir::sparse_tensor::LatPoint::bits, mlir::sparse_tensor::Merger::foreachTidDimPairInBits(), genExpansion(), genInvariants(), mlir::sparse_tensor::Merger::lat(), and mlir::sparse_tensor::Merger::set().
topSortOptimal()
static bool topSortOptimal (unsigned n, ArrayRef< utils::IteratorType > iteratorTypes, std::vector< unsigned > & topSort, std::vector< unsigned > & inDegree, std::vector< std::vector< bool >> & adjM) static
A helper to compute a topological sort.
O(n^2) time complexity as we use adj matrix for the graph. The sorted result will put the first Reduction iterator to the latest possible index.
Definition at line 185 of file Sparsification.cpp.
References mlir::linalg::isReductionIterator().
Referenced by computeIterationGraph().
translateBitsToTidDimPairs()
static void translateBitsToTidDimPairs (Merger & merger, CodeGen & codegen, unsigned li, unsigned idx, SmallVectorImpl< size_t > & condTids, SmallVectorImpl< size_t > & condDims, SmallVectorImpl< size_t > & extraTids, SmallVectorImpl< size_t > & extraDims) static
Definition at line 1125 of file Sparsification.cpp.
References mlir::sparse_tensor::LatPoint::bits, mlir::sparse_tensor::Merger::foreachTidDimPairInBits(), mlir::sparse_tensor::isDenseDLT(), mlir::sparse_tensor::Merger::lat(), and mlir::sparse_tensor::LatPoint::simple.
Referenced by startLoop().
updateReduc()
static void updateReduc (Merger & merger, CodeGen & codegen, Value reduc) static
Updates scalarized reduction value.
Definition at line 404 of file Sparsification.cpp.
References mlir::sparse_tensor::Merger::exp(), and mlir::sparse_tensor::TensorExp::val.
Referenced by endIf(), finalizeWhileOp(), and genLoopBoundary().