MLIR: lib/Dialect/SparseTensor/Transforms/SparseBufferRewriting.cpp File Reference
SparseBufferRewriting.cpp File Reference
#include "CodegenUtils.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Support/LLVM.h"
Typedefs
using FuncGeneratorType = function_ref< void(OpBuilder &, ModuleOp, func::FuncOp, uint64_t, uint64_t, bool)>
Functions
static void getMangledSortHelperFuncName (llvm::raw_svector_ostream &nameOstream, StringRef namePrefix, uint64_t nx, uint64_t ny, bool isCoo, ValueRange operands)
Constructs a function name with this format to facilitate quick sort: <namePrefix><nx>_<x type>_<y0 type>..._<yn type> for sort <namePrefix><nx>_<x type>coo<ny>_<y0 type>..._<yn type> for sort_coo.
static FlatSymbolRefAttr getMangledSortHelperFunc (OpBuilder &builder, func::FuncOp insertPoint, TypeRange resultTypes, StringRef namePrefix, uint64_t nx, uint64_t ny, bool isCoo, ValueRange operands, FuncGeneratorType createFunc)
Looks up a function that is appropriate for the given operands being sorted, and creates such a function if it doesn't exist yet.
static void forEachIJPairInXs (OpBuilder &builder, Location loc, ValueRange args, uint64_t nx, uint64_t ny, bool isCoo, function_ref< void(uint64_t, Value, Value, Value)> bodyBuilder)
Creates a code block to process each pair of (xs[i], xs[j]) for sorting.
static void forEachIJPairInAllBuffers (OpBuilder &builder, Location loc, ValueRange args, uint64_t nx, uint64_t ny, bool isCoo, function_ref< void(uint64_t, Value, Value, Value)> bodyBuilder)
Creates a code block to process each pair of (xys[i], xys[j]) for sorting.
static void createSwap (OpBuilder &builder, Location loc, ValueRange args, uint64_t nx, uint64_t ny, bool isCoo)
Creates a code block for swapping the values in index i and j for all the buffers.
static void createCompareFuncImplementation (OpBuilder &builder, ModuleOp unused, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo, function_ref< scf::IfOp(OpBuilder &, Location, Value, Value, Value, bool)> compareBuilder)
Creates a function to compare all the (xs[i], xs[j]) pairs.
static scf::IfOp createEqCompare (OpBuilder &builder, Location loc, Value i, Value j, Value x, bool isLastDim)
Generates an if-statement to compare whether x[i] is equal to x[j].
static void createEqCompareFunc (OpBuilder &builder, ModuleOp unused, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo)
Creates a function to compare whether xs[i] is equal to xs[j].
static scf::IfOp createLessThanCompare (OpBuilder &builder, Location loc, Value i, Value j, Value x, bool isLastDim)
Generates an if-statement to compare whether x[i] is less than x[j].
static void createLessThanFunc (OpBuilder &builder, ModuleOp unused, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo)
Creates a function to compare whether xs[i] is less than xs[j].
static void createBinarySearchFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo)
Creates a function to use a binary search to find the insertion point for inserting xs[hi] to the sorted values xs[lo..hi).
static std::pair< Value, Value > createScanLoop (OpBuilder &builder, ModuleOp module, func::FuncOp func, ValueRange xs, Value i, Value p, uint64_t nx, uint64_t ny, bool isCoo, int step)
Creates code to advance i in a loop based on xs[p] as follows: while (xs[i] < xs[p]) i += step (step > 0) or while (xs[i] > xs[p]) i += step (step < 0) The routine returns i as well as a boolean value to indicate whether xs[i] == xs[p].
static void createPartitionFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo)
Creates a function to perform quick sort partition on the values in the range of index [lo, hi), assuming lo < hi.
static void createSortNonstableFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo)
Creates a function to perform quick sort on the value in the range of index [lo, hi).
static void createSortStableFunc (OpBuilder &builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo)
Creates a function to perform insertion sort on the values in the range of index [lo, hi).
template<typename OpTy >
LogicalResult matchAndRewriteSortOp (OpTy op, ValueRange xys, uint64_t nx, uint64_t ny, bool isCoo, PatternRewriter &rewriter)
Implements the rewriting for operator sort and sort_coo.
Variables
static constexpr uint64_t loIdx = 0
static constexpr uint64_t hiIdx = 1
static constexpr uint64_t xStartIdx = 2
static constexpr const char kLessThanFuncNamePrefix [] = "_sparse_less_than_"
static constexpr const char kCompareEqFuncNamePrefix [] = "_sparse_compare_eq_"
static constexpr const char kPartitionFuncNamePrefix [] = "_sparse_partition_"
static constexpr const char kBinarySearchFuncNamePrefix []
static constexpr const char kSortNonstableFuncNamePrefix []
static constexpr const char kSortStableFuncNamePrefix []
Typedef Documentation
FuncGeneratorType
using FuncGeneratorType = function_ref<void(OpBuilder &, ModuleOp, func::FuncOp, uint64_t, uint64_t, bool)>
Definition at line 46 of file SparseBufferRewriting.cpp.
Function Documentation
createBinarySearchFunc()
static void createBinarySearchFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo) static
Creates a function to use a binary search to find the insertion point for inserting xs[hi] to the sorted values xs[lo..hi).
Definition at line 324 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), createLessThanFunc(), mlir::Block::getArguments(), getMangledSortHelperFunc(), mlir::Value::getType(), hiIdx, kLessThanFuncNamePrefix, loIdx, mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by createSortStableFunc().
createCompareFuncImplementation()
static void createCompareFuncImplementation (OpBuilder & builder, ModuleOp unused, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo, function_ref< scf::IfOp(OpBuilder &, Location, Value, Value, Value, bool)> compareBuilder) static
Creates a function to compare all the (xs[i], xs[j]) pairs.
The method to compare each pair is create via compareBuilder.
Definition at line 177 of file SparseBufferRewriting.cpp.
References mlir::OpBuilder::create(), forEachIJPairInXs(), mlir::Block::getArguments(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by createEqCompareFunc(), and createLessThanFunc().
createEqCompare()
static scf::IfOp createEqCompare (OpBuilder & builder, Location loc, Value i, Value j, Value x, bool isLastDim) static
Generates an if-statement to compare whether x[i] is equal to x[j].
Definition at line 208 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantI1(), mlir::OpBuilder::create(), mlir::Value::getType(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by createEqCompareFunc().
createEqCompareFunc()
static void createEqCompareFunc (OpBuilder & builder, ModuleOp unused, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo) static
Creates a function to compare whether xs[i] is equal to xs[j].
Definition at line 244 of file SparseBufferRewriting.cpp.
References createCompareFuncImplementation(), and createEqCompare().
Referenced by createScanLoop().
createLessThanCompare()
static scf::IfOp createLessThanCompare (OpBuilder & builder, Location loc, Value i, Value j, Value x, bool isLastDim) static
Generates an if-statement to compare whether x[i] is less than x[j].
Definition at line 252 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantI1(), mlir::OpBuilder::create(), mlir::Value::getType(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by createLessThanFunc().
createLessThanFunc()
static void createLessThanFunc (OpBuilder & builder, ModuleOp unused, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo) static
Creates a function to compare whether xs[i] is less than xs[j].
Definition at line 304 of file SparseBufferRewriting.cpp.
References createCompareFuncImplementation(), and createLessThanCompare().
Referenced by createBinarySearchFunc(), and createScanLoop().
createPartitionFunc()
static void createPartitionFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo) static
Creates a function to perform quick sort partition on the values in the range of index [lo, hi), assuming lo < hi.
Definition at line 475 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), createScanLoop(), createSwap(), mlir::Block::getArguments(), mlir::Value::getType(), hiIdx, loIdx, mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by createSortNonstableFunc().
createScanLoop()
static std::pair<Value, Value> createScanLoop (OpBuilder & builder, ModuleOp module, func::FuncOp func, ValueRange xs, Value i, Value p, uint64_t nx, uint64_t ny, bool isCoo, int step) static
Creates code to advance i in a loop based on xs[p] as follows: while (xs[i] < xs[p]) i += step (step > 0) or while (xs[i] > xs[p]) i += step (step < 0) The routine returns i as well as a boolean value to indicate whether xs[i] == xs[p].
Definition at line 393 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), createEqCompareFunc(), createLessThanFunc(), getMangledSortHelperFunc(), mlir::Value::getType(), kCompareEqFuncNamePrefix, kLessThanFuncNamePrefix, mlir::OpBuilder::setInsertionPointAfter(), and mlir::OpBuilder::setInsertionPointToEnd().
Referenced by createPartitionFunc().
createSortNonstableFunc()
static void createSortNonstableFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo) static
Creates a function to perform quick sort on the value in the range of index [lo, hi).
Definition at line 589 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), createPartitionFunc(), mlir::Block::getArguments(), getMangledSortHelperFunc(), hiIdx, kPartitionFuncNamePrefix, loIdx, mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by matchAndRewriteSortOp().
createSortStableFunc()
static void createSortStableFunc (OpBuilder & builder, ModuleOp module, func::FuncOp func, uint64_t nx, uint64_t ny, bool isCoo) static
Creates a function to perform insertion sort on the values in the range of index [lo, hi).
Definition at line 642 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), createBinarySearchFunc(), forEachIJPairInAllBuffers(), mlir::Block::getArguments(), getMangledSortHelperFunc(), mlir::Value::getType(), hiIdx, kBinarySearchFuncNamePrefix, loIdx, mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and xStartIdx.
Referenced by matchAndRewriteSortOp().
createSwap()
static void createSwap (OpBuilder & builder, Location loc, ValueRange args, uint64_t nx, uint64_t ny, bool isCoo) static
Creates a code block for swapping the values in index i and j for all the buffers.
Definition at line 163 of file SparseBufferRewriting.cpp.
References mlir::OpBuilder::create(), and forEachIJPairInAllBuffers().
Referenced by createPartitionFunc().
forEachIJPairInAllBuffers()
static void forEachIJPairInAllBuffers (OpBuilder & builder, Location loc, ValueRange args, uint64_t nx, uint64_t ny, bool isCoo, function_ref< void(uint64_t, Value, Value, Value)> bodyBuilder) static
Creates a code block to process each pair of (xys[i], xys[j]) for sorting.
The code to process the value pairs is generated by bodyBuilder.
Definition at line 133 of file SparseBufferRewriting.cpp.
References mlir::detail::enumerate(), forEachIJPairInXs(), and xStartIdx.
Referenced by createSortStableFunc(), and createSwap().
forEachIJPairInXs()
static void forEachIJPairInXs (OpBuilder & builder, Location loc, ValueRange args, uint64_t nx, uint64_t ny, bool isCoo, function_ref< void(uint64_t, Value, Value, Value)> bodyBuilder) static
Creates a code block to process each pair of (xs[i], xs[j]) for sorting.
The code to process the value pairs is generated by bodyBuilder.
Definition at line 105 of file SparseBufferRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), and xStartIdx.
Referenced by createCompareFuncImplementation(), and forEachIJPairInAllBuffers().
getMangledSortHelperFunc()
static FlatSymbolRefAttr getMangledSortHelperFunc (OpBuilder & builder, func::FuncOp insertPoint, TypeRange resultTypes, StringRef namePrefix, uint64_t nx, uint64_t ny, bool isCoo, ValueRange operands, FuncGeneratorType createFunc) static
Looks up a function that is appropriate for the given operands being sorted, and creates such a function if it doesn't exist yet.
The parameters nx and ny tell the number of x and y values provided by the buffer in xStartIdx, and isCoo indicates whether the instruction being processed is a sparse_tensor.sort or sparse_tensor.sort_coo.
Definition at line 74 of file SparseBufferRewriting.cpp.
References mlir::OpBuilder::create(), getMangledSortHelperFuncName(), mlir::ValueRange::getTypes(), and mlir::OpBuilder::setInsertionPoint().
Referenced by createBinarySearchFunc(), createScanLoop(), createSortNonstableFunc(), createSortStableFunc(), and matchAndRewriteSortOp().
getMangledSortHelperFuncName()
static void getMangledSortHelperFuncName (llvm::raw_svector_ostream & nameOstream, StringRef namePrefix, uint64_t nx, uint64_t ny, bool isCoo, ValueRange operands) static
Constructs a function name with this format to facilitate quick sort: <namePrefix><nx>_<x type>_<y0 type>..._<yn type> for sort <namePrefix><nx>_<x type>coo<ny>_<y0 type>..._<yn type> for sort_coo.
Definition at line 52 of file SparseBufferRewriting.cpp.
References getElementType(), mlir::ValueRange::getType(), and xStartIdx.
Referenced by getMangledSortHelperFunc().
matchAndRewriteSortOp()
template<typename OpTy > LogicalResult matchAndRewriteSortOp (OpTy op, ValueRange xys, uint64_t nx, uint64_t ny, bool isCoo, PatternRewriter & rewriter)
Implements the rewriting for operator sort and sort_coo.
Definition at line 714 of file SparseBufferRewriting.cpp.
References mlir::Type::cast(), mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), createSortNonstableFunc(), createSortStableFunc(), getMangledSortHelperFunc(), mlir::Value::getType(), kSortNonstableFuncNamePrefix, kSortStableFuncNamePrefix, mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Variable Documentation
hiIdx
constexpr uint64_t hiIdx = 1 static constexpr
Definition at line 33 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), createPartitionFunc(), createSortNonstableFunc(), and createSortStableFunc().
kBinarySearchFuncNamePrefix
constexpr const char kBinarySearchFuncNamePrefix[] static constexpr
Initial value:
=
    "_sparse_binary_search_"
Definition at line 39 of file SparseBufferRewriting.cpp.
Referenced by createSortStableFunc().
kCompareEqFuncNamePrefix
constexpr const char kCompareEqFuncNamePrefix[] = "_sparse_compare_eq_" static constexpr
Definition at line 37 of file SparseBufferRewriting.cpp.
Referenced by createScanLoop().
kLessThanFuncNamePrefix
constexpr const char kLessThanFuncNamePrefix[] = "_sparse_less_than_" static constexpr
Definition at line 36 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), and createScanLoop().
kPartitionFuncNamePrefix
constexpr const char kPartitionFuncNamePrefix[] = "_sparse_partition_" static constexpr
Definition at line 38 of file SparseBufferRewriting.cpp.
Referenced by createSortNonstableFunc().
kSortNonstableFuncNamePrefix
constexpr const char kSortNonstableFuncNamePrefix[] static constexpr
Initial value:
=
    "_sparse_sort_nonstable_"
Definition at line 41 of file SparseBufferRewriting.cpp.
Referenced by matchAndRewriteSortOp().
kSortStableFuncNamePrefix
constexpr const char kSortStableFuncNamePrefix[] static constexpr
Initial value:
=
    "_sparse_sort_stable_"
Definition at line 43 of file SparseBufferRewriting.cpp.
Referenced by matchAndRewriteSortOp().
loIdx
constexpr uint64_t loIdx = 0 static constexpr
Definition at line 32 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), createPartitionFunc(), createSortNonstableFunc(), and createSortStableFunc().
xStartIdx
constexpr uint64_t xStartIdx = 2 static constexpr
Definition at line 34 of file SparseBufferRewriting.cpp.
Referenced by createBinarySearchFunc(), createPartitionFunc(), createSortNonstableFunc(), createSortStableFunc(), forEachIJPairInAllBuffers(), forEachIJPairInXs(), and getMangledSortHelperFuncName().