MLIR: lib/Target/SPIRV/TranslateRegistration.cpp File Reference
TranslateRegistration.cpp File Reference
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Target/SPIRV/Deserialization.h"
#include "mlir/Target/SPIRV/Serialization.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
Namespaces
mlir
Include the generated interface declarations.
Functions
static OwningOpRef< Operation * > deserializeModule (const llvm::MemoryBuffer *input, MLIRContext *context)
void mlir::registerFromSPIRVTranslation ()
static LogicalResult serializeModule (spirv::ModuleOp module, raw_ostream &output)
void mlir::registerToSPIRVTranslation ()
static LogicalResult roundTripModule (spirv::ModuleOp module, bool emitDebugInfo, raw_ostream &output)
void mlir::registerTestRoundtripSPIRV ()
void mlir::registerTestRoundtripDebugSPIRV ()
Function Documentation
deserializeModule()
static OwningOpRef<Operation *> deserializeModule (const llvm::MemoryBuffer * input, MLIRContext * context) static
Definition at line 40 of file TranslateRegistration.cpp.
References mlir::spirv::deserialize(), mlir::emitError(), and mlir::MLIRContext::loadDialect().
Referenced by mlir::registerFromSPIRVTranslation().
roundTripModule()
static LogicalResult roundTripModule (spirv::ModuleOp module, bool emitDebugInfo, raw_ostream & output) static
Definition at line 102 of file TranslateRegistration.cpp.
References mlir::spirv::deserialize(), mlir::failed(), mlir::failure(), mlir::MLIRContext::getDialectRegistry(), mlir::MLIRContext::loadAllAvailableDialects(), options, mlir::spirv::serialize(), and mlir::success().
Referenced by mlir::registerTestRoundtripDebugSPIRV(), and mlir::registerTestRoundtripSPIRV().
serializeModule()
static LogicalResult serializeModule (spirv::ModuleOp module, raw_ostream & output) static
Definition at line 73 of file TranslateRegistration.cpp.
References mlir::failed(), mlir::failure(), mlir::spirv::serialize(), and mlir::success().
Referenced by mlir::registerToSPIRVTranslation().