MLIR: mlir::sparse_tensor::SparseCompilerOptions Struct Reference
mlir::sparse_tensor::SparseCompilerOptions Struct Reference
Options for the "sparse-compiler" pipeline.
#include "mlir/Dialect/SparseTensor/Pipelines/Passes.h"
Public Member Functions
SparsificationOptions sparsificationOptions () const
Projects out the options for createSparsificationPass.
SparseTensorConversionOptions sparseTensorConversionOptions () const
Projects out the options for createSparsificationPass.
LowerVectorToLLVMOptions lowerVectorToLLVMOptions () const
Projects out the options for createConvertVectorToLLVMPass.
Public Member Functions inherited from mlir::detail::PassOptions
PassOptions ()=default
PassOptions (const PassOptions &)=delete
Delete the copy constructor to avoid copying the internal options map.
PassOptions (PassOptions &&)=delete
void copyOptionValuesFrom (const PassOptions &other)
Copy the option values from 'other' into 'this', where 'other' has the same options as 'this'.
LogicalResult parseFromString (StringRef options)
Parse options out as key=value pairs that can then be handed off to the llvm::cl command line passing infrastructure.
void print (raw_ostream &os)
Print the options held by this struct in a form that can be parsed via 'parseFromString'.
void printHelp (size_t indent, size_t descIndent) const
Print the help string for the options held by this struct.
size_t getOptionWidth () const
Return the maximum width required when printing the help string.
Public Attributes
PassOptions::Option< mlir::SparseParallelizationStrategy > parallelization
PassOptions::Option< bool > enableRuntimeLibrary
PassOptions::Option< bool > testBufferizationAnalysisOnly
PassOptions::Option< bool > enableBufferInitialization
PassOptions::Option< int32_t > sparseToSparse
PassOptions::Option< bool > reassociateFPReductions
PassOptions::Option< bool > indexOptimizations
PassOptions::Option< bool > amx
PassOptions::Option< bool > armNeon
PassOptions::Option< bool > armSVE
PassOptions::Option< bool > x86Vector
Additional Inherited Members
Public Types inherited from mlir::detail::PassOptions
template<typename DataType >
using OptionParser = std::conditional_t< std::is_base_of< llvm::cl::generic_parser_base, llvm::cl::parser< DataType > >::value, GenericOptionParser< DataType >, llvm::cl::parser< DataType > >
The specific parser to use depending on llvm::cl parser used.
Static Public Member Functions inherited from mlir::PassPipelineOptions< SparseCompilerOptions >
static std::unique_ptr< SparseCompilerOptions > createFromString (StringRef options)
Factory that parses the provided options and returns a unique_ptr to the struct.
Detailed Description
Options for the "sparse-compiler" pipeline.
So far this only contains a subset of the options that can be set for the underlying passes, because it must be manually kept in sync with the tablegen files for those passes.
Definition at line 30 of file Passes.h.
Member Function Documentation
lowerVectorToLLVMOptions()
LowerVectorToLLVMOptions mlir::sparse_tensor::SparseCompilerOptions::lowerVectorToLLVMOptions () const inline
Projects out the options for createConvertVectorToLLVMPass.
Definition at line 116 of file Passes.h.
References mlir::LowerVectorToLLVMOptions::enableAMX(), mlir::LowerVectorToLLVMOptions::enableArmNeon(), mlir::LowerVectorToLLVMOptions::enableArmSVE(), mlir::LowerVectorToLLVMOptions::enableIndexOptimizations(), mlir::LowerVectorToLLVMOptions::enableReassociateFPReductions(), and mlir::LowerVectorToLLVMOptions::enableX86Vector().
sparseTensorConversionOptions()
SparseTensorConversionOptions mlir::sparse_tensor::SparseCompilerOptions::sparseTensorConversionOptions () const inline
Projects out the options for createSparsificationPass.
Definition at line 81 of file Passes.h.
References mlir::sparseToSparseConversionStrategy().
sparsificationOptions()
SparsificationOptions mlir::sparse_tensor::SparseCompilerOptions::sparsificationOptions () const inline
Projects out the options for createSparsificationPass.
Definition at line 71 of file Passes.h.
Member Data Documentation
amx
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::amx
Initial value:
{
      *this, "enable-amx",
      desc("Enables the use of AMX dialect while lowering the vector dialect."),
      init(false)}
Definition at line 97 of file Passes.h.
armNeon
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::armNeon
Initial value:
{*this, "enable-arm-neon",
                                    desc("Enables the use of ArmNeon dialect "
                                         "while lowering the vector dialect."),
                                    init(false)}
Definition at line 101 of file Passes.h.
armSVE
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::armSVE
Initial value:
{*this, "enable-arm-sve",
                                   desc("Enables the use of ArmSVE dialect "
                                        "while lowering the vector dialect."),
                                   init(false)}
Definition at line 105 of file Passes.h.
enableBufferInitialization
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::enableBufferInitialization
Initial value:
{
      *this, "enable-buffer-initialization",
      desc("Enable zero-initialization of memory buffers"), init(false)}
Definition at line 66 of file Passes.h.
enableRuntimeLibrary
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::enableRuntimeLibrary
Initial value:
{
      *this, "enable-runtime-library",
      desc("Enable runtime library for manipulating sparse tensors"),
      init(true)}
Definition at line 56 of file Passes.h.
indexOptimizations
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::indexOptimizations
Initial value:
{
      *this, "enable-index-optimizations",
      desc("Allows compiler to assume indices fit in 32-bit if that yields "
           "faster code"),
      init(true)}
Definition at line 92 of file Passes.h.
parallelization
PassOptions::Option<mlir::SparseParallelizationStrategy> mlir::sparse_tensor::SparseCompilerOptions::parallelization
Initial value:
{
      *this, "parallelization-strategy",
      ::llvm::cl::desc("Set the parallelization strategy"),
      ::llvm::cl::init(mlir::SparseParallelizationStrategy::kNone),
      llvm::cl::values(
          clEnumValN(mlir::SparseParallelizationStrategy::kNone, "none",
                     "Turn off sparse parallelization."),
          clEnumValN(mlir::SparseParallelizationStrategy::kDenseOuterLoop,
                     "dense-outer-loop",
                     "Enable dense outer loop sparse parallelization."),
          clEnumValN(mlir::SparseParallelizationStrategy::kAnyStorageOuterLoop,
                     "any-storage-outer-loop",
                     "Enable sparse parallelization regardless of storage for "
                     "the outer loop."),
          clEnumValN(mlir::SparseParallelizationStrategy::kDenseAnyLoop,
                     "dense-any-loop",
                     "Enable dense parallelization for any loop."),
          clEnumValN(
              mlir::SparseParallelizationStrategy::kAnyStorageAnyLoop,
              "any-storage-any-loop",
              "Enable sparse parallelization for any storage and loop."))}
Definition at line 34 of file Passes.h.
reassociateFPReductions
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::reassociateFPReductions
Initial value:
{
      *this, "reassociate-fp-reductions",
      desc("Allows llvm to reassociate floating-point reductions for speed"),
      init(false)}
Definition at line 88 of file Passes.h.
sparseToSparse
PassOptions::Option<int32_t> mlir::sparse_tensor::SparseCompilerOptions::sparseToSparse
Initial value:
{
      *this, "s2s-strategy",
      desc("Set the strategy for sparse-to-sparse conversion"), init(0)}
Definition at line 76 of file Passes.h.
testBufferizationAnalysisOnly
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::testBufferizationAnalysisOnly
Initial value:
{
      *this, "test-bufferization-analysis-only",
      desc("Run only the inplacability analysis"), init(false)}
Definition at line 62 of file Passes.h.
x86Vector
PassOptions::Option<bool> mlir::sparse_tensor::SparseCompilerOptions::x86Vector
Initial value:
{
      *this, "enable-x86vector",
      desc("Enables the use of X86Vector dialect while lowering the vector "
           "dialect."),
      init(false)}
Definition at line 109 of file Passes.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/SparseTensor/Pipelines/Passes.h