MLIR: mlir::bufferization::func_ext::CallOpInterface Struct Reference
mlir::bufferization::func_ext::CallOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
SmallVector< OpResult > getAliasingOpResult (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, const AnalysisState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const AnalysisState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationOptions &options) const
All function arguments are writable.
Detailed Description
Definition at line 144 of file FuncBufferizableOpInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::bufferization::func_ext::CallOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationOptions & options) const inline
All function arguments are writable.
It is the responsibility of the CallOp to insert buffer copies where necessary.
Definition at line 259 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::bufferization::getBuffer(), mlir::bufferization::func_ext::getCalledFunction(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Type::isa(), None, options, mlir::bufferization::replaceOpWithBufferizedValues(), mlir::Operation::setAttrs(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 147 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::OpOperand::getOperandNumber(), and mlir::bufferization::func_ext::FuncAnalysisState::readBbArgs.
bufferizesToMemoryWrite()
bool mlir::bufferization::func_ext::CallOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 162 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::OpOperand::getOperandNumber(), and mlir::bufferization::func_ext::FuncAnalysisState::writtenBbArgs.
bufferRelation()
BufferRelation mlir::bufferization::func_ext::CallOpInterface::bufferRelation (Operation * op, OpResult opResult, const AnalysisState & state) const inline
Definition at line 229 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::Analyzed, mlir::bufferization::Equivalent, getAliasingOpOperand(), mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getEquivalentFuncArgIdx(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::OpResult::getResultNumber(), and mlir::bufferization::None.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::bufferization::func_ext::CallOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult, const AnalysisState & state) const inline
Definition at line 204 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::aliasingFuncArgs, mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::Operation::getOpOperands(), and mlir::OpResult::getResultNumber().
Referenced by bufferRelation().
getAliasingOpResult()
SmallVector<OpResult> mlir::bufferization::func_ext::CallOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 177 of file FuncBufferizableOpInterfaceImpl.cpp.
References mlir::bufferization::func_ext::FuncAnalysisState::aliasingReturnVals, mlir::bufferization::func_ext::Analyzed, mlir::bufferization::func_ext::getCalledFunction(), mlir::bufferization::func_ext::getFuncAnalysisState(), mlir::bufferization::func_ext::getFuncOpAnalysisState(), mlir::OpOperand::getOperandNumber(), and mlir::Operation::getOpResults().
The documentation for this struct was generated from the following file:
lib/Dialect/Bufferization/Transforms/FuncBufferizableOpInterfaceImpl.cpp