MLIR: mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp > Struct Template Reference
mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp > Struct Template Reference
OpOrInterfaceRewritePatternBase is a wrapper around RewritePattern that allows for matching and rewriting against an instance of a derived operation class or Interface.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual void rewrite (SourceOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
virtual LogicalResult match (SourceOp op) const
virtual LogicalResult matchAndRewrite (SourceOp op, PatternRewriter &rewriter) const
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()=default
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
Optional< TypeID > getRootInterfaceID () const
Return the interface ID used to match the root operation of this pattern.
Optional< TypeID > getRootTraitID () const
Return the trait ID used to match the root operation of this pattern.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
MLIRContext * getContext () const
Return the MLIRContext used to create this pattern.
StringRef getDebugName () const
Return a readable name for this pattern.
void setDebugName (StringRef name)
Set the human readable debug name used for this pattern.
ArrayRef< StringRef > getDebugLabels () const
Return the set of debug labels attached to this pattern.
void addDebugLabels (ArrayRef< StringRef > labels)
Add the provided debug labels to this pattern.
void addDebugLabels (StringRef label)
Additional Inherited Members
Static Public Member Functions inherited from mlir::RewritePattern
template<typename T , typename... Args>
static std::unique_ptr< T > create (Args &&...args)
This method provides a convenient interface for creating and initializing derived rewrite patterns of the given type T.
Protected Member Functions inherited from mlir::RewritePattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Inherit the base constructors from Pattern.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (MatchAnyOpTypeTag tag, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation type.
Pattern (MatchInterfaceOpTypeTag tag, TypeID interfaceID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the interface defined by the provided interfaceID.
Pattern (MatchTraitOpTypeTag tag, TypeID traitID, PatternBenefit benefit, MLIRContext *context, ArrayRef< StringRef > generatedNames={})
Construct a pattern that may match any operation that implements the trait defined by the provided traitID.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
template<typename SourceOp>
struct mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >
OpOrInterfaceRewritePatternBase is a wrapper around RewritePattern that allows for matching and rewriting against an instance of a derived operation class or Interface.
Definition at line 317 of file PatternMatch.h.
Member Function Documentation
match() [1/2]
template<typename SourceOp > LogicalResult mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::match (Operation * op) const inline final virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Reimplemented from mlir::RewritePattern.
Definition at line 324 of file PatternMatch.h.
Referenced by mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::matchAndRewrite().
match() [2/2]
template<typename SourceOp > virtual LogicalResult mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::match (SourceOp op) const inline virtual
Definition at line 337 of file PatternMatch.h.
matchAndRewrite() [1/2]
template<typename SourceOp > LogicalResult mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline final virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented from mlir::RewritePattern.
Definition at line 327 of file PatternMatch.h.
matchAndRewrite() [2/2]
template<typename SourceOp > virtual LogicalResult mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::matchAndRewrite (SourceOp op, PatternRewriter & rewriter) const inline virtual
Definition at line 340 of file PatternMatch.h.
References mlir::failure(), mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::match(), mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::rewrite(), mlir::succeeded(), and mlir::success().
rewrite() [1/2]
template<typename SourceOp > void mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::rewrite (Operation * op, PatternRewriter & rewriter) const inline final virtual
Wrappers around the RewritePattern methods that pass the derived op type.
Reimplemented from mlir::RewritePattern.
Definition at line 321 of file PatternMatch.h.
Referenced by mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::matchAndRewrite().
rewrite() [2/2]
template<typename SourceOp > virtual void mlir::detail::OpOrInterfaceRewritePatternBase< SourceOp >::rewrite (SourceOp op, PatternRewriter & rewriter) const inline virtual
Rewrite and Match methods that operate on the SourceOp type.
These must be overridden by the derived pattern class.
Definition at line 334 of file PatternMatch.h.
The documentation for this struct was generated from the following file:
include/mlir/IR/PatternMatch.h