MLIR: mlir::OpBuilder::Listener Struct Reference
mlir::OpBuilder::Listener Struct Reference
This class represents a listener that may be used to hook into various actions within an OpBuilder.
#include "mlir/IR/Builders.h"
Public Member Functions
virtual ~Listener ()
virtual void notifyOperationInserted (Operation *op)
Notification handler for when an operation is inserted into the builder.
virtual void notifyBlockCreated (Block *block)
Notification handler for when a block is created using the builder.
Detailed Description
This class represents a listener that may be used to hook into various actions within an OpBuilder.
Definition at line 255 of file Builders.h.
Constructor & Destructor Documentation
~Listener()
OpBuilder::Listener::~Listener () virtual default
Member Function Documentation
notifyBlockCreated()
virtual void mlir::OpBuilder::Listener::notifyBlockCreated (Block * block) inline virtual
Notification handler for when a block is created using the builder.
block is the block that was created.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 264 of file Builders.h.
Referenced by mlir::OpBuilder::createBlock().
notifyOperationInserted()
virtual void mlir::OpBuilder::Listener::notifyOperationInserted (Operation * op) inline virtual
Notification handler for when an operation is inserted into the builder.
op is the operation that was inserted.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 260 of file Builders.h.
Referenced by mlir::OpBuilder::clone(), createAsyncDispatchFunction(), createOrFold(), createParallelComputeFunction(), and mlir::OpBuilder::insert().
The documentation for this struct was generated from the following files:
include/mlir/IR/Builders.h
lib/IR/Builders.cpp