MLIR: lib/IR/SubElementInterfaces.cpp File Reference
SubElementInterfaces.cpp File Reference
#include "mlir/IR/SubElementInterfaces.h"
#include "mlir/IR/Operation.h"
#include "llvm/ADT/DenseSet.h"
#include "mlir/IR/SubElementAttrInterfaces.cpp.inc"
#include "mlir/IR/SubElementTypeInterfaces.cpp.inc"
Functions
template<typename InterfaceT >
static void walkSubElementsImpl (InterfaceT interface, function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn, DenseSet< Attribute > &visitedAttrs, DenseSet< Type > &visitedTypes)
template<typename T >
static void updateSubElementImpl (T element, AttrTypeReplacer &replacer, DenseMap< T, T > &elementMap, SmallVectorImpl< T > &newElements, FailureOr< bool > &changed)
Function Documentation
updateSubElementImpl()
template<typename T > static void updateSubElementImpl (T element, AttrTypeReplacer & replacer, DenseMap< T, T > & elementMap, SmallVectorImpl< T > & newElements, FailureOr< bool > & changed) static
Definition at line 149 of file SubElementInterfaces.cpp.
References mlir::failed(), mlir::failure(), and mlir::AttrTypeReplacer::replace().
walkSubElementsImpl()
template<typename InterfaceT > static void walkSubElementsImpl (InterfaceT interface, function_ref< void(Attribute)> walkAttrsFn, function_ref< void(Type)> walkTypesFn, DenseSet< Attribute > & visitedAttrs, DenseSet< Type > & visitedTypes) static
Definition at line 24 of file SubElementInterfaces.cpp.
References mlir::Attribute::dyn_cast(), and mlir::Attribute::hasTrait().