MLIR: lib/Dialect/Linalg/Transforms/Tiling.cpp File Reference
Tiling.cpp File Reference
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/Utils/Utils.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/Transforms/Transforms.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/CommandLine.h"
#include <utility>
#include "mlir/Dialect/Linalg/Passes.h.inc"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_LINALGTILINGPASS
#define DEBUG_TYPE "linalg-tiling"
#define GET_OP_LIST
Functions
static bool isZero (OpFoldResult v)
static void emitIsPositiveIndexAssertion (ImplicitLocOpBuilder &b, OpFoldResult value)
Asserts that the given index-typed value is strictly positive.
static bool canOmitTileOffsetInBoundsCheck (OpFoldResult tileSize, OpFoldResult numThreads, OpFoldResult iterationSize)
Returns true if the maximum tile offset tileSize * numThreads-1 is less than iterationSize.
static OpFoldResult buildMax (OpBuilder &b, Location loc, ArrayRef< OpFoldResult > vals)
Build an affine_max of all the vals.
static OpFoldResult buildMin (OpBuilder &b, Location loc, ArrayRef< OpFoldResult > vals)
Build an affine_min of all the vals.
static void calculateTileOffsetsAndSizes (RewriterBase &b, Location loc, scf::ForeachThreadOp foreachThreadOp, ArrayRef< OpFoldResult > numThreads, SmallVector< Range > loopRanges, bool omitTileOffsetBoundsCheck, Optional< ArrayRef< OpFoldResult >> nominalTileSizes, SmallVector< OpFoldResult > &tiledOffsets, SmallVector< OpFoldResult > &tiledSizes)
Fill out the tiledOffsets and tiledSizes to be used to tile to a given number of threads.
static FailureOr< ForeachThreadTilingResult > tileToForeachThreadOpImpl (RewriterBase &b, TilingInterface op, ArrayRef< OpFoldResult > numThreads, Optional< ArrayRef< OpFoldResult >> nominalTileSizes, Optional< ArrayAttr > mapping, bool omitTileOffsetBoundsCheck)
Rewrite a TilingInterface op to a tiled scf.foreach_thread.
static Value insertSliceIntoTensor (OpBuilder &b, Location loc, tensor::ExtractSliceOp sliceOp, Value source, Value dest)
template<typename LoopTy >
static FailureOr< TiledLinalgOp > tileLinalgOpImpl (RewriterBase &b, LinalgOp op, ArrayRef< OpFoldResult > tileSizes, const LinalgTilingOptions &options)
template<typename LoopTy >
static FailureOr< TiledLinalgOp > tileLinalgOpImpl (RewriterBase &b, LinalgOp op, const LinalgTilingOptions &options)
static LogicalResult tilePadOp (RewriterBase &builder, tensor::PadOp op, tensor::PadOp &newPadOp, LoopNest &loopNest, const LinalgTilingOptions &options)
Generate a loop nest around a given tensor::PadOp (for tiling).
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-tiling"
Definition at line 41 of file Tiling.cpp.
GEN_PASS_DEF_LINALGTILINGPASS
#define GEN_PASS_DEF_LINALGTILINGPASS
Definition at line 33 of file Tiling.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
buildMax()
static OpFoldResult buildMax (OpBuilder & b, Location loc, ArrayRef< OpFoldResult > vals) static
Build an affine_max of all the vals.
Definition at line 199 of file Tiling.cpp.
References mlir::Location::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), and mlir::makeComposedFoldedAffineMax().
Referenced by calculateTileOffsetsAndSizes().
buildMin()
static OpFoldResult buildMin (OpBuilder & b, Location loc, ArrayRef< OpFoldResult > vals) static
Build an affine_min of all the vals.
Definition at line 207 of file Tiling.cpp.
References mlir::Location::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), and mlir::makeComposedFoldedAffineMin().
Referenced by calculateTileOffsetsAndSizes().
calculateTileOffsetsAndSizes()
static void calculateTileOffsetsAndSizes (RewriterBase & b, Location loc, scf::ForeachThreadOp foreachThreadOp, ArrayRef< OpFoldResult > numThreads, SmallVector< Range > loopRanges, bool omitTileOffsetBoundsCheck, Optional< ArrayRef< OpFoldResult >> nominalTileSizes, SmallVector< OpFoldResult > & tiledOffsets, SmallVector< OpFoldResult > & tiledSizes) static
Fill out the tiledOffsets and tiledSizes to be used to tile to a given number of threads.
Definition at line 216 of file Tiling.cpp.
References mlir::bindDims(), mlir::bindSymbols(), buildMax(), buildMin(), canOmitTileOffsetInBoundsCheck(), mlir::AffineExpr::ceilDiv(), mlir::Builder::getContext(), mlir::Builder::getIndexAttr(), mlir::isConstantIntValue(), isZero(), and mlir::makeComposedFoldedAffineApply().
Referenced by mlir::linalg::tileReductionUsingForeachThread(), and tileToForeachThreadOpImpl().
canOmitTileOffsetInBoundsCheck()
static bool canOmitTileOffsetInBoundsCheck (OpFoldResult tileSize, OpFoldResult numThreads, OpFoldResult iterationSize) static
Returns true if the maximum tile offset tileSize * numThreads-1 is less than iterationSize.
Definition at line 187 of file Tiling.cpp.
References mlir::getConstantIntValue().
Referenced by calculateTileOffsetsAndSizes().
emitIsPositiveIndexAssertion()
static void emitIsPositiveIndexAssertion (ImplicitLocOpBuilder & b, OpFoldResult value) static
Asserts that the given index-typed value is strictly positive.
If the value is an attribute, asserts at compile time, otherwise emits an assertion checked at runtime.
Definition at line 100 of file Tiling.cpp.
References mlir::ImplicitLocOpBuilder::create(), mlir::Builder::getStringAttr(), and value.
Referenced by mlir::linalg::computeMultiTileSizes().
insertSliceIntoTensor()
static Value insertSliceIntoTensor (OpBuilder & b, Location loc, tensor::ExtractSliceOp sliceOp, Value source, Value dest) static
Definition at line 550 of file Tiling.cpp.
References mlir::OpBuilder::create().
Referenced by tilePadOp().
isZero()
static bool isZero (OpFoldResult v) static
Definition at line 43 of file Tiling.cpp.
References mlir::Value::getDefiningOp().
Referenced by calculateTileOffsetsAndSizes(), isAlloc(), mlir::linalg::makeTiledLoopRanges(), tileLinalgOpImpl(), and tilePadOp().
tileLinalgOpImpl() [1/2]
template<typename LoopTy > static FailureOr<TiledLinalgOp> tileLinalgOpImpl (RewriterBase & b, LinalgOp op, ArrayRef< OpFoldResult > tileSizes, const LinalgTilingOptions & options) static
Definition at line 561 of file Tiling.cpp.
References mlir::applyPermutationToVector(), mlir::OpBuilder::clone(), mlir::detail::enumerate(), mlir::failure(), mlir::Builder::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::AffineMap::getPermutationMap(), mlir::inversePermutation(), mlir::linalg::isParallelIterator(), isZero(), mlir::linalg::makeTiledLoopRanges(), mlir::linalg::TiledLinalgOp::op, options, and mlir::linalg::TiledLinalgOp::tensorResults.
tileLinalgOpImpl() [2/2]
template<typename LoopTy > static FailureOr<TiledLinalgOp> tileLinalgOpImpl (RewriterBase & b, LinalgOp op, const LinalgTilingOptions & options) static
Definition at line 711 of file Tiling.cpp.
References mlir::failure(), mlir::getAsOpFoldResult(), mlir::Builder::getIndexAttr(), options, and mlir::OpBuilder::setInsertionPoint().
tilePadOp()
static LogicalResult tilePadOp (RewriterBase & builder, tensor::PadOp op, tensor::PadOp & newPadOp, LoopNest & loopNest, const LinalgTilingOptions & options) static
Generate a loop nest around a given tensor::PadOp (for tiling).
newPadOp and loopNest are output parameters that return the new (tiled) tensor::PadOp and the loop nest.
Definition at line 748 of file Tiling.cpp.
References mlir::scf::buildLoopNest(), mlir::OpBuilder::clone(), mlir::linalg::computeTileOffsets(), mlir::linalg::computeTileSizes(), mlir::failed(), mlir::failure(), mlir::getAsOpFoldResult(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexAttr(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::tensor::getOrCreateDestinations(), mlir::getValueOrCreateConstantIndexOp(), insertSliceIntoTensor(), isZero(), mlir::linalg::makeTiledShape(), options, mlir::OpBuilder::setInsertionPoint(), and mlir::success().
tileToForeachThreadOpImpl()
static FailureOr<ForeachThreadTilingResult> tileToForeachThreadOpImpl (RewriterBase & b, TilingInterface op, ArrayRef< OpFoldResult > numThreads, Optional< ArrayRef< OpFoldResult >> nominalTileSizes, Optional< ArrayAttr > mapping, bool omitTileOffsetBoundsCheck) static
Rewrite a TilingInterface op to a tiled scf.foreach_thread.
The tiling is specified by the number of tiles/threads numThreads and the optional nominal tile size nominalTileSizes. If nominalTilSizes is not specified, then it is derived from numThreads as ceilDiv(dimSize[i], numThreads[i]). If non-empty, the mapping is added as an attribute to the resulting scf.foreach_thread. A zero tile sizes indicate that the dimension is not tiled, and can be thought of as tiling by the full size of data. It is the user's responsibility to ensure that numThreads is a valid tiling specification (i.e. that only tiles parallel dimensions, e.g. in the Linalg case). If omitTileOffsetBoundsCheck is true, then the function will assume that tileSize[i] * (numThread[i] -1) <= dimSize[i] holds.
Definition at line 296 of file Tiling.cpp.
References calculateTileOffsetsAndSizes(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::OpBuilder::InsertPoint::getBlock(), mlir::Builder::getIndexAttr(), mlir::tensor::getOrCreateDestinations(), mlir::OpBuilder::InsertPoint::getPoint(), mlir::getValueOrCreateConstantIndexOp(), mlir::isConstantIntValue(), mlir::OpBuilder::saveInsertionPoint(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::linalg::tileToForeachThreadOp(), and mlir::linalg::tileToForeachThreadOpUsingTileSizes().