MLIR: lib/Tools/mlir-translate/Translation.cpp File Reference
Translation.cpp File Reference
#include "mlir/Tools/mlir-translate/Translation.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Tools/ParseUtilities.h"
#include "llvm/Support/SourceMgr.h"
Classes
struct TranslationOptions
Functions
static llvm::StringMap< Translation > & getTranslationRegistry ()
Get the mutable static map between registered file-to-file MLIR translations.
static void registerTranslation (StringRef name, StringRef description, Optional< llvm::Align > inputAlignment, const TranslateFunction &function)
Register the given translation.
static void registerTranslateToMLIRFunction (StringRef name, StringRef description, Optional< llvm::Align > inputAlignment, const TranslateSourceMgrToMLIRFunction &function)
Variables
static llvm::ManagedStatic< TranslationOptions > clOptions
Function Documentation
getTranslationRegistry()
static llvm::StringMap<Translation>& getTranslationRegistry () static
Get the mutable static map between registered file-to-file MLIR translations.
Definition at line 45 of file Translation.cpp.
Referenced by registerTranslation(), and mlir::TranslationParser::TranslationParser().
registerTranslateToMLIRFunction()
static void registerTranslateToMLIRFunction (StringRef name, StringRef description, Optional< llvm::Align > inputAlignment, const TranslateSourceMgrToMLIRFunction & function) static
Definition at line 75 of file Translation.cpp.
References mlir::failed(), mlir::failure(), mlir::OwningOpRef< OpTy >::get(), registerTranslation(), mlir::success(), and mlir::verify().
registerTranslation()
static void registerTranslation (StringRef name, StringRef description, Optional< llvm::Align > inputAlignment, const TranslateFunction & function) static
Register the given translation.
Definition at line 51 of file Translation.cpp.
References getTranslationRegistry().
Referenced by registerTranslateToMLIRFunction(), and mlir::TranslateRegistration::TranslateRegistration().
Variable Documentation
clOptions
llvm::ManagedStatic<TranslationOptions> clOptions static
Definition at line 35 of file Translation.cpp.
Referenced by mlir::registerTranslationCLOptions().