MLIR: lib/Dialect/Vector/Transforms/VectorInsertExtractStridedSliceRewritePatterns.cpp File Reference
VectorInsertExtractStridedSliceRewritePatterns.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Transforms/VectorRewritePatterns.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/PatternMatch.h"
Classes
class DecomposeDifferentRankInsertStridedSlice
RewritePattern for InsertStridedSliceOp where source and destination vectors have different ranks.
class ConvertSameRankInsertStridedSliceIntoShuffle
RewritePattern for InsertStridedSliceOp where source and destination vectors have the same rank.
class Convert1DExtractStridedSliceIntoShuffle
RewritePattern for ExtractStridedSliceOp where source and destination vectors are 1-D.
class Convert1DExtractStridedSliceIntoExtractInsertChain
For a 1-D ExtractStridedSlice, breaks it down into a chain of Extract ops to extract each element from the source, and then a chain of Insert ops to insert to the target vector.
class DecomposeNDExtractStridedSlice
RewritePattern for ExtractStridedSliceOp where the source vector is n-D.
Functions
static Value insertOne (PatternRewriter &rewriter, Location loc, Value from, Value into, int64_t offset)
static Value extractOne (PatternRewriter &rewriter, Location loc, Value vector, int64_t offset)
Function Documentation
extractOne()
static Value extractOne (PatternRewriter & rewriter, Location loc, Value vector, int64_t offset) static
Definition at line 33 of file VectorInsertExtractStridedSliceRewritePatterns.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), and mlir::Value::getType().
insertOne()
static Value insertOne (PatternRewriter & rewriter, Location loc, Value from, Value into, int64_t offset) static
Definition at line 22 of file VectorInsertExtractStridedSliceRewritePatterns.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), and mlir::Value::getType().