MLIR: lib/Conversion/VectorToGPU/VectorToGPU.cpp File Reference
VectorToGPU.cpp File Reference
#include "mlir/Conversion/VectorToGPU/VectorToGPU.h"
#include <type_traits>
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/NVGPU/IR/NVGPUDialect.h"
#include "mlir/Dialect/NVGPU/Utils/MMAUtils.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/Dialect/Vector/Utils/VectorUtils.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define GEN_PASS_DEF_CONVERTVECTORTOGPU
Functions
template<typename TransferOpType >
static void getXferIndices (OpBuilder &b, TransferOpType xferOp, AffineMap offsetMap, ArrayRef< Value > dimValues, SmallVector< Value, 4 > &indices)
For a vector TransferOpType xferOp, an empty indices vector, and an AffineMap representing offsets to apply to indices, the function fills indices with the original indices plus the offsets.
static bool contractSupportsMMAMatrixType (vector::ContractionOp contract, bool useNvGpu)
static llvm::Optional< int64_t > getMemrefConstantHorizontalStride (ShapedType type)
static bool transferReadSupportsMMAMatrixType (vector::TransferReadOp readOp, bool useNvGpu)
static bool transferWriteSupportsMMAMatrixType (vector::TransferWriteOp writeOp)
static bool constantSupportsMMAMatrixType (arith::ConstantOp constantOp)
Return true if the constant is a splat to a 2D vector so that it can be converted to a MMA constant matrix op.
static bool broadcastSupportsMMAMatrixType (vector::BroadcastOp broadcastOp)
Return true if this is a broadcast from scalar to a 2D vector.
static llvm::Optional< gpu::MMAElementwiseOp > convertElementwiseOpToMMA (Operation *op)
Return the MMA elementwise enum associated with op if it is supported.
static bool elementwiseSupportsMMAMatrixType (Operation *op)
Return true if the op is supported as elementwise op on MMAMatrix type.
static bool extractStridedSliceSupportsMMAMatrixType (vector::ExtractStridedSliceOp op)
Returns true if the extract strided slice op is supported with mma.sync path.
static bool supportsMMaMatrixType (Operation *op, bool useNvGpu)
static SetVector< Operation * > getSliceContract (Operation *op, TransitiveFilter backwardFilter, TransitiveFilter forwardFilter)
Return an unsorted slice handling scf.for region differently than getSlice.
static SetVector< Operation * > getOpToConvert (mlir::Operation *op, bool useNvGpu)
template<typename OpTy >
static const char * inferFragType (OpTy op)
static void convertTransferReadOp (vector::TransferReadOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertTransferWriteOp (vector::TransferWriteOp op, llvm::DenseMap< Value, Value > &valueMapping)
static VectorType getMmaSyncVectorOperandType (const nvgpu::FragmentElementInfo &regInfo)
Returns the vector type which represents a matrix fragment.
static LogicalResult convertConstantOpMmaSync (arith::ConstantOp op, llvm::DenseMap< Value, Value > &valueMapping)
Convert a 2D splat ConstantOp to a SubgroupMmaConstantMatrix op.
static LogicalResult creatLdMatrixCompatibleLoads (vector::TransferReadOp op, OpBuilder &builder, llvm::DenseMap< Value, Value > &valueMapping)
static LogicalResult createNonLdMatrixLoads (vector::TransferReadOp op, OpBuilder &builder, llvm::DenseMap< Value, Value > &valueMapping)
static LogicalResult convertTransferReadToLoads (vector::TransferReadOp op, llvm::DenseMap< Value, Value > &valueMapping)
Converts a vector.transfer_read operation directly to either a vector.load or a nvgpu.ldmatrix operation.
static LogicalResult convertTransferWriteToStores (vector::TransferWriteOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > &results)
static LogicalResult convertExtractStridedSlice (vector::ExtractStridedSliceOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertContractOp (vector::ContractionOp op, llvm::DenseMap< Value, Value > &valueMapping)
static LogicalResult convertContractOpToMmaSync (vector::ContractionOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertConstantOp (arith::ConstantOp op, llvm::DenseMap< Value, Value > &valueMapping)
Convert a 2D splat ConstantOp to a SubgroupMmaConstantMatrix op.
static void convertBroadcastOp (vector::BroadcastOp op, llvm::DenseMap< Value, Value > &valueMapping)
Convert a vector.broadcast from scalar to a SubgroupMmaConstantMatrix op.
static scf::ForOp replaceForOpWithNewSignature (OpBuilder &b, scf::ForOp loop, ValueRange newIterOperands)
static void convertForOp (scf::ForOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertYieldOp (scf::YieldOp op, llvm::DenseMap< Value, Value > &valueMapping)
static void convertElementwiseOp (Operation *op, gpu::MMAElementwiseOp opType, llvm::DenseMap< Value, Value > &valueMapping)
Convert an elementwise op to the equivalent elementwise op on MMA matrix.
Macro Definition Documentation
GEN_PASS_DEF_CONVERTVECTORTOGPU
#define GEN_PASS_DEF_CONVERTVECTORTOGPU
Definition at line 35 of file VectorToGPU.cpp.
Function Documentation
broadcastSupportsMMAMatrixType()
static bool broadcastSupportsMMAMatrixType (vector::BroadcastOp broadcastOp) static
Return true if this is a broadcast from scalar to a 2D vector.
Definition at line 168 of file VectorToGPU.cpp.
Referenced by convertBroadcastOp(), and supportsMMaMatrixType().
constantSupportsMMAMatrixType()
static bool constantSupportsMMAMatrixType (arith::ConstantOp constantOp) static
Return true if the constant is a splat to a 2D vector so that it can be converted to a MMA constant matrix op.
Definition at line 160 of file VectorToGPU.cpp.
Referenced by convertConstantOp(), and supportsMMaMatrixType().
contractSupportsMMAMatrixType()
static bool contractSupportsMMAMatrixType (vector::ContractionOp contract, bool useNvGpu) static
Definition at line 68 of file VectorToGPU.cpp.
References mlir::bindDims(), contract(), mlir::AffineMap::inferFromExprList(), mlir::vector::isParallelIterator(), and mlir::vector::isReductionIterator().
Referenced by supportsMMaMatrixType().
convertBroadcastOp()
static void convertBroadcastOp (vector::BroadcastOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Convert a vector.broadcast from scalar to a SubgroupMmaConstantMatrix op.
Definition at line 829 of file VectorToGPU.cpp.
References broadcastSupportsMMAMatrixType(), mlir::OpBuilder::create(), mlir::gpu::MMAMatrixType::get(), and inferFragType().
Referenced by mlir::convertVectorToMMAOps().
convertConstantOp()
static void convertConstantOp (arith::ConstantOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Convert a 2D splat ConstantOp to a SubgroupMmaConstantMatrix op.
Definition at line 811 of file VectorToGPU.cpp.
References constantSupportsMMAMatrixType(), mlir::OpBuilder::create(), mlir::gpu::MMAMatrixType::get(), and inferFragType().
Referenced by mlir::convertVectorToMMAOps().
convertConstantOpMmaSync()
static LogicalResult convertConstantOpMmaSync (arith::ConstantOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Convert a 2D splat ConstantOp to a SubgroupMmaConstantMatrix op.
Definition at line 481 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::nvgpu::getMmaSyncRegisterType(), getMmaSyncVectorOperandType(), mlir::nvgpu::getWarpMatrixInfo(), and mlir::success().
Referenced by mlir::convertVectorToNVVMCompatibleMMASync().
convertContractOp()
static void convertContractOp (vector::ContractionOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 783 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), and mlir::Value::getType().
Referenced by mlir::convertVectorToMMAOps().
convertContractOpToMmaSync()
static LogicalResult convertContractOpToMmaSync (vector::ContractionOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 795 of file VectorToGPU.cpp.
References mlir::AffineExpr::cast(), mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), getShape(), and mlir::success().
Referenced by mlir::convertVectorToNVVMCompatibleMMASync().
convertElementwiseOp()
static void convertElementwiseOp (Operation * op, gpu::MMAElementwiseOp opType, llvm::DenseMap< Value, Value > & valueMapping) static
Convert an elementwise op to the equivalent elementwise op on MMA matrix.
Definition at line 911 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), and mlir::Operation::getResult().
Referenced by mlir::convertVectorToMMAOps().
convertElementwiseOpToMMA()
static llvm::Optional<gpu::MMAElementwiseOp> convertElementwiseOpToMMA (Operation * op) static
Return the MMA elementwise enum associated with op if it is supported.
Return llvm::None otherwise.
Definition at line 176 of file VectorToGPU.cpp.
Referenced by mlir::convertVectorToMMAOps(), and elementwiseSupportsMMAMatrixType().
convertExtractStridedSlice()
static LogicalResult convertExtractStridedSlice (vector::ExtractStridedSliceOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 713 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::nvgpu::getMmaSyncRegisterType(), mlir::nvgpu::getWarpMatrixInfo(), populateFromInt64AttrArray(), and mlir::success().
Referenced by mlir::convertVectorToNVVMCompatibleMMASync().
convertForOp()
static void convertForOp (scf::ForOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 868 of file VectorToGPU.cpp.
References mlir::detail::enumerate(), mlir::Block::getArgument(), and replaceForOpWithNewSignature().
Referenced by mlir::convertVectorToMMAOps(), and mlir::convertVectorToNVVMCompatibleMMASync().
convertTransferReadOp()
static void convertTransferReadOp (vector::TransferReadOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 430 of file VectorToGPU.cpp.
References mlir::AffineExpr::cast(), mlir::OpBuilder::create(), mlir::gpu::MMAMatrixType::get(), mlir::Builder::getIndexAttr(), getMemrefConstantHorizontalStride(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::getResult(), mlir::AffineConstantExpr::getValue(), inferFragType(), mlir::AffineExpr::isa(), and transferReadSupportsMMAMatrixType().
Referenced by mlir::convertVectorToMMAOps().
convertTransferReadToLoads()
static LogicalResult convertTransferReadToLoads (vector::TransferReadOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Converts a vector.transfer_read operation directly to either a vector.load or a nvgpu.ldmatrix operation.
This function should only be used when converting to nvgpu.mma.sync operations.
Definition at line 638 of file VectorToGPU.cpp.
References createNonLdMatrixLoads(), creatLdMatrixCompatibleLoads(), mlir::failed(), mlir::failure(), mlir::detail::getMemorySpaceAsInt(), mlir::nvgpu::getWarpMatrixInfo(), and mlir::nvgpu::inferTileWidthInBits().
Referenced by mlir::convertVectorToNVVMCompatibleMMASync().
convertTransferWriteOp()
static void convertTransferWriteOp (vector::TransferWriteOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 454 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::Operation::erase(), mlir::Builder::getIndexAttr(), getMemrefConstantHorizontalStride(), and transferWriteSupportsMMAMatrixType().
Referenced by mlir::convertVectorToMMAOps().
convertTransferWriteToStores()
static LogicalResult convertTransferWriteToStores (vector::TransferWriteOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 669 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::nvgpu::getLaneIdAndValueIdToOperandCoord(), mlir::nvgpu::getMmaSyncRegisterType(), getMmaSyncVectorOperandType(), mlir::nvgpu::getWarpMatrixInfo(), and mlir::success().
Referenced by mlir::convertVectorToNVVMCompatibleMMASync().
convertYieldOp()
static void convertYieldOp (scf::YieldOp op, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 892 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), and mlir::Operation::erase().
Referenced by mlir::convertVectorToMMAOps(), and mlir::convertVectorToNVVMCompatibleMMASync().
createNonLdMatrixLoads()
static LogicalResult createNonLdMatrixLoads (vector::TransferReadOp op, OpBuilder & builder, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 550 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexType(), mlir::nvgpu::getLaneIdAndValueIdToOperandCoord(), mlir::nvgpu::getMmaSyncRegisterType(), getMmaSyncVectorOperandType(), mlir::nvgpu::getWarpMatrixInfo(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), and mlir::success().
Referenced by convertTransferReadToLoads().
creatLdMatrixCompatibleLoads()
static LogicalResult creatLdMatrixCompatibleLoads (vector::TransferReadOp op, OpBuilder & builder, llvm::DenseMap< Value, Value > & valueMapping) static
Definition at line 506 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::nvgpu::getLaneIdToLdMatrixMatrixCoord(), mlir::nvgpu::getLdMatrixParams(), mlir::nvgpu::getMmaSyncRegisterType(), getMmaSyncVectorOperandType(), mlir::nvgpu::getWarpMatrixInfo(), and mlir::success().
Referenced by convertTransferReadToLoads().
elementwiseSupportsMMAMatrixType()
static bool elementwiseSupportsMMAMatrixType (Operation * op) static
Return true if the op is supported as elementwise op on MMAMatrix type.
Definition at line 191 of file VectorToGPU.cpp.
References convertElementwiseOpToMMA().
Referenced by supportsMMaMatrixType().
extractStridedSliceSupportsMMAMatrixType()
static bool extractStridedSliceSupportsMMAMatrixType (vector::ExtractStridedSliceOp op) static
Returns true if the extract strided slice op is supported with mma.sync path.
Definition at line 198 of file VectorToGPU.cpp.
References mlir::nvgpu::B, mlir::nvgpu::C, mlir::failed(), mlir::nvgpu::getUserContract(), and mlir::nvgpu::getWarpMatrixInfo().
Referenced by supportsMMaMatrixType().
getMemrefConstantHorizontalStride()
static llvm::Optional<int64_t> getMemrefConstantHorizontalStride (ShapedType type) static
Definition at line 98 of file VectorToGPU.cpp.
References mlir::failed(), and mlir::getStridesAndOffset().
Referenced by convertTransferReadOp(), convertTransferWriteOp(), transferReadSupportsMMAMatrixType(), and transferWriteSupportsMMAMatrixType().
getMmaSyncVectorOperandType()
static VectorType getMmaSyncVectorOperandType (const nvgpu::FragmentElementInfo & regInfo) static
Returns the vector type which represents a matrix fragment.
Definition at line 470 of file VectorToGPU.cpp.
References mlir::Type::dyn_cast(), mlir::nvgpu::FragmentElementInfo::elementsPerRegister, mlir::nvgpu::FragmentElementInfo::numRegistersPerFragment, and mlir::nvgpu::FragmentElementInfo::registerLLVMType.
Referenced by convertConstantOpMmaSync(), convertTransferWriteToStores(), createNonLdMatrixLoads(), and creatLdMatrixCompatibleLoads().
getOpToConvert()
static SetVector<Operation *> getOpToConvert (mlir::Operation * op, bool useNvGpu) static
Definition at line 281 of file VectorToGPU.cpp.
References contract(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), getSliceContract(), supportsMMaMatrixType(), mlir::topologicalSort(), and mlir::Operation::walk().
Referenced by mlir::convertVectorToMMAOps(), and mlir::convertVectorToNVVMCompatibleMMASync().
getSliceContract()
static SetVector<Operation *> getSliceContract (Operation * op, TransitiveFilter backwardFilter, TransitiveFilter forwardFilter) static
Return an unsorted slice handling scf.for region differently than getSlice.
In scf.for we only want to include as part of the slice elements that are part of the use/def chain.
Definition at line 244 of file VectorToGPU.cpp.
References mlir::getBackwardSlice(), and mlir::getForwardSlice().
Referenced by getOpToConvert().
getXferIndices()
template<typename TransferOpType > static void getXferIndices (OpBuilder & b, TransferOpType xferOp, AffineMap offsetMap, ArrayRef< Value > dimValues, SmallVector< Value, 4 > & indices) static
For a vector TransferOpType xferOp, an empty indices vector, and an AffineMap representing offsets to apply to indices, the function fills indices with the original indices plus the offsets.
The offsets are applied by taking into account the permutation map of the transfer op. If the offsetMap has dimension placeholders, those should be provided in dimValues.
Definition at line 48 of file VectorToGPU.cpp.
References mlir::Builder::getAffineDimExpr(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getResult(), and mlir::makeComposedAffineApply().
inferFragType()
template<typename OpTy > static const char* inferFragType (OpTy op) static
Definition at line 417 of file VectorToGPU.cpp.
References contract(), and mlir::Operation::getUsers().
Referenced by convertBroadcastOp(), convertConstantOp(), and convertTransferReadOp().
populateFromInt64AttrArray()
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > & results) static
Definition at line 706 of file VectorToGPU.cpp.
Referenced by convertExtractStridedSlice().
replaceForOpWithNewSignature()
static scf::ForOp replaceForOpWithNewSignature (OpBuilder & b, scf::ForOp loop, ValueRange newIterOperands) static
Definition at line 844 of file VectorToGPU.cpp.
References mlir::OpBuilder::create(), mlir::Operation::erase(), and mlir::OpBuilder::setInsertionPoint().
Referenced by convertForOp().
supportsMMaMatrixType()
static bool supportsMMaMatrixType (Operation * op, bool useNvGpu) static
Definition at line 222 of file VectorToGPU.cpp.
References broadcast(), broadcastSupportsMMAMatrixType(), constantSupportsMMAMatrixType(), contract(), contractSupportsMMAMatrixType(), elementwiseSupportsMMAMatrixType(), extractStridedSliceSupportsMMAMatrixType(), transferReadSupportsMMAMatrixType(), and transferWriteSupportsMMAMatrixType().
Referenced by getOpToConvert().
transferReadSupportsMMAMatrixType()
static bool transferReadSupportsMMAMatrixType (vector::TransferReadOp readOp, bool useNvGpu) static
Definition at line 117 of file VectorToGPU.cpp.
References mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::Builder::getAffineDimExpr(), getMemrefConstantHorizontalStride(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getPermutationMap(), and mlir::AffineMap::isMinorIdentity().
Referenced by convertTransferReadOp(), and supportsMMaMatrixType().
transferWriteSupportsMMAMatrixType()
static bool transferWriteSupportsMMAMatrixType (vector::TransferWriteOp writeOp) static
Definition at line 142 of file VectorToGPU.cpp.
References getMemrefConstantHorizontalStride().
Referenced by convertTransferWriteOp(), and supportsMMaMatrixType().